import { db } from '../firebase/config.js';
import { collection, addDoc, getDocs, query, where, deleteDoc } from 'firebase/firestore';

export const allQuestions = [
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Evaluate the product, simplifying where possible: $\\frac{1}{3} \\times \\frac{2}{5}$`,
    options: [`\\frac{2}{16}`, `\\frac{3}{15}`, `\\frac{2}{15}`, `\\frac{15}{2}`],
    answer: 2,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{1 \\times 2}{3 \\times 5} = \\frac{2}{15}$</p><p><strong>Step 2: Check for simplification</strong><br>The fraction $\\frac{2}{15}$ is already in its simplest form.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Evaluate the product, simplifying where possible: $\\frac{2}{5} \\times \\frac{3}{7}$`,
    options: [`\\frac{6}{36}`, `\\frac{7}{35}`, `\\frac{6}{35}`, `\\frac{35}{6}`],
    answer: 2,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{2 \\times 3}{5 \\times 7} = \\frac{6}{35}$</p><p><strong>Step 2: Check for simplification</strong><br>The fraction $\\frac{6}{35}$ is already in its simplest form.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Evaluate the product, simplifying where possible: $\\frac{1}{3} \\times \\frac{1}{5}$`,
    options: [`\\frac{1}{16}`, `\\frac{2}{15}`, `\\frac{1}{15}`, `15`],
    answer: 2,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{1 \\times 1}{3 \\times 5} = \\frac{1}{15}$</p><p><strong>Step 2: Check for simplification</strong><br>The fraction $\\frac{1}{15}$ is already in its simplest form.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Evaluate the product, simplifying where possible: $\\frac{1}{4} \\times \\frac{3}{5}$`,
    options: [`\\frac{3}{21}`, `\\frac{3}{20}`, `\\frac{4}{20}`, `\\frac{20}{3}`],
    answer: 1,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{1 \\times 3}{4 \\times 5} = \\frac{3}{20}$</p><p><strong>Step 2: Check for simplification</strong><br>The fraction $\\frac{3}{20}$ is already in its simplest form.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Evaluate the product, simplifying where possible: $\\frac{4}{3} \\times \\frac{2}{5}$`,
    options: [`\\frac{8}{15}`, `\\frac{15}{8}`, `\\frac{9}{15}`, `\\frac{8}{16}`],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{4 \\times 2}{3 \\times 5} = \\frac{8}{15}$</p><p><strong>Step 2: Check for simplification</strong><br>The fraction $\\frac{8}{15}$ is already in its simplest form.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Evaluate the product, simplifying where possible: $\\frac{4}{9} \\times \\frac{2}{7}$`,
    options: [`\\frac{8}{64}`, `\\frac{63}{8}`, `\\frac{8}{63}`, `\\frac{9}{63}`],
    answer: 2,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{4 \\times 2}{9 \\times 7} = \\frac{8}{63}$</p><p><strong>Step 2: Check for simplification</strong><br>The fraction $\\frac{8}{63}$ is already in its simplest form.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Evaluate the product, simplifying where possible: $\\frac{5}{3} \\times \\frac{5}{4}$`,
    options: [`\\frac{25}{13}`, `\\frac{12}{25}`, `\\frac{25}{12}`, `\\frac{26}{12}`],
    answer: 2,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{5 \\times 5}{3 \\times 4} = \\frac{25}{12}$</p><p><strong>Step 2: Check for simplification</strong><br>The fraction $\\frac{25}{12}$ is already in its simplest form.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Evaluate the product, simplifying where possible: $\\frac{5}{2} \\times \\frac{3}{8}$`,
    options: [`\\frac{15}{16}`, `\\frac{15}{17}`, `\\frac{16}{16}`, `\\frac{16}{15}`],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{5 \\times 3}{2 \\times 8} = \\frac{15}{16}$</p><p><strong>Step 2: Check for simplification</strong><br>The fraction $\\frac{15}{16}$ is already in its simplest form.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Evaluate the product, simplifying where possible: $\\frac{5}{4} \\times \\frac{3}{5}$`,
    options: [`\\frac{4}{4}`, `\\frac{3}{4}`, `\\frac{4}{3}`, `\\frac{3}{5}`],
    answer: 1,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{5 \\times 3}{4 \\times 5} = \\frac{15}{20}$</p><p><strong>Step 2: Simplify the fraction</strong><br>Divide the numerator and denominator by their greatest common divisor ($5$):<br>$\\frac{15 \\div 5}{20 \\div 5} = \\frac{3}{4}$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Find: $3 \\times \\frac{2}{5}$`,
    options: [`\\frac{6}{5}`, `\\frac{5}{6}`, `\\frac{7}{5}`, `\\frac{6}{6}`],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{3 \\times 2}{1 \\times 5} = \\frac{6}{5}$</p><p><strong>Step 2: Check for simplification</strong><br>The fraction $\\frac{6}{5}$ is already in its simplest form.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Find: $5 \\times \\frac{2}{9}$`,
    options: [`\\frac{9}{10}`, `\\frac{11}{9}`, `\\frac{10}{9}`, `\\frac{10}{10}`],
    answer: 2,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{5 \\times 2}{1 \\times 9} = \\frac{10}{9}$</p><p><strong>Step 2: Check for simplification</strong><br>The fraction $\\frac{10}{9}$ is already in its simplest form.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Find: $\\frac{3}{10} \\times 7$`,
    options: [`\\frac{10}{21}`, `\\frac{21}{10}`, `\\frac{21}{11}`, `\\frac{22}{10}`],
    answer: 1,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{3 \\times 7}{10 \\times 1} = \\frac{21}{10}$</p><p><strong>Step 2: Check for simplification</strong><br>The fraction $\\frac{21}{10}$ is already in its simplest form.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Find: $7 \\times \\frac{3}{4}$`,
    options: [`\\frac{21}{5}`, `\\frac{22}{4}`, `\\frac{4}{21}`, `\\frac{21}{4}`],
    answer: 3,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{7 \\times 3}{1 \\times 4} = \\frac{21}{4}$</p><p><strong>Step 2: Check for simplification</strong><br>The fraction $\\frac{21}{4}$ is already in its simplest form.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Find: $\\frac{2}{5} \\times 6$`,
    options: [`\\frac{13}{5}`, `\\frac{5}{12}`, `\\frac{12}{5}`, `\\frac{12}{6}`],
    answer: 2,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{2 \\times 6}{5 \\times 1} = \\frac{12}{5}$</p><p><strong>Step 2: Check for simplification</strong><br>The fraction $\\frac{12}{5}$ is already in its simplest form.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Find: $\\frac{5}{12} \\times 5$`,
    options: [`\\frac{12}{25}`, `\\frac{25}{13}`, `\\frac{25}{12}`, `\\frac{26}{12}`],
    answer: 2,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{5 \\times 5}{12 \\times 1} = \\frac{25}{12}$</p><p><strong>Step 2: Check for simplification</strong><br>The fraction $\\frac{25}{12}$ is already in its simplest form.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Find: $\\frac{1}{4}$ of $\\frac{1}{3}$`,
    options: [`\\frac{1}{12}`, `\\frac{2}{12}`, `\\frac{1}{13}`, `12`],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Convert "of" to multiplication</strong><br>The word "of" means multiply: $\\frac{1}{4} \\times \\frac{1}{3}$.</p><p><strong>Step 2: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{1 \\times 1}{4 \\times 3} = \\frac{1}{12}$</p><p><strong>Step 3: Check for simplification</strong><br>The fraction $\\frac{1}{12}$ is already in its simplest form.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Find: $\\frac{1}{5}$ of $\\frac{3}{4}$`,
    options: [`\\frac{3}{21}`, `\\frac{3}{20}`, `\\frac{4}{20}`, `\\frac{20}{3}`],
    answer: 1,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Convert "of" to multiplication</strong><br>The word "of" means multiply: $\\frac{1}{5} \\times \\frac{3}{4}$.</p><p><strong>Step 2: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{1 \\times 3}{5 \\times 4} = \\frac{3}{20}$</p><p><strong>Step 3: Check for simplification</strong><br>The fraction $\\frac{3}{20}$ is already in its simplest form.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Find: $\\frac{3}{7}$ of $\\frac{5}{6}$`,
    options: [`\\frac{6}{14}`, `\\frac{14}{5}`, `\\frac{5}{15}`, `\\frac{5}{14}`],
    answer: 3,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Convert "of" to multiplication</strong><br>The word "of" means multiply: $\\frac{3}{7} \\times \\frac{5}{6}$.</p><p><strong>Step 2: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{3 \\times 5}{7 \\times 6} = \\frac{15}{42}$</p><p><strong>Step 3: Simplify the fraction</strong><br>Divide the numerator and denominator by their greatest common divisor ($3$):<br>$\\frac{15 \\div 3}{42 \\div 3} = \\frac{5}{14}$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Find: $\\frac{3}{4}$ of $\\frac{4}{3}$`,
    options: [`\\frac{2}{4}`, `2`, `1`, `\\frac{1}{2}`],
    answer: 2,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Convert "of" to multiplication</strong><br>The word "of" means multiply: $\\frac{3}{4} \\times \\frac{4}{3}$.</p><p><strong>Step 2: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{3 \\times 4}{4 \\times 3} = \\frac{12}{12}$</p><p><strong>Step 3: Simplify the fraction</strong><br>Divide the numerator and denominator by their greatest common divisor ($12$):<br>$\\frac{12 \\div 12}{12 \\div 12} = 1$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Find: $\\frac{7}{5}$ of $\\frac{2}{7}$`,
    options: [`\\frac{2}{6}`, `\\frac{3}{5}`, `\\frac{2}{5}`, `\\frac{5}{2}`],
    answer: 2,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Convert "of" to multiplication</strong><br>The word "of" means multiply: $\\frac{7}{5} \\times \\frac{2}{7}$.</p><p><strong>Step 2: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{7 \\times 2}{5 \\times 7} = \\frac{14}{35}$</p><p><strong>Step 3: Simplify the fraction</strong><br>Divide the numerator and denominator by their greatest common divisor ($7$):<br>$\\frac{14 \\div 7}{35 \\div 7} = \\frac{2}{5}$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Find: $\\frac{3}{8}$ of $\\frac{5}{2}$`,
    options: [`\\frac{16}{16}`, `\\frac{16}{15}`, `\\frac{15}{16}`, `\\frac{15}{17}`],
    answer: 2,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Convert "of" to multiplication</strong><br>The word "of" means multiply: $\\frac{3}{8} \\times \\frac{5}{2}$.</p><p><strong>Step 2: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{3 \\times 5}{8 \\times 2} = \\frac{15}{16}$</p><p><strong>Step 3: Check for simplification</strong><br>The fraction $\\frac{15}{16}$ is already in its simplest form.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Find: $\\frac{3}{5}$ of $7$`,
    options: [`\\frac{22}{5}`, `\\frac{21}{6}`, `\\frac{21}{5}`, `\\frac{5}{21}`],
    answer: 2,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Convert "of" to multiplication</strong><br>The word "of" means multiply: $\\frac{3}{5} \\times 7$.</p><p><strong>Step 2: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{3 \\times 7}{5 \\times 1} = \\frac{21}{5}$</p><p><strong>Step 3: Check for simplification</strong><br>The fraction $\\frac{21}{5}$ is already in its simplest form.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Find: $\\frac{2}{7}$ of $11$`,
    options: [`\\frac{7}{22}`, `\\frac{23}{7}`, `\\frac{22}{8}`, `\\frac{22}{7}`],
    answer: 3,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Convert "of" to multiplication</strong><br>The word "of" means multiply: $\\frac{2}{7} \\times 11$.</p><p><strong>Step 2: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{2 \\times 11}{7 \\times 1} = \\frac{22}{7}$</p><p><strong>Step 3: Check for simplification</strong><br>The fraction $\\frac{22}{7}$ is already in its simplest form.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Find: $\\frac{3}{2} \\times \\frac{8}{9}$`,
    options: [`\\frac{3}{4}`, `\\frac{4}{4}`, `\\frac{4}{3}`, `\\frac{5}{3}`],
    answer: 2,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{3 \\times 8}{2 \\times 9} = \\frac{24}{18}$</p><p><strong>Step 2: Simplify the fraction</strong><br>Divide the numerator and denominator by their greatest common divisor ($6$):<br>$\\frac{24 \\div 6}{18 \\div 6} = \\frac{4}{3}$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Find: $\\frac{4}{15} \\times \\frac{5}{7}$`,
    options: [`\\frac{21}{4}`, `\\frac{4}{22}`, `\\frac{5}{21}`, `\\frac{4}{21}`],
    answer: 3,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{4 \\times 5}{15 \\times 7} = \\frac{20}{105}$</p><p><strong>Step 2: Simplify the fraction</strong><br>Divide the numerator and denominator by their greatest common divisor ($5$):<br>$\\frac{20 \\div 5}{105 \\div 5} = \\frac{4}{21}$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Find: $\\frac{9}{16} \\times \\frac{8}{15}$`,
    options: [`\\frac{3}{10}`, `\\frac{10}{3}`, `\\frac{3}{11}`, `\\frac{4}{10}`],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{9 \\times 8}{16 \\times 15} = \\frac{72}{240}$</p><p><strong>Step 2: Simplify the fraction</strong><br>Divide the numerator and denominator by their greatest common divisor ($24$):<br>$\\frac{72 \\div 24}{240 \\div 24} = \\frac{3}{10}$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Find: $\\frac{6}{25} \\times \\frac{5}{18}$`,
    options: [`\\frac{2}{15}`, `\\frac{1}{16}`, `\\frac{1}{15}`, `15`],
    answer: 2,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{6 \\times 5}{25 \\times 18} = \\frac{30}{450}$</p><p><strong>Step 2: Simplify the fraction</strong><br>Divide the numerator and denominator by their greatest common divisor ($30$):<br>$\\frac{30 \\div 30}{450 \\div 30} = \\frac{1}{15}$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Find: $\\frac{13}{14} \\times \\frac{7}{26}$`,
    options: [`4`, `\\frac{1}{4}`, `\\frac{1}{5}`, `\\frac{2}{4}`],
    answer: 1,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{13 \\times 7}{14 \\times 26} = \\frac{91}{364}$</p><p><strong>Step 2: Simplify the fraction</strong><br>Divide the numerator and denominator by their greatest common divisor ($91$):<br>$\\frac{91 \\div 91}{364 \\div 91} = \\frac{1}{4}$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Find: $\\frac{15}{8} \\times \\frac{32}{45}$`,
    options: [`\\frac{3}{4}`, `\\frac{4}{3}`, `\\frac{4}{4}`, `\\frac{5}{3}`],
    answer: 1,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{15 \\times 32}{8 \\times 45} = \\frac{480}{360}$</p><p><strong>Step 2: Simplify the fraction</strong><br>Divide the numerator and denominator by their greatest common divisor ($120$):<br>$\\frac{480 \\div 120}{360 \\div 120} = \\frac{4}{3}$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Find: $\\frac{35}{18} \\times \\frac{27}{49}$`,
    options: [`\\frac{14}{15}`, `\\frac{15}{15}`, `\\frac{15}{14}`, `\\frac{16}{14}`],
    answer: 2,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{35 \\times 27}{18 \\times 49} = \\frac{945}{882}$</p><p><strong>Step 2: Simplify the fraction</strong><br>Divide the numerator and denominator by their greatest common divisor ($63$):<br>$\\frac{945 \\div 63}{882 \\div 63} = \\frac{15}{14}$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Find: $\\frac{24}{45} \\times \\frac{35}{56}$`,
    options: [`\\frac{1}{3}`, `\\frac{2}{3}`, `\\frac{1}{4}`, `3`],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply numerators and denominators</strong><br>Multiply the top numbers together and the bottom numbers together:<br>$\\frac{24 \\times 35}{45 \\times 56} = \\frac{840}{2520}$</p><p><strong>Step 2: Simplify the fraction</strong><br>Divide the numerator and denominator by their greatest common divisor ($840$):<br>$\\frac{840 \\div 840}{2520 \\div 840} = \\frac{1}{3}$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Complete the multiplication, simplifying where possible: $\\frac{1}{2} \\times \\frac{1}{4} \\times \\frac{1}{5}$`,
    options: [`40`, `\\frac{1}{40}`, `\\frac{2}{40}`, `\\frac{1}{41}`],
    answer: 1,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply all numerators and all denominators</strong><br>$\\frac{1 \\times 1 \\times 1}{2 \\times 4 \\times 5} = \\frac{1}{40}$</p><p><strong>Step 2: Check for simplification</strong><br>The fraction $\\frac{1}{40}$ is already in its simplest form.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Complete the multiplication, simplifying where possible: $\\frac{2}{3} \\times \\frac{4}{5} \\times \\frac{5}{8}$`,
    options: [`\\frac{2}{3}`, `\\frac{1}{4}`, `3`, `\\frac{1}{3}`],
    answer: 3,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply all numerators and all denominators</strong><br>$\\frac{2 \\times 4 \\times 5}{3 \\times 5 \\times 8} = \\frac{40}{120}$</p><p><strong>Step 2: Simplify the fraction</strong><br>Divide the numerator and denominator by their greatest common divisor ($40$):<br>$\\frac{40 \\div 40}{120 \\div 40} = \\frac{1}{3}$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Complete the multiplication, simplifying where possible: $\\frac{1}{3} \\times \\frac{2}{5} \\times \\frac{5}{8}$`,
    options: [`12`, `\\frac{2}{12}`, `\\frac{1}{13}`, `\\frac{1}{12}`],
    answer: 3,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply all numerators and all denominators</strong><br>$\\frac{1 \\times 2 \\times 5}{3 \\times 5 \\times 8} = \\frac{10}{120}$</p><p><strong>Step 2: Simplify the fraction</strong><br>Divide the numerator and denominator by their greatest common divisor ($10$):<br>$\\frac{10 \\div 10}{120 \\div 10} = \\frac{1}{12}$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Complete the multiplication, simplifying where possible: $\\frac{2}{5} \\times \\frac{3}{4} \\times \\frac{5}{9}$`,
    options: [`\\frac{1}{6}`, `\\frac{1}{7}`, `6`, `\\frac{2}{6}`],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply all numerators and all denominators</strong><br>$\\frac{2 \\times 3 \\times 5}{5 \\times 4 \\times 9} = \\frac{30}{180}$</p><p><strong>Step 2: Simplify the fraction</strong><br>Divide the numerator and denominator by their greatest common divisor ($30$):<br>$\\frac{30 \\div 30}{180 \\div 30} = \\frac{1}{6}$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Complete the multiplication, simplifying where possible: $\\frac{5}{14} \\times \\frac{7}{10} \\times \\frac{8}{9}$`,
    options: [`\\frac{3}{9}`, `\\frac{2}{9}`, `\\frac{2}{10}`, `\\frac{9}{2}`],
    answer: 1,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply all numerators and all denominators</strong><br>$\\frac{5 \\times 7 \\times 8}{14 \\times 10 \\times 9} = \\frac{280}{1260}$</p><p><strong>Step 2: Simplify the fraction</strong><br>Divide the numerator and denominator by their greatest common divisor ($140$):<br>$\\frac{280 \\div 140}{1260 \\div 140} = \\frac{2}{9}$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Complete the multiplication, simplifying where possible: $\\frac{3}{4} \\times \\frac{6}{7} \\times \\frac{14}{27}$`,
    options: [`3`, `\\frac{2}{3}`, `\\frac{1}{3}`, `\\frac{1}{4}`],
    answer: 2,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply all numerators and all denominators</strong><br>$\\frac{3 \\times 6 \\times 14}{4 \\times 7 \\times 27} = \\frac{252}{756}$</p><p><strong>Step 2: Simplify the fraction</strong><br>Divide the numerator and denominator by their greatest common divisor ($252$):<br>$\\frac{252 \\div 252}{756 \\div 252} = \\frac{1}{3}$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Complete the multiplication, simplifying where possible: $\\frac{4}{9} \\times \\frac{7}{12} \\times \\frac{9}{14}$`,
    options: [`6`, `\\frac{1}{6}`, `\\frac{2}{6}`, `\\frac{1}{7}`],
    answer: 1,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply all numerators and all denominators</strong><br>$\\frac{4 \\times 7 \\times 9}{9 \\times 12 \\times 14} = \\frac{252}{1512}$</p><p><strong>Step 2: Simplify the fraction</strong><br>Divide the numerator and denominator by their greatest common divisor ($252$):<br>$\\frac{252 \\div 252}{1512 \\div 252} = \\frac{1}{6}$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Complete the multiplication, simplifying where possible: $\\frac{18}{5} \\times \\frac{10}{21} \\times \\frac{7}{12}$`,
    options: [`2`, `\\frac{1}{2}`, `1`, `0`],
    answer: 2,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply all numerators and all denominators</strong><br>$\\frac{18 \\times 10 \\times 7}{5 \\times 21 \\times 12} = \\frac{1260}{1260}$</p><p><strong>Step 2: Simplify the fraction</strong><br>Divide the numerator and denominator by their greatest common divisor ($1260$):<br>$\\frac{1260 \\div 1260}{1260 \\div 1260} = 1$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Complete the multiplication, simplifying where possible: $\\frac{7}{12} \\times \\frac{8}{21} \\times \\frac{9}{14}$`,
    options: [`\\frac{2}{7}`, `7`, `\\frac{1}{8}`, `\\frac{1}{7}`],
    answer: 3,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply all numerators and all denominators</strong><br>$\\frac{7 \\times 8 \\times 9}{12 \\times 21 \\times 14} = \\frac{504}{3528}$</p><p><strong>Step 2: Simplify the fraction</strong><br>Divide the numerator and denominator by their greatest common divisor ($504$):<br>$\\frac{504 \\div 504}{3528 \\div 504} = \\frac{1}{7}$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Complete the multiplication, simplifying where possible: $\\frac{4}{15} \\times \\frac{7}{8} \\times \\frac{10}{21}$`,
    options: [`\\frac{1}{10}`, `\\frac{1}{9}`, `\\frac{2}{9}`, `9`],
    answer: 1,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply all numerators and all denominators</strong><br>$\\frac{4 \\times 7 \\times 10}{15 \\times 8 \\times 21} = \\frac{280}{2520}$</p><p><strong>Step 2: Simplify the fraction</strong><br>Divide the numerator and denominator by their greatest common divisor ($280$):<br>$\\frac{280 \\div 280}{2520 \\div 280} = \\frac{1}{9}$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Complete the multiplication, simplifying where possible: $\\frac{15}{16} \\times \\frac{24}{35} \\times \\frac{7}{9}$`,
    options: [`\\frac{1}{3}`, `\\frac{1}{2}`, `\\frac{2}{2}`, `2`],
    answer: 1,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply all numerators and all denominators</strong><br>$\\frac{15 \\times 24 \\times 7}{16 \\times 35 \\times 9} = \\frac{2520}{5040}$</p><p><strong>Step 2: Simplify the fraction</strong><br>Divide the numerator and denominator by their greatest common divisor ($2520$):<br>$\\frac{2520 \\div 2520}{5040 \\div 2520} = \\frac{1}{2}$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-5',
    topicId: 'y7-5a',
    topicCode: '5A',
    topicTitle: 'Multiplication of fractions',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Complete the multiplication, simplifying where possible: $\\frac{9}{14} \\times \\frac{28}{33} \\times \\frac{11}{18}$`,
    options: [`3`, `\\frac{1}{4}`, `\\frac{2}{3}`, `\\frac{1}{3}`],
    answer: 3,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Multiply all numerators and all denominators</strong><br>$\\frac{9 \\times 28 \\times 11}{14 \\times 33 \\times 18} = \\frac{2772}{8316}$</p><p><strong>Step 2: Simplify the fraction</strong><br>Divide the numerator and denominator by their greatest common divisor ($2772$):<br>$\\frac{2772 \\div 2772}{8316 \\div 2772} = \\frac{1}{3}$</p></div>`,
    createdAt: new Date().toISOString()
  }
];

export const importYear7Ch5A = async (forceReset = false) => {
  console.log('[Ch5A Year 7 Import] STARTING PHYSICAL SYNC...');
  let importedCount = 0;
  try {
    const qRef = collection(db, 'questions');
    
    if (forceReset) {
      console.log('Force reset enabled. Deleting existing Y7 Ch5A questions...');
      const existingSnap = await getDocs(query(qRef, where('topicId', '==', 'y7-5a')));
      for (const doc of existingSnap.docs) {
        await deleteDoc(doc.ref);
      }
      console.log(`Deleted ${existingSnap.size} existing questions.`);
    }

    const existingSnap = await getDocs(query(qRef, where('topicId', '==', 'y7-5a')));
    const existingQuestions = new Set(existingSnap.docs.map(doc => doc.data().question.trim()));
    
    for (const q of allQuestions) {
      if (!existingQuestions.has(q.question.trim())) {
        await addDoc(collection(db, 'questions'), q);
        importedCount++;
      }
    }
    console.log(`[Ch5A Year 7 Import] SUCCESS! ${importedCount} new questions imported.`);
  } catch (error) {
    console.error('[Ch5A Year 7 Import] ERROR:', error);
  }
};
