import { db } from '../firebase/config.js';
import { collection, addDoc, getDocs, query, where, deleteDoc } from 'firebase/firestore';

export const allQuestions = [
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Which of the following lists all the factors of $8$?`,
    options: ["\\{1, 2, 4, 8\\}","\\{1, 2, 4\\}","\\{2, 4, 8\\}","\\{1, 2, 3, 4, 8\\}"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand factors</strong><br>A factor is a whole number that divides exactly into another number without leaving a remainder.</p><p><strong>Step 2: Find factor pairs</strong><br>For $8$, the pairs of factors are what multiply to give $8$. Listing them out gives $\\{1, 2, 4, 8\\}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Which of the following lists all the factors of $18$?`,
    options: ["\\{1, 2, 3, 6, 9, 18\\}","\\{1, 2, 3, 9, 18\\}","\\{2, 3, 6, 9\\}","\\{1, 2, 4, 6, 9, 18\\}"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand factors</strong><br>A factor is a whole number that divides exactly into another number without leaving a remainder.</p><p><strong>Step 2: Find factor pairs</strong><br>For $18$, the pairs of factors are what multiply to give $18$. Listing them out gives $\\{1, 2, 3, 6, 9, 18\\}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Which of the following lists all the factors of $21$?`,
    options: ["\\{1, 3, 7, 21\\}","\\{1, 3, 21\\}","\\{3, 7, 21\\}","\\{1, 2, 3, 7, 21\\}"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand factors</strong><br>A factor is a whole number that divides exactly into another number without leaving a remainder.</p><p><strong>Step 2: Find factor pairs</strong><br>For $21$, the pairs of factors are what multiply to give $21$. Listing them out gives $\\{1, 3, 7, 21\\}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Which of the following lists all the factors of $20$?`,
    options: ["\\{1, 2, 4, 5, 10, 20\\}","\\{1, 2, 4, 10, 20\\}","\\{1, 2, 5, 10, 20\\}","\\{1, 2, 4, 5, 8, 10, 20\\}"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand factors</strong><br>A factor is a whole number that divides exactly into another number without leaving a remainder.</p><p><strong>Step 2: Find factor pairs</strong><br>For $20$, the pairs of factors are what multiply to give $20$. Listing them out gives $\\{1, 2, 4, 5, 10, 20\\}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Which of the following lists all the factors of $13$?`,
    options: ["\\{1, 13\\}","\\{13\\}","\\{1, 3, 13\\}","\\{0, 1, 13\\}"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand factors</strong><br>A factor is a whole number that divides exactly into another number without leaving a remainder.</p><p><strong>Step 2: Find factor pairs</strong><br>For $13$, the pairs of factors are what multiply to give $13$. Listing them out gives $\\{1, 13\\}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Which list correctly identifies all the factors of $10$?`,
    options: ["\\{1, 2, 5, 10\\}","\\{1, 5, 10\\}","\\{2, 5\\}","\\{1, 2, 10\\}"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Use factor pairing</strong><br>Write pairs of numbers that multiply to $10$.</p><p><strong>Step 2: Compile the list</strong><br>Combining all unique numbers from those pairs in ascending order gives $\\{1, 2, 5, 10\\}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Which list correctly identifies all the factors of $16$?`,
    options: ["\\{1, 2, 4, 8, 16\\}","\\{1, 2, 8, 16\\}","\\{1, 2, 4, 6, 8, 16\\}","\\{2, 4, 8\\}"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Use factor pairing</strong><br>Write pairs of numbers that multiply to $16$.</p><p><strong>Step 2: Compile the list</strong><br>Combining all unique numbers from those pairs in ascending order gives $\\{1, 2, 4, 8, 16\\}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Which list correctly identifies all the factors of $17$?`,
    options: ["\\{1, 17\\}","\\{17\\}","\\{1, 7, 17\\}","\\{1, 3, 17\\}"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Use factor pairing</strong><br>Write pairs of numbers that multiply to $17$.</p><p><strong>Step 2: Compile the list</strong><br>Combining all unique numbers from those pairs in ascending order gives $\\{1, 17\\}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Which list correctly identifies all the factors of $24$?`,
    options: ["\\{1, 2, 3, 4, 6, 8, 12, 24\\}","\\{1, 2, 3, 4, 6, 12, 24\\}","\\{1, 2, 4, 6, 8, 12, 24\\}","\\{1, 2, 3, 6, 8, 12, 24\\}"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Use factor pairing</strong><br>Write pairs of numbers that multiply to $24$.</p><p><strong>Step 2: Compile the list</strong><br>Combining all unique numbers from those pairs in ascending order gives $\\{1, 2, 3, 4, 6, 8, 12, 24\\}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Which list correctly identifies all the factors of $36$?`,
    options: ["\\{1, 2, 3, 4, 6, 9, 12, 18, 36\\}","\\{1, 2, 3, 4, 6, 12, 18, 36\\}","\\{1, 2, 3, 4, 9, 12, 18, 36\\}","\\{1, 2, 3, 4, 6, 8, 9, 12, 18, 36\\}"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Use factor pairing</strong><br>Write pairs of numbers that multiply to $36$.</p><p><strong>Step 2: Compile the list</strong><br>Combining all unique numbers from those pairs in ascending order gives $\\{1, 2, 3, 4, 6, 9, 12, 18, 36\\}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Which list correctly identifies all the factors of $15$?`,
    options: ["\\{1, 3, 5, 15\\}","\\{1, 5, 15\\}","\\{3, 5\\}","\\{1, 3, 15\\}"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Use factor pairing</strong><br>Write pairs of numbers that multiply to $15$.</p><p><strong>Step 2: Compile the list</strong><br>Combining all unique numbers from those pairs in ascending order gives $\\{1, 3, 5, 15\\}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Which list correctly identifies all the factors of $28$?`,
    options: ["\\{1, 2, 4, 7, 14, 28\\}","\\{1, 2, 4, 14, 28\\}","\\{1, 2, 7, 14, 28\\}","\\{1, 2, 4, 7, 8, 14, 28\\}"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Use factor pairing</strong><br>Write pairs of numbers that multiply to $28$.</p><p><strong>Step 2: Compile the list</strong><br>Combining all unique numbers from those pairs in ascending order gives $\\{1, 2, 4, 7, 14, 28\\}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Which list correctly identifies all the factors of $19$?`,
    options: ["\\{1, 19\\}","\\{19\\}","\\{1, 3, 19\\}","\\{1, 9, 19\\}"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Use factor pairing</strong><br>Write pairs of numbers that multiply to $19$.</p><p><strong>Step 2: Compile the list</strong><br>Combining all unique numbers from those pairs in ascending order gives $\\{1, 19\\}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Which list correctly identifies all the factors of $27$?`,
    options: ["\\{1, 3, 9, 27\\}","\\{1, 3, 27\\}","\\{1, 9, 27\\}","\\{1, 3, 7, 9, 27\\}"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Use factor pairing</strong><br>Write pairs of numbers that multiply to $27$.</p><p><strong>Step 2: Compile the list</strong><br>Combining all unique numbers from those pairs in ascending order gives $\\{1, 3, 9, 27\\}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Which list correctly identifies all the factors of $64$?`,
    options: ["\\{1, 2, 4, 8, 16, 32, 64\\}","\\{1, 2, 4, 8, 32, 64\\}","\\{1, 2, 8, 16, 32, 64\\}","\\{1, 2, 4, 8, 12, 16, 32, 64\\}"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Use factor pairing</strong><br>Write pairs of numbers that multiply to $64$.</p><p><strong>Step 2: Compile the list</strong><br>Combining all unique numbers from those pairs in ascending order gives $\\{1, 2, 4, 8, 16, 32, 64\\}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Which list correctly identifies all the factors of $40$?`,
    options: ["\\{1, 2, 4, 5, 8, 10, 20, 40\\}","\\{1, 2, 4, 5, 10, 20, 40\\}","\\{1, 2, 4, 8, 10, 20, 40\\}","\\{1, 2, 4, 5, 8, 12, 20, 40\\}"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Use factor pairing</strong><br>Write pairs of numbers that multiply to $40$.</p><p><strong>Step 2: Compile the list</strong><br>Combining all unique numbers from those pairs in ascending order gives $\\{1, 2, 4, 5, 8, 10, 20, 40\\}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Which list correctly identifies all the factors of $50$?`,
    options: ["\\{1, 2, 5, 10, 25, 50\\}","\\{1, 2, 5, 25, 50\\}","\\{1, 2, 10, 25, 50\\}","\\{1, 2, 4, 5, 10, 25, 50\\}"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Use factor pairing</strong><br>Write pairs of numbers that multiply to $50$.</p><p><strong>Step 2: Compile the list</strong><br>Combining all unique numbers from those pairs in ascending order gives $\\{1, 2, 5, 10, 25, 50\\}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `From the list $\\{8, 12, 14, 25, 30, 41, 48, 55, 60\\}$, which numbers have $4$ as a factor?`,
    options: ["$\\{8, 12, 48, 60\\}$","$\\{8, 12, 30, 48, 60\\}$","$\\{8, 12, 14, 48\\}$","$\\{12, 48, 60\\}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Check divisibility by 4</strong><br>A number has $4$ as a factor if it can be divided evenly by $4$.</p><p><strong>Step 2: Test each number</strong><br>$8 \\div 4 = 2$<br>$12 \\div 4 = 3$<br>$48 \\div 4 = 12$<br>$60 \\div 4 = 15$<br>The others ($14, 25, 30, 41, 55$) leave a remainder.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `From the list $\\{45, 135, 160, 210, 225, 250, 300\\}$, which numbers have $15$ as a factor?`,
    options: ["$\\{45, 135, 210, 225, 300\\}$","$\\{45, 135, 160, 225, 300\\}$","$\\{45, 210, 225, 300\\}$","$\\{135, 210, 225, 250, 300\\}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Divide by 15</strong><br>Test each number. Also note that numbers divisible by $15$ must be divisible by both $3$ and $5$.</p><p><strong>Step 2: Filter the list</strong><br>$45, 135, 210, 225, 300$ are all multiples of $15$. $160$ and $250$ are not divisible by $3$, so they are not multiples of $15$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Which of the following represents the first $5$ non-zero multiples of $7$?`,
    options: ["$7, 14, 21, 28, 35$","$14, 21, 28, 35, 42$","$7, 14, 21, 28, 36$","$1, 7, 14, 21, 28$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand multiples</strong><br>Multiples of a number are found by multiplying it by integers ($1, 2, 3, \\dots$).</p><p><strong>Step 2: Calculate the first 5</strong><br>$7 \\times 1 = 7$<br>$7 \\times 2 = 14$<br>$7 \\times 3 = 21$<br>$7 \\times 4 = 28$<br>$7 \\times 5 = 35$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Which of the following represents the first $5$ non-zero multiples of $9$?`,
    options: ["$9, 18, 27, 36, 45$","$18, 27, 36, 45, 54$","$9, 18, 28, 36, 45$","$1, 9, 18, 27, 36$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand multiples</strong><br>Multiples of a number are found by multiplying it by integers ($1, 2, 3, \\dots$).</p><p><strong>Step 2: Calculate the first 5</strong><br>$9 \\times 1 = 9$<br>$9 \\times 2 = 18$<br>$9 \\times 3 = 27$<br>$9 \\times 4 = 36$<br>$9 \\times 5 = 45$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Which of the following represents the first $5$ non-zero multiples of $12$?`,
    options: ["$12, 24, 36, 48, 60$","$24, 36, 48, 60, 72$","$12, 24, 38, 48, 60$","$1, 12, 24, 36, 48$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand multiples</strong><br>Multiples of a number are found by multiplying it by integers ($1, 2, 3, \\dots$).</p><p><strong>Step 2: Calculate the first 5</strong><br>$12 \\times 1 = 12$<br>$12 \\times 2 = 24$<br>$12 \\times 3 = 36$<br>$12 \\times 4 = 48$<br>$12 \\times 5 = 60$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Which of the following represents the first $5$ non-zero multiples of $14$?`,
    options: ["$14, 28, 42, 56, 70$","$28, 42, 56, 70, 84$","$14, 28, 44, 56, 70$","$14, 24, 34, 44, 54$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand multiples</strong><br>Multiples of a number are found by multiplying it by integers ($1, 2, 3, \\dots$).</p><p><strong>Step 2: Calculate the first 5</strong><br>$14 \\times 1 = 14$<br>$14 \\times 2 = 28$<br>$14 \\times 3 = 42$<br>$14 \\times 4 = 56$<br>$14 \\times 5 = 70$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Which of the following represents the first $5$ non-zero multiples of $16$?`,
    options: ["$16, 32, 48, 64, 80$","$32, 48, 64, 80, 96$","$16, 32, 46, 64, 80$","$1, 16, 32, 48, 64$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand multiples</strong><br>Multiples of a number are found by multiplying it by integers ($1, 2, 3, \\dots$).</p><p><strong>Step 2: Calculate the first 5</strong><br>$16 \\times 1 = 16$<br>$16 \\times 2 = 32$<br>$16 \\times 3 = 48$<br>$16 \\times 4 = 64$<br>$16 \\times 5 = 80$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Which of the following represents the first $5$ non-zero multiples of $21$?`,
    options: ["$21, 42, 63, 84, 105$","$42, 63, 84, 105, 126$","$21, 42, 61, 84, 105$","$21, 41, 61, 81, 101$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand multiples</strong><br>Multiples of a number are found by multiplying it by integers ($1, 2, 3, \\dots$).</p><p><strong>Step 2: Calculate the first 5</strong><br>$21 \\times 1 = 21$<br>$21 \\times 2 = 42$<br>$21 \\times 3 = 63$<br>$21 \\times 4 = 84$<br>$21 \\times 5 = 105$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Which of the following numbers are multiples of $13$? ($\\dots 39, 52, 70, 91, 115, 130 \\dots$)`,
    options: ["$\\{39, 52, 91, 130\\}$","$\\{39, 52, 70, 91\\}$","$\\{52, 91, 115, 130\\}$","$\\{39, 70, 91, 130\\}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Check divisibility by 13</strong><br>$39 \\div 13 = 3$<br>$52 \\div 13 = 4$<br>$91 \\div 13 = 7$<br>$130 \\div 13 = 10$<br>$70$ and $115$ do not divide evenly by $13$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Which of these numbers have $60$ as a multiple? ($\\dots 4, 5, 7, 8, 10, 12, 14, 15, 18, 20, 24, 30 \\dots$)`,
    options: ["$\\{4, 5, 10, 12, 15, 20, 30\\}$","$\\{4, 5, 8, 10, 12, 15, 20, 30\\}$","$\\{4, 5, 10, 12, 14, 15, 20, 30\\}$","$\\{5, 10, 15, 20, 24, 30\\}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Reword the question</strong><br>Asking which numbers have $60$ as a multiple is the same as asking which numbers are <em>factors</em> of $60$.</p><p><strong>Step 2: Identify factors of 60</strong><br>From the given list, $4, 5, 10, 12, 15, 20$, and $30$ divide evenly into $60$. Numbers like $7, 8, 14, 18, 24$ do not.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Which of the following is a correct expression of $288$ as a product of two factors, both of which are strictly greater than $10$?`,
    options: ["$12 \\times 24$","$8 \\times 36$","$9 \\times 32$","$6 \\times 48$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Check the conditions</strong><br>The product must equal $288$ and BOTH factors must be $> 10$.</p><p><strong>Step 2: Evaluate options</strong><br>In $12 \\times 24$, both numbers are greater than $10$. In the incorrect options, at least one factor is $10$ or smaller (or the math is incorrect).</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Which of the following is a correct expression of $450$ as a product of two factors, both of which are strictly greater than $10$?`,
    options: ["$15 \\times 30$","$9 \\times 50$","$10 \\times 45$","$5 \\times 90$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Check the conditions</strong><br>The product must equal $450$ and BOTH factors must be $> 10$.</p><p><strong>Step 2: Evaluate options</strong><br>In $15 \\times 30$, both numbers are greater than $10$. In the incorrect options, at least one factor is $10$ or smaller (or the math is incorrect).</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Which of the following is a correct expression of $169$ as a product of two factors, both of which are strictly greater than $10$?`,
    options: ["$13 \\times 13$","$1 \\times 169$","$169 \\times 1$","$16 \\times 9$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Check the conditions</strong><br>The product must equal $169$ and BOTH factors must be $> 10$.</p><p><strong>Step 2: Evaluate options</strong><br>In $13 \\times 13$, both numbers are greater than $10$. In the incorrect options, at least one factor is $10$ or smaller (or the math is incorrect).</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Which of the following is a correct expression of $600$ as a product of two factors, both of which are strictly greater than $10$?`,
    options: ["$15 \\times 40$","$10 \\times 60$","$8 \\times 75$","$6 \\times 100$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Check the conditions</strong><br>The product must equal $600$ and BOTH factors must be $> 10$.</p><p><strong>Step 2: Evaluate options</strong><br>In $15 \\times 40$, both numbers are greater than $10$. In the incorrect options, at least one factor is $10$ or smaller (or the math is incorrect).</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Which of the following is a correct expression of $289$ as a product of two factors, both of which are strictly greater than $10$?`,
    options: ["$17 \\times 17$","$1 \\times 289$","$19 \\times 19$","$13 \\times 23$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Check the conditions</strong><br>The product must equal $289$ and BOTH factors must be $> 10$.</p><p><strong>Step 2: Evaluate options</strong><br>In $17 \\times 17$, both numbers are greater than $10$. In the incorrect options, at least one factor is $10$ or smaller (or the math is incorrect).</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Which of the following is a correct expression of $360$ as a product of two factors, both of which are strictly greater than $10$?`,
    options: ["$12 \\times 30$","$9 \\times 40$","$10 \\times 36$","$8 \\times 45$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Check the conditions</strong><br>The product must equal $360$ and BOTH factors must be $> 10$.</p><p><strong>Step 2: Evaluate options</strong><br>In $12 \\times 30$, both numbers are greater than $10$. In the incorrect options, at least one factor is $10$ or smaller (or the math is incorrect).</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `What are the common factors of $16$ and $24$?`,
    options: ["$\\{1, 2, 4, 8\\}$","$\\{1, 2, 4, 6, 8\\}$","$\\{1, 2, 4, 8, 16\\}$","$\\{1, 2, 3, 4, 8\\}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: List factors of 16</strong><br>$\\{1, 2, 4, 8, 16\\}$</p><p><strong>Step 2: List factors of 24</strong><br>$\\{1, 2, 3, 4, 6, 8, 12, 24\\}$</p><p><strong>Step 3: Find common numbers</strong><br>The numbers present in both lists are $\\{1, 2, 4, 8\\}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Which of the following lists the common multiples of $4$ and $6$ that are strictly less than $40$?`,
    options: ["$\\{12, 24, 36\\}$","$\\{12, 24, 30, 36\\}$","$\\{24, 36\\}$","$\\{12, 18, 24, 36\\}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Find the Lowest Common Multiple (LCM)</strong><br>The multiples of $4$ are $4, 8, 12, 16 \\dots$<br>The multiples of $6$ are $6, 12, 18 \\dots$<br>The LCM is $12$.</p><p><strong>Step 2: List multiples of the LCM</strong><br>The common multiples will be all multiples of $12$: $12, 24, 36, 48 \\dots$<br>Those less than $40$ are $\\{12, 24, 36\\}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Find the multiple of $8$ that is closest to $50$.`,
    options: ["$48$","$56$","$42$","$50$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Divide by 8 to find bounds</strong><br>$50 \\div 8$ gives a number between two integers.</p><p><strong>Step 2: Test the multiples</strong><br>The nearest multiples of $8$ are $48$ and $56$.<br>Distance to $48$ is $|50 - 48|$.<br>Distance to $56$ is $|50 - 56|$.<br>$48$ is closer.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Find the multiple of $8$ that is closest to $110$.`,
    options: ["$112$","$104$","$120$","$108$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Divide by 8 to find bounds</strong><br>$110 \\div 8$ gives a number between two integers.</p><p><strong>Step 2: Test the multiples</strong><br>The nearest multiples of $8$ are $112$ and $104$.<br>Distance to $112$ is $|110 - 112|$.<br>Distance to $104$ is $|110 - 104|$.<br>$112$ is closer.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Find the multiple of $8$ that is closest to $210$.`,
    options: ["$208$","$216$","$200$","$210$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Divide by 8 to find bounds</strong><br>$210 \\div 8$ gives a number between two integers.</p><p><strong>Step 2: Test the multiples</strong><br>The nearest multiples of $8$ are $208$ and $216$.<br>Distance to $208$ is $|210 - 208|$.<br>Distance to $216$ is $|210 - 216|$.<br>$208$ is closer.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Find the multiple of $8$ that is closest to $315$.`,
    options: ["$312$","$320$","$304$","$318$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Divide by 8 to find bounds</strong><br>$315 \\div 8$ gives a number between two integers.</p><p><strong>Step 2: Test the multiples</strong><br>The nearest multiples of $8$ are $312$ and $320$.<br>Distance to $312$ is $|315 - 312|$.<br>Distance to $320$ is $|315 - 320|$.<br>$312$ is closer.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Find the number that is divisible by $12$ and closest to $80$.`,
    options: ["$84$","$72$","$96$","$80$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Find surrounding multiples of 12</strong><br>Divide $80$ by $12$ to locate the nearest multiples.</p><p><strong>Step 2: Calculate distances</strong><br>The closest multiples are $84$ and $72$. The absolute difference between $84$ and $80$ is the smallest.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Find the number that is divisible by $12$ and closest to $160$.`,
    options: ["$156$","$168$","$144$","$162$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Find surrounding multiples of 12</strong><br>Divide $160$ by $12$ to locate the nearest multiples.</p><p><strong>Step 2: Calculate distances</strong><br>The closest multiples are $156$ and $168$. The absolute difference between $156$ and $160$ is the smallest.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Find the number that is divisible by $12$ and closest to $130$.`,
    options: ["$132$","$120$","$144$","$128$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Find surrounding multiples of 12</strong><br>Divide $130$ by $12$ to locate the nearest multiples.</p><p><strong>Step 2: Calculate distances</strong><br>The closest multiples are $132$ and $120$. The absolute difference between $132$ and $130$ is the smallest.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Find the number that is divisible by $12$ and closest to $70$.`,
    options: ["$72$","$60$","$84$","$68$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Find surrounding multiples of 12</strong><br>Divide $70$ by $12$ to locate the nearest multiples.</p><p><strong>Step 2: Calculate distances</strong><br>The closest multiples are $72$ and $60$. The absolute difference between $72$ and $70$ is the smallest.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Find the number that is divisible by $12$ and closest to $400$.`,
    options: ["$396$","$408$","$384$","$402$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Find surrounding multiples of 12</strong><br>Divide $400$ by $12$ to locate the nearest multiples.</p><p><strong>Step 2: Calculate distances</strong><br>The closest multiples are $396$ and $408$. The absolute difference between $396$ and $400$ is the smallest.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Find the number that is divisible by $12$ and closest to $800$.`,
    options: ["$804$","$792$","$816$","$800$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Find surrounding multiples of 12</strong><br>Divide $800$ by $12$ to locate the nearest multiples.</p><p><strong>Step 2: Calculate distances</strong><br>The closest multiples are $804$ and $792$. The absolute difference between $804$ and $800$ is the smallest.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `When $40$ is divided by each of the whole numbers from $1$ to $5$, which of these divisors leaves a remainder of $0$?`,
    options: ["$\\{1, 2, 4, 5\\}$","$\\{1, 2, 3, 4, 5\\}$","$\\{1, 2, 5\\}$","$\\{2, 4, 5\\}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Check each division</strong><br>$40 \\div 1 = 40$ (R0)<br>$40 \\div 2 = 20$ (R0)<br>$40 \\div 3 = 13$ (R1)<br>$40 \\div 4 = 10$ (R0)<br>$40 \\div 5 = 8$ (R0)</p><p><strong>Step 2: Conclusion</strong><br>The divisors leaving remainder $0$ are $1, 2, 4, 5$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Write down all the factors of $40$.`,
    options: ["$\\{1, 2, 4, 5, 8, 10, 20, 40\\}$","$\\{1, 2, 4, 5, 10, 20, 40\\}$","$\\{1, 2, 4, 8, 10, 20, 40\\}$","$\\{1, 2, 5, 8, 10, 20, 40\\}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Pair the factors</strong><br>$1 \\times 40 = 40$<br>$2 \\times 20 = 40$<br>$4 \\times 10 = 40$<br>$5 \\times 8 = 40$</p><p><strong>Step 2: Combine in order</strong><br>$\\{1, 2, 4, 5, 8, 10, 20, 40\\}$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `When $45$ is divided by each of the whole numbers from $1$ to $6$, which of these divisors leaves a remainder of $0$?`,
    options: ["$\\{1, 3, 5\\}$","$\\{1, 3, 5, 6\\}$","$\\{1, 5\\}$","$\\{3, 5\\}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Check division</strong><br>$45$ is divisible by $1$. It is not divisible by $2$ (odd number). $4+5=9$, so it is divisible by $3$. It ends in $5$, so it is divisible by $5$. It is not divisible by $4$ or $6$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Write down all the factors of $45$.`,
    options: ["$\\{1, 3, 5, 9, 15, 45\\}$","$\\{1, 3, 5, 15, 45\\}$","$\\{1, 3, 9, 15, 45\\}$","$\\{1, 5, 9, 15, 45\\}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Pair the factors</strong><br>$1 \\times 45 = 45$<br>$3 \\times 15 = 45$<br>$5 \\times 9 = 45$</p><p><strong>Step 2: Combine in order</strong><br>$\\{1, 3, 5, 9, 15, 45\\}$</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Which of the following best explains why the number $1$ is a factor of every whole number $N$?`,
    options: ["Because dividing any whole number $N$ by $1$ results in $N$ with a remainder of zero ($N = 1 \\times N$).","Because $1$ is the smallest whole number, so it fits inside all other numbers.","Because $1$ is an odd number, and odd numbers divide everything.","Because any number multiplied by $1$ becomes $1$."],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Definition of a factor</strong><br>A factor divides exactly into another number with no remainder.</p><p><strong>Step 2: Apply to 1</strong><br>$N \\div 1 = N$ exactly, meaning $1$ is always a factor of $N$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Which of the following best explains why any non-zero whole number $N$ is a factor of $0$?`,
    options: ["Because $0$ can be written as $N \\times 0$, leaving no remainder when divided by $N$.","Because dividing by $0$ is always zero.","Because $0$ is the smallest whole number.","Because all non-zero numbers are multiples of $0$."],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Definition of a factor</strong><br>If $A$ is a factor of $B$, then $A \\times k = B$ for some whole number $k$.</p><p><strong>Step 2: Apply to zero</strong><br>$N \\times 0 = 0$. This means $N$ divides exactly into $0$ with a quotient of $0$ and no remainder.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `What are all the factors of $1$?`,
    options: ["$\\{1\\}$","$\\{0, 1\\}$","None","$\\{1, 2\\}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Find numbers that multiply to 1</strong><br>The only whole numbers that multiply to $1$ are $1 \\times 1$.</p><p><strong>Step 2: Compile the list</strong><br>The only factor is $1$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Which of the following best explains why zero is a multiple of every whole number $N$?`,
    options: ["Because any whole number $N$ multiplied by $0$ yields $0$.","Because zero is an even number.","Because you cannot divide by zero.","Because zero is less than $N$."],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Definition of a multiple</strong><br>A multiple of $N$ is formed by multiplying $N$ by any whole number.</p><p><strong>Step 2: Apply to zero</strong><br>Since $N \\times 0 = 0$, $0$ fits the definition of being a multiple of $N$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `A "perfect number" is a number that equals the sum of its own factors (excluding itself). The first perfect number is $6$ (since $1+2+3=6$). The second perfect number is $28$. Which of the following correctly shows that $28$ is a perfect number?`,
    options: ["The factors of $28$ (excluding $28$) are $1, 2, 4, 7,$ and $14$, and their sum is $28$.","The factors of $28$ (excluding $28$) are $1, 2, 4, 14,$ and $28$, and their sum is $49$.","The multiples of $28$ are $1, 2, 4, 7,$ and $14$.","The prime factors of $28$ are $2$ and $7$, and $2 \\times 14 = 28$."],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: List the factors of 28</strong><br>$\\{1, 2, 4, 7, 14, 28\\}$.</p><p><strong>Step 2: Exclude the number itself</strong><br>The "proper factors" are $1, 2, 4, 7, 14$.</p><p><strong>Step 3: Sum them up</strong><br>$1 + 2 + 4 + 7 + 14 = 28$. Because the sum equals the number, $28$ is a perfect number.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `The next perfect number after $28$ is $496$. Which of the following represents the sum of the proper factors (factors excluding the number itself) of $496$?`,
    options: ["$1 + 2 + 4 + 8 + 16 + 31 + 62 + 124 + 248 = 496$","$1 + 2 + 4 + 8 + 16 + 32 + 64 + 128 + 256 = 496$","$1 + 3 + 9 + 27 + 81 + 124 + 251 = 496$","$2 + 4 + 8 + 16 + 31 + 62 + 124 + 248 = 495$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Find factors of 496</strong><br>Dividing by $2$: $248$. Dividing by $2$: $124$. By $2$: $62$. By $2$: $31$ (prime).</p><p><strong>Step 2: List all proper factors</strong><br>$1, 2, 4, 8, 16, 31, 62, 124, 248$.</p><p><strong>Step 3: Verify the sum</strong><br>$1 + 2 + 4 + 8 + 16 + 31 + 62 + 124 + 248 = 496$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Why does the number $36$ have an odd number of factors?`,
    options: ["Because it is a perfect square, so one of its factor pairs consists of a number multiplied by itself ($6 \\times 6$), which is counted only once.","Because it is an even number, and all even numbers have an odd number of factors.","Because its digits ($3+6$) add up to $9$, which is an odd number.","Because it has only prime factors."],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: List the factors of 36</strong><br>$\\{1, 2, 3, 4, 6, 9, 12, 18, 36\\}$. There are $9$ factors (an odd amount).</p><p><strong>Step 2: Analyze the pairs</strong><br>$1 \\times 36$<br>$2 \\times 18$<br>$3 \\times 12$<br>$4 \\times 9$<br>$6 \\times 6$<br>Because $6$ is paired with itself, it does not contribute two distinct factors, leaving the total count odd.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `What is the next whole number after $36$ to have an odd number of factors?`,
    options: ["$49$","$40$","$38$","$64$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand the rule</strong><br>Only perfect squares have an odd number of factors.</p><p><strong>Step 2: Find the next perfect square</strong><br>$36$ is $6 \\times 6$. The next whole number squared is $7 \\times 7 = 49$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-2',
    topicId: 'y7-2a',
    topicCode: '2A',
    topicTitle: 'Factors and multiples',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `What is the largest two-digit number with an odd number of factors?`,
    options: ["$81$","$99$","$96$","$100$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Apply the rule</strong><br>Numbers with an odd number of factors are perfect squares.</p><p><strong>Step 2: Find the largest two-digit perfect square</strong><br>$9^2 = 81$.<br>$10^2 = 100$ (which has $3$ digits).<br>Therefore, $81$ is the largest.</p></div>`,
    createdAt: new Date().toISOString()
  },
];

export const importYear7Ch2A = async (forceReset = false) => {
  console.log('[Ch2A Year 7 Import] STARTING PHYSICAL SYNC...');
  let importedCount = 0;
  try {
    const qRef = collection(db, 'questions');
    if (forceReset) {
      const oldSnap = await getDocs(query(qRef, where('topicId', '==', 'y7-2a')));
      for (const d of oldSnap.docs) { await deleteDoc(d.ref); }
    }
    const existingSnap = await getDocs(query(qRef, where('topicId', '==', 'y7-2a')));
    const existingQuestions = new Set(existingSnap.docs.map(doc => doc.data().question.trim()));
    
    for (const q of allQuestions) {
      if (!existingQuestions.has(q.question.trim())) {
        await addDoc(collection(db, 'questions'), q);
        importedCount++;
      }
    }
  } catch (error) { 
    console.error(error); 
    throw error; 
  }
  return importedCount;
};
