import { db } from '../firebase/config.js';
import { collection, addDoc, getDocs, query, where, deleteDoc } from 'firebase/firestore';

export const allQuestions = [
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Sarah has a box that contains $y$ markers. She finds $5$ more markers. Which expression shows the total number of markers Sarah has?`,
    options: ["$y + 5$","$5y$","$y - 5$","$\\frac{y}{5}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Identify the operation</strong><br>Finding "more" implies addition.</p><p><strong>Step 2: Write the expression</strong><br>Starting with $y$ markers and adding $5$ gives the expression $y + 5$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Write an algebraic expression for the following: Adding $8$ to the number $m$`,
    options: ["$m + 8$","$8m$","$m - 8$","$\\frac{m}{8}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Translate the words to symbols</strong><br>Phrases like "sum", "adding", or "more than" mean addition ($+$). Phrases like "subtracting from", "difference", or "less than" mean subtraction ($-$).</p><p><strong>Step 2: Form the expression</strong><br>The correct mathematical translation is $m + 8$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Write an algebraic expression for the following: The sum of $k$ and $7$`,
    options: ["$k + 7$","$7k$","$k - 7$","$7 - k$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Translate the words to symbols</strong><br>Phrases like "sum", "adding", or "more than" mean addition ($+$). Phrases like "subtracting from", "difference", or "less than" mean subtraction ($-$).</p><p><strong>Step 2: Form the expression</strong><br>The correct mathematical translation is $k + 7$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Write an algebraic expression for the following: Subtracting $5$ from $w$`,
    options: ["$w - 5$","$5 - w$","$5w$","$w + 5$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Translate the words to symbols</strong><br>Phrases like "sum", "adding", or "more than" mean addition ($+$). Phrases like "subtracting from", "difference", or "less than" mean subtraction ($-$).</p><p><strong>Step 2: Form the expression</strong><br>The correct mathematical translation is $w - 5$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Write an algebraic expression for the following: Subtracting $9$ from $z$`,
    options: ["$z - 9$","$9 - z$","$9z$","$z + 9$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Translate the words to symbols</strong><br>Phrases like "sum", "adding", or "more than" mean addition ($+$). Phrases like "subtracting from", "difference", or "less than" mean subtraction ($-$).</p><p><strong>Step 2: Form the expression</strong><br>The correct mathematical translation is $z - 9$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Write an algebraic expression for the following: The difference of $p$ and $6$ (where $p > 6$)`,
    options: ["$p - 6$","$6 - p$","$6p$","$p + 6$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Translate the words to symbols</strong><br>Phrases like "sum", "adding", or "more than" mean addition ($+$). Phrases like "subtracting from", "difference", or "less than" mean subtraction ($-$).</p><p><strong>Step 2: Form the expression</strong><br>The correct mathematical translation is $p - 6$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Write an algebraic expression for the following: $12$ less than $h$`,
    options: ["$h - 12$","$12 - h$","$12h$","$h + 12$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Translate the words to symbols</strong><br>Phrases like "sum", "adding", or "more than" mean addition ($+$). Phrases like "subtracting from", "difference", or "less than" mean subtraction ($-$).</p><p><strong>Step 2: Form the expression</strong><br>The correct mathematical translation is $h - 12$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Write an algebraic expression for the following: The sum of $u$ and $v$`,
    options: ["$u + v$","$uv$","$u - v$","$\\frac{u}{v}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Translate the words to symbols</strong><br>Phrases like "sum", "adding", or "more than" mean addition ($+$). Phrases like "subtracting from", "difference", or "less than" mean subtraction ($-$).</p><p><strong>Step 2: Form the expression</strong><br>The correct mathematical translation is $u + v$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Write an algebraic expression for the following: The sum of $a$, $4$, and $b$`,
    options: ["$a + b + 4$","$4ab$","$a - b + 4$","$a + 4b$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Translate the words to symbols</strong><br>Phrases like "sum", "adding", or "more than" mean addition ($+$). Phrases like "subtracting from", "difference", or "less than" mean subtraction ($-$).</p><p><strong>Step 2: Form the expression</strong><br>The correct mathematical translation is $a + b + 4$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Write an algebraic expression for the following: The sum of $x$, $y$ and $z$`,
    options: ["$x + y + z$","$xyz$","$xy + z$","$x + yz$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Translate the words to symbols</strong><br>Phrases like "sum", "adding", or "more than" mean addition ($+$). Phrases like "subtracting from", "difference", or "less than" mean subtraction ($-$).</p><p><strong>Step 2: Form the expression</strong><br>The correct mathematical translation is $x + y + z$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Write an algebraic expression for the following: The product of $8$ and $y$`,
    options: ["$8y$","$8 + y$","$y - 8$","$\\frac{y}{8}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Translate the operation</strong><br>"Product" and "multiplied by" indicate multiplication, which in algebra is written by placing the number and variable side by side (e.g., $2x$). "Quotient" indicates division, written as a fraction.</p><p><strong>Step 2: Write the expression</strong><br>The correct expression is $8y$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Write an algebraic expression for the following: The product of $m$ and $n$`,
    options: ["$mn$","$m + n$","$m - n$","$\\frac{m}{n}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Translate the operation</strong><br>"Product" and "multiplied by" indicate multiplication, which in algebra is written by placing the number and variable side by side (e.g., $2x$). "Quotient" indicates division, written as a fraction.</p><p><strong>Step 2: Write the expression</strong><br>The correct expression is $mn$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Write an algebraic expression for the following: $k$ is multiplied by $7$`,
    options: ["$7k$","$k + 7$","$k - 7$","$\\frac{k}{7}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Translate the operation</strong><br>"Product" and "multiplied by" indicate multiplication, which in algebra is written by placing the number and variable side by side (e.g., $2x$). "Quotient" indicates division, written as a fraction.</p><p><strong>Step 2: Write the expression</strong><br>The correct expression is $7k$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Write an algebraic expression for the following: The quotient when $a$ is divided by $b$`,
    options: ["$\\frac{a}{b}$","$\\frac{b}{a}$","$a - b$","$ab$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Translate the operation</strong><br>"Product" and "multiplied by" indicate multiplication, which in algebra is written by placing the number and variable side by side (e.g., $2x$). "Quotient" indicates division, written as a fraction.</p><p><strong>Step 2: Write the expression</strong><br>The correct expression is $\\frac{a}{b}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Write an algebraic expression for the following: The product of $9$ and $p$`,
    options: ["$9p$","$9 + p$","$p - 9$","$\\frac{p}{9}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Perform operations in order</strong><br>Follow the sequence described in the sentence. Multiplication comes first, then addition or subtraction.</p><p><strong>Step 2: Combine terms</strong><br>The final algebraic expression is $9p$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Write an algebraic expression for the following: The product of $u$ and $v$`,
    options: ["$uv$","$u + v$","$\\frac{u}{v}$","$u - v$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Perform operations in order</strong><br>Follow the sequence described in the sentence. Multiplication comes first, then addition or subtraction.</p><p><strong>Step 2: Combine terms</strong><br>The final algebraic expression is $uv$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Write an algebraic expression for the following: The difference of $m$ and $10$ (where $m > 10$)`,
    options: ["$m - 10$","$10 - m$","$10m$","$m + 10$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Perform operations in order</strong><br>Follow the sequence described in the sentence. Multiplication comes first, then addition or subtraction.</p><p><strong>Step 2: Combine terms</strong><br>The final algebraic expression is $m - 10$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Write an algebraic expression for the following: $y$ is multiplied by $5$, and $2$ is added to the result`,
    options: ["$5y + 2$","$5(y + 2)$","$2y + 5$","$5 + 2y$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Perform operations in order</strong><br>Follow the sequence described in the sentence. Multiplication comes first, then addition or subtraction.</p><p><strong>Step 2: Combine terms</strong><br>The final algebraic expression is $5y + 2$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Write an algebraic expression for the following: $k$ is multiplied by $6$, and $4$ is subtracted from the result`,
    options: ["$6k - 4$","$4k - 6$","$6(k - 4)$","$k - 10$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Perform operations in order</strong><br>Follow the sequence described in the sentence. Multiplication comes first, then addition or subtraction.</p><p><strong>Step 2: Combine terms</strong><br>The final algebraic expression is $6k - 4$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Write an algebraic expression for the following: $7$ is multiplied by $w$, and $5$ is added to the result`,
    options: ["$7w + 5$","$5w + 7$","$7(w + 5)$","$12w$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Perform operations in order</strong><br>Follow the sequence described in the sentence. Multiplication comes first, then addition or subtraction.</p><p><strong>Step 2: Combine terms</strong><br>The final algebraic expression is $7w + 5$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Write an algebraic expression for the following: $p$ is divided by $4$, and $3$ is added to it`,
    options: ["$\\frac{p}{4} + 3$","$\\frac{p+3}{4}$","$4p + 3$","$\\frac{4}{p} + 3$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Translate the operations</strong><br>Division is written as a fraction. Addition is written with $+$. Product is written by placing variables next to each other.</p><p><strong>Step 2: Combine correctly</strong><br>The correct expression is $\\frac{p}{4} + 3$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Write an algebraic expression for the following: $m$ is divided by $5$, and $7$ is subtracted from it`,
    options: ["$\\frac{m}{5} - 7$","$\\frac{m-7}{5}$","$5m - 7$","$\\frac{5}{m} - 7$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Translate the operations</strong><br>Division is written as a fraction. Addition is written with $+$. Product is written by placing variables next to each other.</p><p><strong>Step 2: Combine correctly</strong><br>The correct expression is $\\frac{m}{5} - 7$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Write an algebraic expression for the following: $a$, $b$ and $c$ are added together`,
    options: ["$a + b + c$","$abc$","$ab + c$","$a + bc$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Translate the operations</strong><br>Division is written as a fraction. Addition is written with $+$. Product is written by placing variables next to each other.</p><p><strong>Step 2: Combine correctly</strong><br>The correct expression is $a + b + c$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Write an algebraic expression for the following: The product of $r$, $s$ and $t$`,
    options: ["$rst$","$r + s + t$","$rs + t$","$r + st$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Translate the operations</strong><br>Division is written as a fraction. Addition is written with $+$. Product is written by placing variables next to each other.</p><p><strong>Step 2: Combine correctly</strong><br>The correct expression is $rst$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `An apple tree has $k$ apples on it. How many are left on the tree if $15$ apples fall off?`,
    options: ["$k - 15$","$15 - k$","$15k$","$k + 15$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Identify the relationship</strong><br>Determine whether the problem describes addition, subtraction, multiplication, or division.</p><p><strong>Step 2: Construct the expression</strong><br>The correct algebraic representation of the situation is $k - 15$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `There are $8$ bags, each containing $m$ candies. What is the total number of candies?`,
    options: ["$8m$","$8 + m$","$m - 8$","$\\frac{m}{8}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Identify the relationship</strong><br>Determine whether the problem describes addition, subtraction, multiplication, or division.</p><p><strong>Step 2: Construct the expression</strong><br>The correct algebraic representation of the situation is $8m$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `There are $p$ cookies to be divided equally among $4$ children. How many cookies does each child receive?`,
    options: ["$\\frac{p}{4}$","$4p$","$p - 4$","$\\frac{4}{p}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Identify the relationship</strong><br>Determine whether the problem describes addition, subtraction, multiplication, or division.</p><p><strong>Step 2: Construct the expression</strong><br>The correct algebraic representation of the situation is $\\frac{p}{4}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Emma has $\\$d$ in her savings account. She deposits $\\$500$ into the account. How much does she have in total now?`,
    options: ["$d + 500$","$500d$","$d - 500$","$\\frac{d}{500}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Identify the relationship</strong><br>Determine whether the problem describes addition, subtraction, multiplication, or division.</p><p><strong>Step 2: Construct the expression</strong><br>The correct algebraic representation of the situation is $d + 500$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Leo is $7$ years older than Mia, who is $y$ years old. How old is Leo?`,
    options: ["$y + 7$","$7y$","$y - 7$","$\\frac{y}{7}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Identify the relationship</strong><br>Determine whether the problem describes addition, subtraction, multiplication, or division.</p><p><strong>Step 2: Construct the expression</strong><br>The correct algebraic representation of the situation is $y + 7$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `The perimeter of a regular pentagon ($5$ equal sides) is $p$ cm. How long is each side?`,
    options: ["$\\frac{p}{5}$","$5p$","$p - 5$","$p + 5$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Identify the relationship</strong><br>Determine whether the problem describes addition, subtraction, multiplication, or division.</p><p><strong>Step 2: Construct the expression</strong><br>The correct algebraic representation of the situation is $\\frac{p}{5}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `If $w$ cartons each contain $12$ eggs, how many eggs are there in total?`,
    options: ["$12w$","$w + 12$","$w - 12$","$\\frac{w}{12}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Identify the relationship</strong><br>Determine whether the problem describes addition, subtraction, multiplication, or division.</p><p><strong>Step 2: Construct the expression</strong><br>The correct algebraic representation of the situation is $12w$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `The sum of two whole numbers is $25$. If one of the numbers is $k$, what is the other number?`,
    options: ["$25 - k$","$k - 25$","$25k$","$k + 25$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Identify the relationship</strong><br>Determine whether the problem describes addition, subtraction, multiplication, or division.</p><p><strong>Step 2: Construct the expression</strong><br>The correct algebraic representation of the situation is $25 - k$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Noah has $c$ stamps and collects $35$ more. How many stamps does Noah have now?`,
    options: ["$c + 35$","$35c$","$c - 35$","$\\frac{c}{35}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Identify the relationship</strong><br>Determine whether the problem describes addition, subtraction, multiplication, or division.</p><p><strong>Step 2: Construct the expression</strong><br>The correct algebraic representation of the situation is $c + 35$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y7-3',
    topicId: 'y7-3a',
    topicCode: '3A',
    topicTitle: 'Using algebra',
    year: 'Year 7',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `A square has $4$ sides of equal length. The sum of the lengths of the sides of the square is $L$ cm. What is the length of each side?`,
    options: ["$\\frac{L}{4}$","$4L$","$L - 4$","$L + 4$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Identify the relationship</strong><br>Determine whether the problem describes addition, subtraction, multiplication, or division.</p><p><strong>Step 2: Construct the expression</strong><br>The correct algebraic representation of the situation is $\\frac{L}{4}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
];

export const importYear7Ch3A = async (forceReset = false) => {
  console.log('[Ch3A Year 7 Import] STARTING PHYSICAL SYNC...');
  let importedCount = 0;
  try {
    const qRef = collection(db, 'questions');
    if (forceReset) {
      const oldSnap = await getDocs(query(qRef, where('topicId', '==', 'y7-3a')));
      for (const d of oldSnap.docs) { await deleteDoc(d.ref); }
    }
    const existingSnap = await getDocs(query(qRef, where('topicId', '==', 'y7-3a')));
    const existingQuestions = new Set(existingSnap.docs.map(doc => doc.data().question.trim()));
    
    for (const q of allQuestions) {
      if (!existingQuestions.has(q.question.trim())) {
        await addDoc(collection(db, 'questions'), q);
        importedCount++;
      }
    }
  } catch (error) { 
    console.error(error); 
    throw error; 
  }
  return importedCount;
};
