import { db } from '../firebase/config.js';
import { collection, addDoc, getDocs, query, where, deleteDoc } from 'firebase/firestore';

export const allQuestions = [
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Calculate mentally: $17 + 3$`,
    options: ["$20$","$10$","$30$","$18$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand the addition</strong><br>We need to add $17$ and $3$.</p><p><strong>Step 2: Mental strategy</strong><br>We can split $3$ into tens and units, or complete the nearest ten. For example: $17 + 3 = 20$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Calculate mentally: $6 + 34$`,
    options: ["$40$","$30$","$50$","$38$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand the addition</strong><br>We need to add $6$ and $34$.</p><p><strong>Step 2: Mental strategy</strong><br>We can split $34$ into tens and units, or complete the nearest ten. For example: $6 + 34 = 40$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Calculate mentally: $14 + 16$`,
    options: ["$30$","$20$","$40$","$28$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand the addition</strong><br>We need to add $14$ and $16$.</p><p><strong>Step 2: Mental strategy</strong><br>We can split $16$ into tens and units, or complete the nearest ten. For example: $14 + 16 = 30$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Calculate mentally: $63 + 7$`,
    options: ["$70$","$60$","$80$","$68$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand the addition</strong><br>We need to add $63$ and $7$.</p><p><strong>Step 2: Mental strategy</strong><br>We can split $7$ into tens and units, or complete the nearest ten. For example: $63 + 7 = 70$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Calculate mentally: $8 + 42$`,
    options: ["$50$","$40$","$60$","$48$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand the addition</strong><br>We need to add $8$ and $42$.</p><p><strong>Step 2: Mental strategy</strong><br>We can split $42$ into tens and units, or complete the nearest ten. For example: $8 + 42 = 50$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Calculate mentally: $9 + 51$`,
    options: ["$60$","$50$","$70$","$58$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand the addition</strong><br>We need to add $9$ and $51$.</p><p><strong>Step 2: Mental strategy</strong><br>We can split $51$ into tens and units, or complete the nearest ten. For example: $9 + 51 = 60$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Calculate mentally: $7 + 78$`,
    options: ["$85$","$75$","$95$","$83$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand the addition</strong><br>We need to add $7$ and $78$.</p><p><strong>Step 2: Mental strategy</strong><br>We can split $78$ into tens and units, or complete the nearest ten. For example: $7 + 78 = 85$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Calculate mentally: $43 + 8$`,
    options: ["$51$","$41$","$61$","$49$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand the addition</strong><br>We need to add $43$ and $8$.</p><p><strong>Step 2: Mental strategy</strong><br>We can split $8$ into tens and units, or complete the nearest ten. For example: $43 + 8 = 51$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Calculate mentally: $46 + 28$`,
    options: ["$74$","$64$","$84$","$72$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand the addition</strong><br>We need to add $46$ and $28$.</p><p><strong>Step 2: Mental strategy</strong><br>We can split $28$ into tens and units, or complete the nearest ten. For example: $46 + 28 = 74$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Calculate mentally: $53 + 29$`,
    options: ["$82$","$72$","$92$","$80$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand the addition</strong><br>We need to add $53$ and $29$.</p><p><strong>Step 2: Mental strategy</strong><br>We can split $29$ into tens and units, or complete the nearest ten. For example: $53 + 29 = 82$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Calculate mentally: $38 + 45$`,
    options: ["$83$","$73$","$93$","$81$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand the addition</strong><br>We need to add $38$ and $45$.</p><p><strong>Step 2: Mental strategy</strong><br>We can split $45$ into tens and units, or complete the nearest ten. For example: $38 + 45 = 83$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Calculate mentally: $68 + 74$`,
    options: ["$142$","$132$","$152$","$140$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Understand the addition</strong><br>We need to add $68$ and $74$.</p><p><strong>Step 2: Mental strategy</strong><br>We can split $74$ into tens and units, or complete the nearest ten. For example: $68 + 74 = 142$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Calculate: $2 + 8 + 45$`,
    options: ["$55$","$45$","$65$","$53$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Find friendly numbers</strong><br>Look for numbers that add up to a multiple of $10$ to make the mental math easier.</p><p><strong>Step 2: Add step-by-step</strong><br>Adding them together: $2 + 8 + 45 = 55$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Calculate: $3 + 47 + 6$`,
    options: ["$56$","$46$","$66$","$54$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Find friendly numbers</strong><br>Look for numbers that add up to a multiple of $10$ to make the mental math easier.</p><p><strong>Step 2: Add step-by-step</strong><br>Adding them together: $3 + 47 + 6 = 56$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Calculate: $38 + 4 + 2$`,
    options: ["$44$","$34$","$54$","$42$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Find friendly numbers</strong><br>Look for numbers that add up to a multiple of $10$ to make the mental math easier.</p><p><strong>Step 2: Add step-by-step</strong><br>Adding them together: $38 + 4 + 2 = 44$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Calculate: $25 + 15 + 8$`,
    options: ["$48$","$38$","$58$","$46$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Find friendly numbers</strong><br>Look for numbers that add up to a multiple of $10$ to make the mental math easier.</p><p><strong>Step 2: Add step-by-step</strong><br>Adding them together: $25 + 15 + 8 = 48$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Calculate: $52 + 8 + 36$`,
    options: ["$96$","$86$","$106$","$94$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Find friendly numbers</strong><br>Look for numbers that add up to a multiple of $10$ to make the mental math easier.</p><p><strong>Step 2: Add step-by-step</strong><br>Adding them together: $52 + 8 + 36 = 96$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Calculate: $7 + 33 + 45$`,
    options: ["$85$","$75$","$95$","$83$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Find friendly numbers</strong><br>Look for numbers that add up to a multiple of $10$ to make the mental math easier.</p><p><strong>Step 2: Add step-by-step</strong><br>Adding them together: $7 + 33 + 45 = 85$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Calculate: $28 + 44 + 19$`,
    options: ["$91$","$81$","$101$","$89$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Find friendly numbers</strong><br>Look for numbers that add up to a multiple of $10$ to make the mental math easier.</p><p><strong>Step 2: Add step-by-step</strong><br>Adding them together: $28 + 44 + 19 = 91$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Calculate: $64 + 27 + 38$`,
    options: ["$129$","$119$","$139$","$127$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Find friendly numbers</strong><br>Look for numbers that add up to a multiple of $10$ to make the mental math easier.</p><p><strong>Step 2: Add step-by-step</strong><br>Adding them together: $64 + 27 + 38 = 129$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Calculate: $31 + 24 + 19 + 26$`,
    options: ["$100$","$90$","$110$","$98$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Group friendly numbers</strong><br>Group the numbers that easily sum to multiples of $10$.</p><p><strong>Step 2: Add the pairs</strong><br>We can pair $(31 + 19) + (24 + 26)$ or similar combinations to get $50 + 50 = 100$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Calculate: $23 + 27 + 65 + 85$`,
    options: ["$200$","$190$","$210$","$198$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Group friendly numbers</strong><br>Group the numbers that easily sum to multiples of $10$.</p><p><strong>Step 2: Add the pairs</strong><br>We can pair $(23 + 65) + (27 + 85)$ or similar combinations to get $88 + 112 = 200$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Calculate: $14 + 36 + 58 + 2$`,
    options: ["$110$","$100$","$120$","$108$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Group friendly numbers</strong><br>Group the numbers that easily sum to multiples of $10$.</p><p><strong>Step 2: Add the pairs</strong><br>We can pair $(14 + 58) + (36 + 2)$ or similar combinations to get $72 + 38 = 110$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Calculate: $35 + 42 + 25 + 18$`,
    options: ["$120$","$110$","$130$","$118$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Group friendly numbers</strong><br>Group the numbers that easily sum to multiples of $10$.</p><p><strong>Step 2: Add the pairs</strong><br>We can pair $(35 + 25) + (42 + 18)$ or similar combinations to get $60 + 60 = 120$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Calculate: $25 + 43 + 37 + 45$`,
    options: ["$150$","$140$","$160$","$148$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Group friendly numbers</strong><br>Group the numbers that easily sum to multiples of $10$.</p><p><strong>Step 2: Add the pairs</strong><br>We can pair $(25 + 37) + (43 + 45)$ or similar combinations to get $62 + 88 = 150$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Calculate: $14 + 21 + 16 + 9$`,
    options: ["$60$","$50$","$70$","$58$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Group friendly numbers</strong><br>Group the numbers that easily sum to multiples of $10$.</p><p><strong>Step 2: Add the pairs</strong><br>We can pair $(14 + 16) + (21 + 9)$ or similar combinations to get $30 + 30 = 60$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Calculate: $352 + 48$`,
    options: ["$400$","$390$","$410$","$398$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Set up column addition</strong><br>Align the numbers by their place values.</p><p><strong>Step 2: Add step-by-step</strong><br>Starting from the units column and moving left, carrying over if necessary: $352 + 48 = 400$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Calculate: $674 + 26$`,
    options: ["$700$","$690$","$710$","$698$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Set up column addition</strong><br>Align the numbers by their place values.</p><p><strong>Step 2: Add step-by-step</strong><br>Starting from the units column and moving left, carrying over if necessary: $674 + 26 = 700$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Calculate: $415 + 35$`,
    options: ["$450$","$440$","$460$","$448$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Set up column addition</strong><br>Align the numbers by their place values.</p><p><strong>Step 2: Add step-by-step</strong><br>Starting from the units column and moving left, carrying over if necessary: $415 + 35 = 450$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Calculate: $853 + 47$`,
    options: ["$900$","$890$","$910$","$898$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Set up column addition</strong><br>Align the numbers by their place values.</p><p><strong>Step 2: Add step-by-step</strong><br>Starting from the units column and moving left, carrying over if necessary: $853 + 47 = 900$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Calculate: $542 + 38$`,
    options: ["$580$","$570$","$590$","$578$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Set up column addition</strong><br>Align the numbers by their place values.</p><p><strong>Step 2: Add step-by-step</strong><br>Starting from the units column and moving left, carrying over if necessary: $542 + 38 = 580$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Calculate: $841 + 69$`,
    options: ["$910$","$900$","$920$","$908$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Set up column addition</strong><br>Align the numbers by their place values.</p><p><strong>Step 2: Add step-by-step</strong><br>Starting from the units column and moving left, carrying over if necessary: $841 + 69 = 910$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Calculate: $375 + 625$`,
    options: ["$1000$","$990$","$1010$","$998$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Set up column addition</strong><br>Align the numbers by their place values.</p><p><strong>Step 2: Add step-by-step</strong><br>Starting from the units column and moving left, carrying over if necessary: $375 + 625 = 1000$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `Calculate: $452 + 339$`,
    options: ["$791$","$781$","$801$","$789$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Set up column addition</strong><br>Align the numbers by their place values.</p><p><strong>Step 2: Add step-by-step</strong><br>Starting from the units column and moving left, carrying over if necessary: $452 + 339 = 791$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `Three cows produced $32$ litres, $54$ litres, and $28$ litres of milk in one day. How much milk did they produce in total?`,
    options: ["$114$ litres","$104$ litres","$124$ litres","$110$ litres"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Identify the values</strong><br>The cows produced $32$, $54$, and $28$ litres.</p><p><strong>Step 2: Add the amounts</strong><br>$32 + 54 + 28 = 114$.</p><p><strong>Result</strong>: $114$ litres.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `A tiler laid $345$ tiles in the kitchen, $30$ tiles in the laundry, and $125$ tiles in the bathroom. How many tiles did they lay in total?`,
    options: ["$500$","$490$","$510$","$480$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Identify the values</strong><br>Tiles laid: $345$, $30$, and $125$.</p><p><strong>Step 2: Add the amounts</strong><br>$345 + 125 = 470$<br>$470 + 30 = 500$.</p><p><strong>Result</strong>: $500$ tiles.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `On the first day of a road trip, a family travelled $120\\text{ km}$ from their home to City A, then $485\\text{ km}$ from City A to City B. The next day, they travelled $315\\text{ km}$ from City B to City C. How many kilometres did they travel in the first two days of their trip?`,
    options: ["$920\\text{ km}$","$910\\text{ km}$","$930\\text{ km}$","$900\\text{ km}$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Sum the distances</strong><br>Day 1: $120 + 485 = 605\\text{ km}$.<br>Day 2: $315\\text{ km}$.</p><p><strong>Step 2: Total distance</strong><br>$605 + 315 = 920$.</p><p><strong>Result</strong>: $920\\text{ km}$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `A street performer collected $\\$15.00$, $\\$22.00$, $\\$9.00$, and $\\$18.00$ over four days. How much did they earn in total?`,
    options: ["$\\$64$","$\\$54$","$\\$74$","$\\$60$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: List the earnings</strong><br>$\\$15, \\$22, \\$9, \\$18$.</p><p><strong>Step 2: Add them up</strong><br>$(15 + 9) + (22 + 18) = 24 + 40 = 64$.</p><p><strong>Result</strong>: $\\$64$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    isActive: true,
    question: `In three Year 8 classes, $28$ students, $32$ students, and $25$ students attended roll call one morning. How many students were present in total?`,
    options: ["$85$","$75$","$95$","$80$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Group friendly numbers</strong><br>$28 + 32 = 60$.</p><p><strong>Step 2: Add the remaining class</strong><br>$60 + 25 = 85$.</p><p><strong>Result</strong>: $85$ students.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `A gardener picked $14$ apples from an orchard on Monday, $8$ on Tuesday, $26$ on Wednesday, $12$ on Thursday, and $15$ on Friday. How many apples did they pick over the five days?`,
    options: ["$75$","$65$","$85$","$70$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: List the amounts</strong><br>$14, 8, 26, 12, 15$.</p><p><strong>Step 2: Add systematically</strong><br>$(14 + 26) + (8 + 12) + 15$<br>$= 40 + 20 + 15 = 75$.</p><p><strong>Result</strong>: $75$ apples.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `In one month, Alex read four books. The first book had $245$ pages, the second $185$ pages, the third $55$ pages, and the fourth $115$ pages. How many pages did Alex read in total?`,
    options: ["$600$","$590$","$610$","$580$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Find pairs that sum nicely</strong><br>Notice that $245 + 55 = 300$, and $185 + 115 = 300$.</p><p><strong>Step 2: Add the pairs</strong><br>$300 + 300 = 600$.</p><p><strong>Result</strong>: $600$ pages.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    isActive: true,
    question: `By appropriately pairing numbers, calculate the sum of the first $10$ whole numbers starting from $1$: $1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10$.`,
    options: ["$55$","$45$","$65$","$50$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Pair from the outside in</strong><br>$(1 + 10) = 11$<br>$(2 + 9) = 11$<br>$(3 + 8) = 11$<br>$(4 + 7) = 11$<br>$(5 + 6) = 11$</p><p><strong>Step 2: Multiply by the number of pairs</strong><br>There are $5$ pairs of $11$, so $5 \\times 11 = 55$.</p></div>`,
    createdAt: new Date().toISOString()
  },
  {
    chapterId: 'y8-1',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Addition of whole numbers',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    isActive: true,
    question: `Use the pairing strategy to find the sum of all integers from $1$ to $50$ inclusive.`,
    options: ["$1275$","$1225$","$1300$","$1250$"],
    answer: 0,
    solution: `<div style="text-align: left;"><p><strong>Step 1: Form pairs</strong><br>We pair the smallest and largest numbers: $(1 + 50) = 51$, $(2 + 49) = 51$, and so on.</p><p><strong>Step 2: Count the pairs</strong><br>There are $50$ numbers in total, which means there are $50 \\div 2 = 25$ pairs.</p><p><strong>Step 3: Calculate the total sum</strong><br>Multiply the value of each pair by the number of pairs: $25 \\times 51$.<br>$25 \\times 50 = 1250$, and $25 \\times 1 = 25$.<br>$1250 + 25 = 1275$.</p></div>`,
    createdAt: new Date().toISOString()
  },
];

export const importYear8Ch1B = async (forceReset = false) => {
  console.log('[Ch1B Year 8 Import] STARTING PHYSICAL SYNC...');
  let importedCount = 0;
  try {
    const qRef = collection(db, 'questions');
    if (forceReset) {
      const oldSnap = await getDocs(query(qRef, where('topicId', '==', 'y8-1b')));
      for (const d of oldSnap.docs) { await deleteDoc(d.ref); }
    }
    const existingSnap = await getDocs(query(qRef, where('topicId', '==', 'y8-1b')));
    const existingQuestions = new Set(existingSnap.docs.map(doc => doc.data().question.trim()));
    
    for (const q of allQuestions) {
      if (!existingQuestions.has(q.question.trim())) {
        await addDoc(collection(db, 'questions'), q);
        importedCount++;
      }
    }
  } catch (error) { 
    console.error(error); 
    throw error; 
  }
  return importedCount;
};
