import { db } from '../firebase/config.js';
import { collection, addDoc, getDocs, query, where } from 'firebase/firestore';

export const allQuestions = [
  // SECTION 1: Simplify (1a-d)
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3a', topicCode: '3A', topicTitle: 'Collecting like terms', year: 'Year 10', type: 'short_answer', question: 'Simplify: $4x + 9x$', answer: '13x', solution: 'Step 1: Both are like terms with $x$.\nStep 2: $4 + 9 = 13$.\nResult: $13x$', difficulty: 'easy', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3a', topicCode: '3A', topicTitle: 'Collecting like terms', year: 'Year 10', type: 'short_answer', question: 'Simplify: $5p^3q - 9p^3q + 11p^3q$', answer: '7p^3q', solution: '$5 - 9 + 11 = 7$.\nResult: $7p^3q$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3a', topicCode: '3A', topicTitle: 'Collecting like terms', year: 'Year 10', type: 'short_answer', question: 'Simplify: $ab - 2ab^2 - 6ab + ab^2$', answer: '-5ab - ab^2', solution: '$(ab-6ab) + (-2ab^2+ab^2) = -5ab - ab^2$', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3a', topicCode: '3A', topicTitle: 'Collecting like terms', year: 'Year 10', type: 'short_answer', question: 'Simplify: $8x^3y - 2x^2y + 12x^3y - 8x^2y$', answer: '20x^3y - 10x^2y', solution: '$(8x^3y+12x^3y) + (-2x^2y-8x^2y) = 20x^3y - 10x^2y$', difficulty: 'hard', isManual: true },

  // SECTION 2: Expand (2a-f)
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'short_answer', question: 'Expand: $-2(a + 4)$', answer: '-2a - 8', solution: '$-2 \\times a + (-2) \\times 4 = -2a - 8$', difficulty: 'easy', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'short_answer', question: 'Expand: $-3(b + 6)$', answer: '-3b - 18', solution: '$-3 \\times b + (-3) \\times 6 = -3b - 18$', difficulty: 'easy', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'short_answer', question: 'Expand: $-4(3b - 5)$', answer: '-12b + 20', solution: '$-4 \\times 3b - (-4) \\times (-5) = -12b + 20$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'short_answer', question: 'Expand: $-5(4b - 7)$', answer: '-20b + 35', solution: '$-5 \\times 4b - (-5) \\times 7 = -20b + 35$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'multiple_choice', question: 'Expand: $\\frac{2}{3}(12p + 6)$', options: ['$8p + 4$', '$12p + 4$', '$8p + 6$', '$24p + 12$'], answer: '0', solution: '$\\frac{2}{3}(12p) + \\frac{2}{3}(6) = 8p + 4$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'multiple_choice', question: 'Expand: $-\\frac{1}{4}(16p - 20)$', options: ['$-4p + 5$', '$4p - 5$', '$-4p - 5$', '$-16p + 20$'], answer: '0', solution: '$-\\frac{1}{4}(16p) - (-\\frac{1}{4})(20) = -4p + 5$', difficulty: 'medium', isManual: true },

  // SECTION 3: Expand (3a-i)
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'short_answer', question: 'Expand: $d(d - 9)$', answer: 'd^2 - 9d', solution: '$d \\times d - d \\times 9 = d^2 - 9d$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'short_answer', question: 'Expand: $e(3e + 1)$', answer: '3e^2 + e', solution: '$e \\times 3e + e \\times 1 = 3e^2 + e$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'short_answer', question: 'Expand: $f(5f + 6)$', answer: '5f^2 + 6f', solution: '$f \\times 5f + f \\times 6 = 5f^2 + 6f$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'short_answer', question: 'Expand: $-2m(5m - 4)$', answer: '-10m^2 + 8m', solution: '$-2m(5m) - (-2m)(4) = -10m^2 + 8m$', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'short_answer', question: 'Expand: $-3n(5n + 7)$', answer: '-15n^2 - 21n', solution: '$-3n(5n) + (-3n)(7) = -15n^2 - 21n$', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'short_answer', question: 'Expand: $2p(3q - 5r)$', answer: '6pq - 10pr', solution: '$2p(3q) - 2p(5r) = 6pq - 10pr$', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'short_answer', question: 'Expand: $-3x(2x + 5y)$', answer: '-6x^2 - 15xy', solution: '$-3x(2x) - 3x(5y) = -6x^2 - 15xy$', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'short_answer', question: 'Expand: $-2z(3z - 4y)$', answer: '-6z^2 + 8zy', solution: '$-2z(3z) - 2z(-4y) = -6z^2 + 8zy$', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'short_answer', question: 'Expand: $2a(3 + 4ab)$', answer: '6a + 8a^2b', solution: '$2a(3) + 2a(4ab) = 6a + 8a^2b$', difficulty: 'hard', isManual: true },

  // SECTION 4: Expand and collect (4a-l)
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'short_answer', question: 'Expand and simplify: $2(c + 7) - 9$', answer: '2c + 5', solution: '$2c + 14 - 9 = 2c + 5$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'short_answer', question: 'Expand and simplify: $4(h + 1) + 3h$', answer: '7h + 4', solution: '$4h + 4 + 3h = 7h + 4$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'short_answer', question: 'Expand and simplify: $4(1 - 3q) + 15q$', answer: '3q + 4', solution: '$4 - 12q + 15q = 3q + 4$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'short_answer', question: 'Expand and simplify: $2a(3a + 2b) - 6a^2$', answer: '4ab', solution: '$6a^2 + 4ab - 6a^2 = 4ab$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'multiple_choice', question: 'Expand and simplify: $\\frac{5}{6}(x - 4) + \\frac{3x}{4}$', options: ['$\\frac{19x}{12} - \\frac{10}{3}$', '$\\frac{15x}{12} - 4$', '$\\frac{19x}{12} - \\frac{20}{6}$', '$\\frac{x}{2} - 3$'], answer: '0', solution: '$\\frac{5x}{6} - \\frac{10}{3} + \\frac{3x}{4} = \\frac{10x}{12} + \\frac{9x}{12} - \\frac{10}{3} = \\frac{19x}{12} - \\frac{10}{3}$', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'short_answer', question: 'Expand and simplify: $5(b - 2) - 4(b + 3)$', answer: 'b - 22', solution: '$5b - 10 - 4b - 12 = b - 22$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'short_answer', question: 'Expand and simplify: $4y(3y - 5) + 3(3y - 5)$', answer: '12y^2 - 11y - 15', solution: '$12y^2 - 20y + 9y - 15 = 12y^2 - 11y - 15$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'short_answer', question: 'Expand and simplify: $2p(3p + 1) - 4(2p + 1)$', answer: '6p^2 - 6p - 4', solution: '$6p^2 + 2p - 8p - 4 = 6p^2 - 6p - 4$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'multiple_choice', question: 'Expand: $(m + 4)(m - 5)$', options: ['$m^2 - m - 20$', '$m^2 + m - 20$', '$m^2 - 20$', '$m^2 - 9m - 20$'], answer: '0', solution: '$m^2 - 5m + 4m - 20 = m^2 - m - 20$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'multiple_choice', question: 'Expand: $(6x - 5)(x + 2)$', options: ['$6x^2 + 7x - 10$', '$6x^2 - 7x - 10$', '$6x^2 + 12x - 10$', '$6x^2 + 17x - 10$'], answer: '0', solution: '$6x^2 + 12x - 5x - 10 = 6x^2 + 7x - 10$', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'multiple_choice', question: 'Expand: $(7x - 1)(x - 5)$', options: ['$7x^2 - 36x + 5$', '$7x^2 - 34x + 5$', '$7x^2 - 36x - 5$', '$7x^2 + 36x + 5$'], answer: '0', solution: '$7x^2 - 35x - x + 5 = 7x^2 - 36x + 5$', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3b', topicCode: '3B', topicTitle: 'Expansion', year: 'Year 10', type: 'multiple_choice', question: 'Expand: $(m + 3n)(2m + n)$', options: ['$2m^2 + 7mn + 3n^2$', '$2m^2 + 6mn + 3n^2$', '$2m^2 + 3n^2$', '$2m^2 + mn + 3n^2$'], answer: '0', solution: '$2m^2 + mn + 6mn + 3n^2 = 2m^2 + 7mn + 3n^2$', difficulty: 'hard', isManual: true },

  // SECTION 5: Solve (5a-i)
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3c', topicCode: '3C', topicTitle: 'Solving equations', year: 'Year 10', type: 'short_answer', question: 'Solve: $7x - 4 = 17$', answer: '3', solution: '$7x = 21 \\Rightarrow x = 3$', difficulty: 'easy', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3c', topicCode: '3C', topicTitle: 'Solving equations', year: 'Year 10', type: 'short_answer', question: 'Solve: $3x = 25 - 2x$', answer: '5', solution: '$5x = 25 \\Rightarrow x = 5$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3c', topicCode: '3C', topicTitle: 'Solving equations', year: 'Year 10', type: 'short_answer', question: 'Solve: $7x = 18 - 2x$', answer: '2', solution: '$9x = 18 \\Rightarrow x = 2$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3c', topicCode: '3C', topicTitle: 'Solving equations', year: 'Year 10', type: 'short_answer', question: 'Solve: $\\frac{x}{3} + 2 = 7$', answer: '15', solution: '$\\frac{x}{3} = 5 \\Rightarrow x = 15$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3c', topicCode: '3C', topicTitle: 'Solving equations', year: 'Year 10', type: 'short_answer', question: 'Solve: $\\frac{3x}{2} + 2 = 8$', answer: '4', solution: '$\\frac{3x}{2} = 6 \\Rightarrow 3x = 12 \\Rightarrow x = 4$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3c', topicCode: '3C', topicTitle: 'Solving equations', year: 'Year 10', type: 'short_answer', question: 'Solve: $3x - 7 = x + 1$', answer: '4', solution: '$2x = 8 \\Rightarrow x = 4$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3c', topicCode: '3C', topicTitle: 'Solving equations', year: 'Year 10', type: 'short_answer', question: 'Solve: $\\frac{7x}{2} + 2x = 12 - x$', answer: '24/13', solution: '$3.5x + 2x + x = 12 \\Rightarrow 6.5x = 12 \\Rightarrow x = 12/6.5 = 24/13$', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3c', topicCode: '3C', topicTitle: 'Solving equations', year: 'Year 10', type: 'short_answer', question: 'Solve: $\\frac{x}{2} + \\frac{x}{5} = 14$', answer: '20', solution: '$\\frac{5x}{10} + \\frac{2x}{10} = 14 \\Rightarrow \\frac{7x}{10} = 14 \\Rightarrow 7x = 140 \\Rightarrow x = 20$', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3c', topicCode: '3C', topicTitle: 'Solving equations', year: 'Year 10', type: 'short_answer', question: 'Solve: $3(2x - 1) + 3x = 15$', answer: '2', solution: '$6x - 3 + 3x = 15 \\Rightarrow 9x = 18 \\Rightarrow x = 2$', difficulty: 'hard', isManual: true },

  // SECTION 6: Inequalities (6a-i)
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3d', topicCode: '3D', topicTitle: 'Inequalities', year: 'Year 10', type: 'graph_sketch', question: 'Solve and graph: $x + 1 > 5$', answer: 'x > 4', solution: '$x > 4$. Open circle at 4, arrow right.', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3d', topicCode: '3D', topicTitle: 'Inequalities', year: 'Year 10', type: 'graph_sketch', question: 'Solve and graph: $2x - 1 < 6$', answer: 'x < 3.5', solution: '$2x < 7 \\Rightarrow x < 3.5$. Open circle, arrow left.', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3d', topicCode: '3D', topicTitle: 'Inequalities', year: 'Year 10', type: 'graph_sketch', question: 'Solve and graph: $\\frac{x + 1}{2} \\ge -4$', answer: 'x \\ge -9', solution: '$x + 1 \\ge -8 \\Rightarrow x \\ge -9$. Solid circle, arrow right.', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3d', topicCode: '3D', topicTitle: 'Inequalities', year: 'Year 10', type: 'graph_sketch', question: 'Solve and graph: $-2x + 1 \\le 6$', answer: 'x \\ge -2.5', solution: '$-2x \\le 5 \\Rightarrow x \\ge -2.5$. Solid circle, arrow right.', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3d', topicCode: '3D', topicTitle: 'Inequalities', year: 'Year 10', type: 'graph_sketch', question: 'Solve and graph: $4 - 7x \\ge 6$', answer: 'x \\le -2/7', solution: '$-7x \\ge 2 \\Rightarrow x \\le -2/7$. Solid circle, arrow left.', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3d', topicCode: '3D', topicTitle: 'Inequalities', year: 'Year 10', type: 'graph_sketch', question: 'Solve and graph: $\\frac{-3x + 2}{6} \\le 1$', answer: 'x \\ge -4/3', solution: '$-3x + 2 \\le 6 \\Rightarrow -3x \\le 4 \\Rightarrow x \\ge -4/3$. Solid circle, arrow right.', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3d', topicCode: '3D', topicTitle: 'Inequalities', year: 'Year 10', type: 'graph_sketch', question: 'Solve and graph: $\\frac{2x - 1}{3} \\le \\frac{x + 1}{4}$', answer: 'x \\le 1.4', solution: '$8x - 4 \\le 3x + 3 \\Rightarrow 5x \\le 7 \\Rightarrow x \\le 1.4$. Solid circle, arrow left.', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3d', topicCode: '3D', topicTitle: 'Inequalities', year: 'Year 10', type: 'graph_sketch', question: 'Solve and graph: $\\frac{5x + 6}{3} \\le 2x + 7$', answer: 'x \\ge -15', solution: '$5x + 6 \\le 6x + 21 \\Rightarrow -x \\le 15 \\Rightarrow x \\ge -15$. Solid circle, arrow right.', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3d', topicCode: '3D', topicTitle: 'Inequalities', year: 'Year 10', type: 'graph_sketch', question: 'Solve and graph: $4 - 6x \\le 3 + 2x$', answer: 'x \\ge 1/8', solution: '$1 \\le 8x \\Rightarrow x \\ge 1/8$. Solid circle, arrow right.', difficulty: 'hard', isManual: true },

  // SECTION 7-15 (Image 2)
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3e', topicCode: '3E', topicTitle: 'Formulas', year: 'Year 10', type: 'multiple_choice', question: 'Find $R$ if $r_1 = 4, r_2 = 3$ in $\\frac{1}{R} = \\frac{1}{r_1} + \\frac{1}{r_2}$.', options: ['$12/7$', '$7/12$', '$7$', '$1$'], answer: '0', solution: '$\\frac{1}{R} = \\frac{1}{4} + \\frac{1}{3} = \\frac{7}{12} \\Rightarrow R = 12/7$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3e', topicCode: '3E', topicTitle: 'Formulas', year: 'Year 10', type: 'short_answer', question: 'Find $r_1$ if $R = 2, r_2 = 6$ in $\\frac{1}{R} = \\frac{1}{r_1} + \\frac{1}{r_2}$.', answer: '3', solution: '$\\frac{1}{2} = \\frac{1}{r_1} + \\frac{1}{6} \\Rightarrow \\frac{1}{r_1} = 1/2 - 1/6 = 1/3 \\Rightarrow r_1 = 3$', difficulty: 'medium', isManual: true },
  
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3e', topicCode: '3E', topicTitle: 'Formulas', year: 'Year 10', type: 'short_answer', question: 'Find $P$ when $a = 6, b = 7$ in $P = 4(a + b)$.', answer: '52', solution: '$P = 4(6 + 7) = 52$', difficulty: 'easy', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3e', topicCode: '3E', topicTitle: 'Formulas', year: 'Year 10', type: 'multiple_choice', question: 'Make $a$ the subject of $P = 4(a + b)$.', options: ['$a = P/4 - b$', '$a = P/4 + b$', '$a = P - 4b$', '$a = 4P - b$'], answer: '0', solution: '$P/4 = a + b \\Rightarrow a = P/4 - b$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3e', topicCode: '3E', topicTitle: 'Formulas', year: 'Year 10', type: 'short_answer', question: 'Find $a$ when $P = 20, b = 6$ in $P = 4(a + b)$.', answer: '-1', solution: '$20 = 4(a + 6) \\Rightarrow 5 = a + 6 \\Rightarrow a = -1$', difficulty: 'medium', isManual: true },

  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3e', topicCode: '3E', topicTitle: 'Formulas', year: 'Year 10', type: 'multiple_choice', question: 'Make $h$ the subject of $A = \\pi r^2 + \\pi rh$.', options: ['$h = (A - \\pi r^2)/(\\pi r)$', '$h = A - \\pi r^2$', '$h = A/(\\pi r) - r$', '$h = (A + \\pi r^2)/(\\pi r)$'], answer: '0', solution: '$A - \\pi r^2 = \\pi rh \\Rightarrow h = (A - \\pi r^2)/\\pi r$', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3e', topicCode: '3E', topicTitle: 'Formulas', year: 'Year 10', type: 'multiple_choice', question: 'Make $h$ the subject of $A = \\pi r \\sqrt{h^2 + r^2}$.', options: ['$h = \\sqrt{(A/\\pi r)^2 - r^2}$', '$h = A^2/(\\pi^2 r^2) - r^2$', '$h = \\sqrt{A/\\pi r - r^2}$', '$h = (A/\\pi r) - r$'], answer: '0', solution: '$\\frac{A}{\\pi r} = \\sqrt{h^2+r^2} \\Rightarrow \\frac{A^2}{\\pi^2 r^2} = h^2+r^2 \\Rightarrow h = \\sqrt{(\\frac{A}{\\pi r})^2 - r^2}$', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3e', topicCode: '3E', topicTitle: 'Formulas', year: 'Year 10', type: 'multiple_choice', question: 'Make $u$ the subject of $E = \\frac{1}{2}m(v^2 - u^2)$.', options: ['$u = \\sqrt{v^2 - 2E/m}$', '$u = v^2 - 2E/m$', '$u = \\sqrt{2E/m - v^2}$', '$u = v - \\sqrt{2E/m}$'], answer: '0', solution: '$\\frac{2E}{m} = v^2 - u^2 \\Rightarrow u^2 = v^2 - \\frac{2E}{m} \\Rightarrow u = \\sqrt{v^2 - \\frac{2E}{m}}$', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3e', topicCode: '3E', topicTitle: 'Formulas', year: 'Year 10', type: 'multiple_choice', question: 'Make $x$ the subject of $\\frac{ax + by}{c} = x - b$.', options: ['$x = (bc + by)/(c - a)$', '$x = (bc + by)/(a - c)$', '$x = (by - bc)/(c - a)$', '$x = by/(c - a)$'], answer: '0', solution: '$ax + by = cx - bc \\Rightarrow bc + by = cx - ax = x(c-a) \\Rightarrow x = (bc+by)/(c-a)$', difficulty: 'hard', isManual: true },

  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $49 - z^2$', options: ['$(7 - z)(7 + z)$', '$(z - 7)(z + 7)$', '$(7 - z)^2$', '$(49 - z)(1 + z)$'], answer: '0', solution: '$(7-z)(7+z)$', difficulty: 'easy', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $9 - 4a^2$', options: ['$(3 - 2a)(3 + 2a)$', '$(3 - 4a)(3 + 4a)$', '$(3 - 2a)^2$', '$(9 - 2a)(1 + 2a)$'], answer: '0', solution: '$(3-2a)(3+2a)$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $25 - 64x^2$', options: ['$(5 - 8x)(5 + 8x)$', '$(5 - 8x)^2$', '$(8x - 5)(8x + 5)$', '$(25 - 8x)(1 + 8x)$'], answer: '0', solution: '$(5-8x)(5+8x)$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $a^2b^2 - 4c^2d^2$', options: ['$(ab - 2cd)(ab + 2cd)$', '$(ab - 2cd)^2$', '$(ab + 2cd)(ab - 2cd)$', '$(a^2b^2 - 2cd)(1 + 2cd)$'], answer: '0', solution: '$(ab-2cd)(ab+2cd)$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $9x^2 - 1$', options: ['$(3x - 1)(3x + 1)$', '$(3x - 1)^2$', '$(9x - 1)(x + 1)$', '$(1 - 3x)(1 + 3x)$'], answer: '0', solution: '$(3x-1)(3x+1)$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $36p^2 - 49q^2$', options: ['$(6p - 7q)(6p + 7q)$', '$(6p - 7q)^2$', '$(36p - 7q)(1 + 7q)$', '$(7q - 6p)(7q + 6p)$'], answer: '0', solution: '$(6p-7q)(6p+7q)$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $1 - 100b^2$', options: ['$(1 - 10b)(1 + 10b)$', '$(1 - 10b)^2$', '$(10b - 1)(10b + 1)$', '$(1 - 50b)(1 + 2b)$'], answer: '0', solution: '$(1-10b)(1+10b)$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $121a^2 - 81b^2$', options: ['$(11a - 9b)(11a + 9b)$', '$(11a - 9b)^2$', '$(11a + 81b)(11a - b)$', '$(9b - 11a)(9b + 11a)$'], answer: '0', solution: '$(11a-9b)(11a+9b)$', difficulty: 'medium', isManual: true },

  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise using surds: $x^2 - 11$', options: ['$(x - \\sqrt{11})(x + \\sqrt{11})$', '$(x - 11)(x + 11)$', '$(x - \\sqrt{11})^2$', '$(11 - x)(11 + x)$'], answer: '0', solution: '$(x-\\sqrt{11})(x+\\sqrt{11})$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise using surds: $x^2 - 15$', options: ['$(x - \\sqrt{15})(x + \\sqrt{15})$', '$(x - 15)(x + 15)$', '$(x - \\sqrt{15})^2$', '$(15 - x)(15 + x)$'], answer: '0', solution: '$(x-\\sqrt{15})(x+\\sqrt{15})$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise using surds: $x^2 - 28$', options: ['$(x - 2\\sqrt{7})(x + 2\\sqrt{7})$', '$(x - \\sqrt{28})(x + \\sqrt{28})$', '$(x - 28)(x + 28)$', '$(x - 2\\sqrt{7})^2$'], answer: '0', solution: '$x^2 - 28 = (x-\\sqrt{28})(x+\\sqrt{28}) = (x-2\\sqrt{7})(x+2\\sqrt{7})$', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise using surds: $x^2 - 32$', options: ['$(x - 4\\sqrt{2})(x + 4\\sqrt{2})$', '$(x - \\sqrt{32})(x + \\sqrt{32})$', '$(x - 32)(x + 32)$', '$(x - 4\\sqrt{2})^2$'], answer: '0', solution: '$x^2 - 32 = (x-\\sqrt{32})(x+\\sqrt{32}) = (x-4\\sqrt{2})(x+4\\sqrt{2})$', difficulty: 'hard', isManual: true },

  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $(x + 4)^2 - 2$', options: ['$(x + 4 - \\sqrt{2})(x + 4 + \\sqrt{2})$', '$(x + 4 - 2)(x + 4 + 2)$', '$(x + 2)(x + 6)$', '$(x + 4 - \\sqrt{2})^2$'], answer: '0', solution: '$(x+4-\\sqrt{2})(x+4+\\sqrt{2})$', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $(x - 3)^2 - 5$', options: ['$(x - 3 - \\sqrt{5})(x - 3 + \\sqrt{5})$', '$(x - 3 - 5)(x - 3 + 5)$', '$(x - 8)(x + 2)$', '$(x - 3 - \\sqrt{5})^2$'], answer: '0', solution: '$(x-3-\\sqrt{5})(x-3+\\sqrt{5})$', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $(2x + 1)^2 - 20$', options: ['$(2x + 1 - 2\\sqrt{5})(2x + 1 + 2\\sqrt{5})$', '$(2x + 1 - \\sqrt{20})(2x + 1 + \\sqrt{20})$', '$(2x - 19)(2x + 21)$', '$(2x + 1 - 2\\sqrt{5})^2$'], answer: '0', solution: '$(2x+1-\\sqrt{20})(2x+1+\\sqrt{20}) = (2x+1-2\\sqrt{5})(2x+1+2\\sqrt{5})$', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $(3 - 2x)^2 - 10$', options: ['$(3 - 2x - \\sqrt{10})(3 - 2x + \\sqrt{10})$', '$(3 - 2x - 10)(3 - 2x + 10)$', '$( -7 - 2x)(13 - 2x)$', '$(3 - 2x - \\sqrt{10})^2$'], answer: '0', solution: '$(3-2x-\\sqrt{10})(3-2x+\\sqrt{10})$', difficulty: 'hard', isManual: true },

  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $(a + b)^2 - c^2$', options: ['$(a + b - c)(a + b + c)$', '$(a + b - c)^2$', '$(a + b + c)^2$', '$(a - b - c)(a - b + c)$'], answer: '0', solution: '$(a+b-c)(a+b+c)$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $(a - b)^2 - c^2$', options: ['$(a - b - c)(a - b + c)$', '$(a - b - c)^2$', '$(a + b - c)(a + b + c)$', '$(a - b + c)^2$'], answer: '0', solution: '$(a-b-c)(a-b+c)$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $(x + y)^2 - 4z^2$', options: ['$(x + y - 2z)(x + y + 2z)$', '$(x + y - 4z)(x + y + 4z)$', '$(x + y - 2z)^2$', '$(x - y - 2z)(x - y + 2z)$'], answer: '0', solution: '$(x+y-2z)(x+y+2z)$', difficulty: 'hard', isManual: true },

  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $2ax - a + 6x - 3$', options: ['$(2x - 1)(a + 3)$', '$(2x + 1)(a - 3)$', '$(x - 1)(2a + 3)$', '$(2x - 1)(a - 3)$'], answer: '0', solution: '$a(2x-1) + 3(2x-1) = (2x-1)(a+3)$', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $ab + 5b - 2a - 10$', options: ['$(a + 5)(b - 2)$', '$(a - 5)(b + 2)$', '$(a + 5)(b + 2)$', '$(a - 5)(b - 2)$'], answer: '0', solution: '$b(a+5) - 2(a+5) = (a+5)(b-2)$', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $2xy + 3y + 10x + 15$', options: ['$(2x + 3)(y + 5)$', '$(2x - 3)(y - 5)$', '$(x + 3)(2y + 5)$', '$(2x + 3)(y - 5)$'], answer: '0', solution: '$y(2x+3) + 5(2x+3) = (2x+3)(y+5)$', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $3mx - 21x + 2m - 14$', options: ['$(m - 7)(3x + 2)$', '$(m + 7)(3x - 2)$', '$(3m - 7)(x + 2)$', '$(m - 7)(3x - 2)$'], answer: '0', solution: '$3x(m-7) + 2(m-7) = (m-7)(3x+2)$', difficulty: 'hard', isManual: true },

  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $x^2 - 3x + 2$', options: ['$(x - 2)(x - 1)$', '$(x + 2)(x + 1)$', '$(x - 2)(x + 1)$', '$(x + 2)(x - 1)$'], answer: '0', solution: '$(x-2)(x-1)$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $c^2 + 12c + 11$', options: ['$(c + 11)(c + 1)$', '$(c + 6)(c + 6)$', '$(c - 11)(c - 1)$', '$(c + 12)(c + 1)$'], answer: '0', solution: '$(c+11)(c+1)$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $x^2 - 4x - 5$', options: ['$(x - 5)(x + 1)$', '$(x + 5)(x - 1)$', '$(x - 5)(x - 1)$', '$(x + 4)(x - 1)$'], answer: '0', solution: '$(x-5)(x+1)$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $y^2 + 9y - 10$', options: ['$(y + 10)(y - 1)$', '$(y - 10)(y + 1)$', '$(y + 5)(y + 4)$', '$(y + 9)(y - 1)$'], answer: '0', solution: '$(y+10)(y-1)$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $z^2 - 6z - 16$', options: ['$(z - 8)(z + 2)$', '$(z + 8)(z - 2)$', '$(z - 4)(z - 4)$', '$(z - 16)(z + 1)$'], answer: '0', solution: '$(z-8)(z+2)$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $c^2 + 8c - 20$', options: ['$(c + 10)(c - 2)$', '$(c - 10)(c + 2)$', '$(c + 4)(c + 5)$', '$(c + 20)(c - 1)$'], answer: '0', solution: '$(c+10)(c-2)$', difficulty: 'medium', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $p^2 - 11p - 26$', options: ['$(p - 13)(p + 2)$', '$(p + 13)(p - 2)$', '$(p - 26)(p + 1)$', '$(p - 11)(p - 2)$'], answer: '0', solution: '$(p-13)(p+2)$', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $k^2 - 11k - 42$', options: ['$(k - 14)(k + 3)$', '$(k + 14)(k - 3)$', '$(k - 21)(k + 2)$', '$(k - 7)(k - 6)$'], answer: '0', solution: '$(k-14)(k+3)$', difficulty: 'hard', isManual: true },
  { chapterId: 'y10-3', chapterTitle: 'Chapter 3: Algebra review', topicId: 'y10-3f', topicCode: '3F', topicTitle: 'Factorising', year: 'Year 10', type: 'multiple_choice', question: 'Factorise: $x^2 + 4x - 60$', options: ['$(x + 10)(x - 6)$', '$(x - 10)(x + 6)$', '$(x + 12)(x - 5)$', '$(x + 15)(x - 4)$'], answer: '0', solution: '$(x+10)(x-6)$', difficulty: 'hard', isManual: true }
];

export const importYear10Ch3 = async () => {
  console.log('Starting Year 10 Chapter 3 TOTAL import...');
  let importedCount = 0;
  
  for (const q of allQuestions) {
    try {
      const qRef = collection(db, 'questions');
      const dupQuery = query(qRef, where('question', '==', q.question));
      const dupSnap = await getDocs(dupQuery);
      
      if (dupSnap.empty) {
        await addDoc(collection(db, 'questions'), q);
        importedCount++;
      }
    } catch (error) {
      console.error('Error importing question:', error);
    }
  }
  
  console.log(`Successfully added ${importedCount} NEW Year 10 Ch 3 questions.`);
  return importedCount;
};
