import admin from 'firebase-admin';
import { readFileSync } from 'fs';

const serviceAccount = JSON.parse(readFileSync('/Users/andrewkim/Downloads/sapere-fe23e-firebase-adminsdk-fbsvc-d9dd93623b.json', 'utf8'));

if (!admin.apps.length) {
  admin.initializeApp({
    credential: admin.credential.cert(serviceAccount)
  });
}
const db = admin.firestore();

export const allQuestions = [
  // 1A - Addition and Subtraction
  // Q1: Mental Sums
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $47 + 33$ mentally.',
    options: ['80', '70', '90', '77'],
    answer: 0,
    solution: 'To calculate $47 + 33$ mentally:\n1. Add the tens: $40 + 30 = 70$\n2. Add the units: $7 + 3 = 10$\n3. Combine: $70 + 10 = 80$\n\nResult: **80**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $41 + 27$ mentally.',
    options: ['68', '58', '78', '67'],
    answer: 0,
    solution: 'To calculate $41 + 27$ mentally:\n1. Add the tens: $40 + 20 = 60$\n2. Add the units: $1 + 7 = 8$\n3. Combine: $60 + 8 = 68$\n\nResult: **68**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $36 + 28$ mentally.',
    options: ['64', '54', '74', '62'],
    answer: 0,
    solution: 'To calculate $36 + 28$ mentally:\n1. Add the tens: $30 + 20 = 50$\n2. Add the units: $6 + 8 = 14$\n3. Combine: $50 + 14 = 64$\n\nResult: **64**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $53 + 29$ mentally.',
    options: ['82', '72', '92', '81'],
    answer: 0,
    solution: 'To calculate $53 + 29$ mentally:\n1. Add 30 to 53: $53 + 30 = 83$\n2. Subtract 1 (since 29 is $30 - 1$): $83 - 1 = 82$\n\nResult: **82**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $24 + 16$ mentally.',
    options: ['40', '30', '50', '38'],
    answer: 0,
    solution: 'To calculate $24 + 16$ mentally:\n1. $4 + 6 = 10$\n2. $20 + 10 + 10 = 40$\n\nResult: **40**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $7 + 78$ mentally.',
    options: ['85', '75', '95', '83'],
    answer: 0,
    solution: 'To calculate $7 + 78$ mentally:\n1. $78 + 2 = 80$\n2. $80 + 5 = 85$\n\nResult: **85**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $23 + 67$ mentally.',
    options: ['90', '80', '100', '87'],
    answer: 0,
    solution: 'To calculate $23 + 67$ mentally:\n1. Add units: $3 + 7 = 10$\n2. Add tens: $20 + 60 = 80$\n3. Total: $80 + 10 = 90$\n\nResult: **90**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $34 + 59$ mentally.',
    options: ['93', '83', '103', '91'],
    answer: 0,
    solution: 'To calculate $34 + 59$ mentally:\n1. $34 + 60 = 94$\n2. $94 - 1 = 93$\n\nResult: **93**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $76 + 4$ mentally.',
    options: ['80', '70', '90', '78'],
    answer: 0,
    solution: 'Simple addition: $76 + 4 = 80$\n\nResult: **80**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $45 + 8$ mentally.',
    options: ['53', '43', '63', '51'],
    answer: 0,
    solution: 'To calculate $45 + 8$ mentally:\n1. $45 + 5 = 50$\n2. $50 + 3 = 53$\n\nResult: **53**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $12 + 8 + 44$ mentally.',
    options: ['64', '54', '74', '62'],
    answer: 0,
    solution: '1. Group $12 + 8 = 20$\n2. $20 + 44 = 64$\n\nResult: **64**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $3 + 17 + 45$ mentally.',
    options: ['65', '55', '75', '63'],
    answer: 0,
    solution: '1. Group $3 + 17 = 20$\n2. $20 + 45 = 65$\n\nResult: **65**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $52 + 34 + 8$ mentally.',
    options: ['94', '84', '104', '92'],
    answer: 0,
    solution: '1. Group $52 + 8 = 60$\n2. $60 + 34 = 94$\n\nResult: **94**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $6 + 53 + 27$ mentally.',
    options: ['86', '76', '96', '84'],
    answer: 0,
    solution: '1. Group $53 + 27 = 80$\n2. $80 + 6 = 86$\n\nResult: **86**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $36 + 9 + 4$ mentally.',
    options: ['49', '39', '59', '47'],
    answer: 0,
    solution: '1. Group $36 + 4 = 40$\n2. $40 + 9 = 49$\n\nResult: **49**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $17 + 33 + 6$ mentally.',
    options: ['56', '46', '66', '54'],
    answer: 0,
    solution: '1. Group $17 + 33 = 50$\n2. $50 + 6 = 56$\n\nResult: **56**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    question: 'Calculate $27 + 43 + 15 + 35$ mentally.',
    options: ['120', '110', '130', '115'],
    answer: 0,
    solution: '1. Pair $27 + 43 = 70$\n2. Pair $15 + 35 = 50$\n3. $70 + 50 = 120$\n\nResult: **120**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    question: 'Calculate $61 + 24 + 39 + 16$ mentally.',
    options: ['140', '130', '150', '136'],
    answer: 0,
    solution: '1. Pair $61 + 39 = 100$\n2. Pair $24 + 16 = 40$\n3. $100 + 40 = 140$\n\nResult: **140**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    question: 'Calculate $32 + 14 + 28 + 16$ mentally.',
    options: ['90', '80', '100', '86'],
    answer: 0,
    solution: '1. Pair $32 + 28 = 60$\n2. Pair $14 + 16 = 30$\n3. $60 + 30 = 90$\n\nResult: **90**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    question: 'Calculate $42 + 58 + 73 + 7$ mentally.',
    options: ['180', '170', '190', '175'],
    answer: 0,
    solution: '1. Pair $42 + 58 = 100$\n2. Pair $73 + 7 = 80$\n3. $100 + 80 = 180$\n\nResult: **180**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    question: 'Calculate $25 + 74 + 35 + 26$ mentally.',
    options: ['160', '150', '170', '155'],
    answer: 0,
    solution: '1. Pair $25 + 35 = 60$\n2. Pair $74 + 26 = 100$\n3. $60 + 100 = 160$\n\nResult: **160**'
  },

  // Q2: Mental Subtractions
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $42 - 8$ mentally.',
    options: ['34', '32', '36', '35'],
    answer: 0,
    solution: 'To calculate $42 - 8$:\n1. Subtract 2 to reach 40: $42 - 2 = 40$\n2. Subtract the remaining 6: $40 - 6 = 34$\n\nResult: **34**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $53 - 49$ mentally.',
    options: ['4', '6', '3', '5'],
    answer: 0,
    solution: 'To calculate $53 - 49$:\n1. 49 is very close to 53.\n2. Count up from 49 to 53: $49 + 1 = 50$, $50 + 3 = 53$.\n3. Difference is $1 + 3 = 4$.\n\nResult: **4**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $83 - 55$ mentally.',
    options: ['28', '38', '22', '33'],
    answer: 0,
    solution: 'To calculate $83 - 55$:\n1. $83 - 50 = 33$\n2. $33 - 5 = 28$\n\nResult: **28**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $67 - 59$ mentally.',
    options: ['8', '7', '9', '6'],
    answer: 0,
    solution: '1. $67 - 60 = 7$\n2. Add 1 back (since we subtracted 60 instead of 59): $7 + 1 = 8$\n\nResult: **8**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    question: 'Calculate $632 - 519$ mentally.',
    options: ['113', '123', '111', '103'],
    answer: 0,
    solution: '1. $600 - 500 = 100$\n2. $32 - 19 = 13$\n3. $100 + 13 = 113$\n\nResult: **113**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    question: 'Calculate $504 - 487$ mentally.',
    options: ['17', '27', '13', '23'],
    answer: 0,
    solution: '1. Distance from 487 to 500 is 13.\n2. Add the extra 4 from 504: $13 + 4 = 17$\n\nResult: **17**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    question: 'Calculate $875 - 796$ mentally.',
    options: ['79', '89', '69', '75'],
    answer: 0,
    solution: '1. $875 - 800 = 75$\n2. Add 4 back (since 796 is $800 - 4$): $75 + 4 = 79$\n\nResult: **79**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    question: 'Calculate $729 - 618$ mentally.',
    options: ['111', '101', '121', '118'],
    answer: 0,
    solution: '1. $700 - 600 = 100$\n2. $29 - 18 = 11$\n3. $100 + 11 = 111$\n\nResult: **111**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    question: 'Calculate $924 - 735$ mentally.',
    options: ['189', '199', '179', '185'],
    answer: 0,
    solution: '1. $924 - 700 = 224$\n2. $224 - 30 = 194$\n3. $194 - 5 = 189$\n\nResult: **189**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $863 - 857$ mentally.',
    options: ['6', '7', '5', '8'],
    answer: 0,
    solution: 'Distance between 857 and 863 is $63 - 57 = 6$.\n\nResult: **6**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    question: 'Calculate $437 - 77$ mentally.',
    options: ['360', '350', '370', '340'],
    answer: 0,
    solution: '1. $437 - 37 = 400$\n2. Subtract the remaining 40: $400 - 40 = 360$\n\nResult: **360**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    question: 'Calculate $573 - 498$ mentally.',
    options: ['75', '85', '65', '73'],
    answer: 0,
    solution: '1. $573 - 500 = 73$\n2. Add 2 back (since 498 is $500 - 2$): $73 + 2 = 75$\n\nResult: **75**'
  },

  // 1B - Multiplication and Division
  // Q3: Mental Multiplications
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Multiplication and division',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $50 \\times 2 \\times 7$ mentally.',
    options: ['700', '350', '1400', '70'],
    answer: 0,
    solution: '1. Group $50 \\times 2 = 100$\n2. $100 \\times 7 = 700$\n\nResult: **700**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Multiplication and division',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $25 \\times 64 \\times 4$ mentally.',
    options: ['6400', '1600', '3200', '640'],
    answer: 0,
    solution: '1. Group $25 \\times 4 = 100$\n2. $100 \\times 64 = 6400$\n\nResult: **6400**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Multiplication and division',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $1 \\times 45 \\times 20$ mentally.',
    options: ['900', '450', '1800', '90'],
    answer: 0,
    solution: '1. Multiplying by 1 doesn\'t change the value.\n2. $45 \\times 2 = 90$\n3. So $45 \\times 20 = 900$\n\nResult: **900**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Multiplication and division',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $2 \\times 9 \\times 5 \\times 4$ mentally.',
    options: ['360', '180', '720', '36'],
    answer: 0,
    solution: '1. Group $2 \\times 5 = 10$\n2. Group $9 \\times 4 = 36$\n3. $10 \\times 36 = 360$\n\nResult: **360**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Multiplication and division',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $2 \\times 83 \\times 5$ mentally.',
    options: ['830', '415', '1660', '83'],
    answer: 0,
    solution: '1. Group $2 \\times 5 = 10$\n2. $10 \\times 83 = 830$\n\nResult: **830**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Multiplication and division',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $4 \\times 5 \\times 60$ mentally.',
    options: ['1200', '600', '2400', '120'],
    answer: 0,
    solution: '1. $4 \\times 5 = 20$\n2. $20 \\times 60 = 1200$\n\nResult: **1200**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Multiplication and division',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $8 \\times 5 \\times 10 \\times 2$ mentally.',
    options: ['800', '400', '1600', '80'],
    answer: 0,
    solution: '1. Group $5 \\times 2 = 10$\n2. $8 \\times 10 \\times 10 = 800$\n\nResult: **800**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Multiplication and division',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $20 \\times 39 \\times 5$ mentally.',
    options: ['3900', '1950', '7800', '390'],
    answer: 0,
    solution: '1. Group $20 \\times 5 = 100$\n2. $100 \\times 39 = 3900$\n\nResult: **3900**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Multiplication and division',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'easy',
    isManual: true,
    question: 'Calculate $17 \\times 8 \\times 0$ mentally.',
    options: ['0', '136', '1', '178'],
    answer: 0,
    solution: 'Any number multiplied by 0 is always 0.\n\nResult: **0**'
  },

  // Word Problems
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    question: 'Lake Baikal has an area of $31,722 \\text{ km}^2$. Lake Michigan has an area of $58,030 \\text{ km}^2$. How much larger is Lake Michigan?',
    options: ['$26,308 \\text{ km}^2$', '$27,308 \\text{ km}^2$', '$25,308 \\text{ km}^2$', '$26,208 \\text{ km}^2$'],
    answer: 0,
    solution: 'To find the difference:\n$58,030 - 31,722$\n1. $58,030 - 31,000 = 27,030$\n2. $27,030 - 700 = 26,330$\n3. $26,330 - 22 = 26,308$\n\nResult: **$26,308 \\text{ km}^2$**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    question: 'Find the missing digits (*) in this calculation:\n```\n  2 3 1\n  2 6 *\n+ 1 * 6\n-------\n* 3 1\n```\nWhat is the total sum?',
    options: ['631', '731', '531', '831'],
    answer: 0,
    solution: 'Looking at the units column:\n$1 + * + 6 = 1 + 10n$\n$7 + * = 11 \\Rightarrow * = 4$ (Units digit of 264 is 4)\n\nLooking at the tens column (with carry 1):\n$3 + 6 + * + 1 = 3 + 10n$\n$10 + * = 13 \\Rightarrow * = 3$ (Tens digit of 136 is 3)\n\nLooking at the hundreds column (with carry 1):\n$2 + 2 + 1 + 1 = 6$\nSo the final sum is **631**.'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    question: 'Find the missing digits (*) in this calculation:\n```\n  * * *\n  6 3 7\n+ 5 6 7\n-------\n* 0 4 7\n```\nWhat is the top 3-digit number?',
    options: ['843', '743', '943', '833'],
    answer: 0,
    solution: 'Let the top number be $ABC$.\n$ABC + 637 + 567 = X047$\n1. $637 + 567 = 1204$\n2. $ABC + 1204 = X047$\n3. Looking at units: $C + 4 = 7 \\Rightarrow C = 3$\n4. Looking at tens: $B + 0 = 4 \\Rightarrow B = 4$\n5. Looking at hundreds: $A + 2 = 10 \\Rightarrow A = 8$\n6. $843 + 1204 = 2047$\n\nThe top number is **843**.'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Multiplication and division',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    question: 'Find the missing digits (*) in this multiplication:\n```\n    * 7 *\n  x     9\n --------\n  3 3 * 4\n```\nWhat is the 3-digit number being multiplied?',
    options: ['376', '374', '378', '276'],
    answer: 0,
    solution: '1. Units: $* \\times 9 = \\dots 4$. Only $6 \\times 9 = 54$ works. So units digit is 6.\n2. Carry 5 to tens column.\n3. Tens: $7 \\times 9 + 5 = 63 + 5 = 68$. So the missing digit in the result is 8.\n4. Carry 6 to hundreds column.\n5. Hundreds: $* \\times 9 + 6 = 33 \\Rightarrow * \\times 9 = 27 \\Rightarrow * = 3$.\n\nThe 3-digit number is **376**.'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    question: 'There are $4,125$ cats in Meowtown and $3,842$ in Purrville. What is the combined cat population?',
    options: ['7,967', '8,067', '7,867', '7,977'],
    answer: 0,
    solution: 'Combined population means addition:\n$4,125 + 3,842$\n1. $4,000 + 3,000 = 7,000$\n2. $125 + 842 = 967$\n3. Total = $7,967$\n\nResult: **7,967**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    question: 'A library has $3,450$ books. $1,920$ of them are fiction. How many non-fiction books are there?',
    options: ['1,530', '1,430', '1,630', '1,520'],
    answer: 0,
    solution: 'Subtract fiction from total:\n$3,450 - 1,920$\n1. $3,450 - 1,000 = 2,450$\n2. $2,450 - 900 = 1,550$\n3. $1,550 - 20 = 1,530$\n\nResult: **1,530**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Multiplication and division',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    question: 'Six hundred and forty-eight candies are shared among $24$ students. How many candies does each student get?',
    options: ['27', '26', '28', '25'],
    answer: 0,
    solution: 'Divide total candies by students:\n$648 \\div 24$\n1. $24 \\times 20 = 480$\n2. $648 - 480 = 168$\n3. $24 \\times 7 = 168$\n4. Total = $20 + 7 = 27$\n\nResult: **27**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'hard',
    isManual: true,
    question: 'A chess club has $120$ members. There are $20$ more adults than children. How many adults are there?',
    options: ['70', '60', '80', '75'],
    answer: 0,
    solution: '1. Let children $= x$\n2. Adults $= x + 20$\n3. Total: $x + (x + 20) = 120$\n4. $2x + 20 = 120 \\Rightarrow 2x = 100 \\Rightarrow x = 50$\n5. Adults $= 50 + 20 = 70$\n\nResult: **70**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Multiplication and division',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    question: '5,000 oranges are packed into boxes of $80$. How many boxes are needed?',
    options: ['63', '62', '64', '65'],
    answer: 0,
    solution: 'Divide total oranges by box size:\n$5,000 \\div 80 = 500 \\div 8$\n1. $500 \\div 8 = 62.5$\n2. Since we need to hold ALL oranges, we must round up to the next whole box.\n3. **63** boxes are required.\n\nResult: **63**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1a',
    topicCode: '1A',
    topicTitle: 'Addition and subtraction',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    question: 'A gym started with $95$ members. $42$ left and $35$ joined. How many members are there now?',
    options: ['88', '78', '98', '85'],
    answer: 0,
    solution: '1. Initial: $95$\n2. Left: $95 - 42 = 53$\n3. Joined: $53 + 35 = 88$\n\nResult: **88**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Multiplication and division',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    question: 'A farmer sold $420$ trays of eggs. Each tray weighs $12$ kg. What was the total weight?',
    options: ['5,040 kg', '4,040 kg', '6,040 kg', '5,140 kg'],
    answer: 0,
    solution: 'Multiply trays by weight:\n$420 \\times 12$\n1. $420 \\times 10 = 4,200$\n2. $420 \\times 2 = 840$\n3. Total $= 4,200 + 840 = 5,040$\n\nResult: **5,040 kg**'
  },
  {
    chapterId: 'y8-1',
    chapterTitle: 'Chapter 1: Whole Numbers',
    topicId: 'y8-1b',
    topicCode: '1B',
    topicTitle: 'Multiplication and division',
    year: 'Year 8',
    type: 'multiple_choice',
    difficulty: 'medium',
    isManual: true,
    question: 'An estate of $80$ hectares has $4,800$ trees. How many trees are there per hectare?',
    options: ['60', '50', '70', '65'],
    answer: 0,
    solution: 'Divide total trees by area:\n$4,800 \\div 80 = 480 \\div 8 = 60$\n\nResult: **60**'
  }
];

export const importYear8Ch1V2 = async (forceReset = false) => {
  console.log('[Ch1 Year 8 v2 Import] STARTING PHYSICAL SYNC...');
  let importedCount = 0;
  try {
    if (forceReset) {
      const qSnap = await db.collection('questions').where('chapterId', '==', 'y8-1').get();
      const batch = db.batch();
      qSnap.forEach(doc => batch.delete(doc.ref));
      await batch.commit();
    }
    
    for (const q of allQuestions) {
        await db.collection('questions').add(q);
        importedCount++;
    }
  } catch (error) { console.error(error); throw error; }
  return importedCount;
};
