import { db } from '../firebase/config.js';
import { collection, addDoc, getDocs, query, where } from 'firebase/firestore';

const allQuestions = [
  // SECTION 1: Simplify by collecting like terms
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3a',
    topicCode: '3A',
    topicTitle: 'Collecting like terms',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Simplify the expression: 4x + 9x',
    answer: '13x',
    solution: '4x + 9x = (4 + 9)x = 13x',
    difficulty: 'easy',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3a',
    topicCode: '3A',
    topicTitle: 'Collecting like terms',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Simplify the expression: 5p³q - 9p³q + 11p³q',
    answer: '7p³q',
    solution: '(5 - 9 + 11)p³q = 7p³q',
    difficulty: 'medium',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3a',
    topicCode: '3A',
    topicTitle: 'Collecting like terms',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Simplify the expression: ab - 2ab² - 6ab + ab²',
    answer: '-5ab - ab²',
    solution: '(ab - 6ab) + (-2ab² + ab²) = -5ab - ab²',
    difficulty: 'hard',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3a',
    topicCode: '3A',
    topicTitle: 'Collecting like terms',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Simplify the expression: 8x³y - 2x²y + 12x³y - 8x²y',
    answer: '20x³y - 10x²y',
    solution: '(8x³y + 12x³y) + (-2x²y - 8x²y) = 20x³y - 10x²y',
    difficulty: 'hard',
    isManual: true
  },

  // SECTION 2: Expand each expression
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Expand the expression: -2(a + 4)',
    answer: '-2a - 8',
    solution: '-2 * a + (-2) * 4 = -2a - 8',
    difficulty: 'easy',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Expand the expression: -3(b + 6)',
    answer: '-3b - 18',
    solution: '-3 * b + (-3) * 6 = -3b - 18',
    difficulty: 'easy',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Expand the expression: -4(3b - 5)',
    answer: '-12b + 20',
    solution: '-4 * 3b - (-4) * 5 = -12b + 20',
    difficulty: 'medium',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Expand the expression: -5(4b - 7)',
    answer: '-20b + 35',
    solution: '-5 * 4b - (-5) * 7 = -20b + 35',
    difficulty: 'medium',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'multiple_choice',
    question: 'Expand the expression: 2/3(12p + 6)',
    options: ['8p + 4', '12p + 4', '8p + 6', '24p + 12'],
    answer: '0',
    solution: '(2/3 * 12p) + (2/3 * 6) = 8p + 4',
    difficulty: 'medium',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'multiple_choice',
    question: 'Expand the expression: -1/4(16p - 20)',
    options: ['-4p + 5', '4p - 5', '-4p - 5', '-16p + 20'],
    answer: '0',
    solution: '(-1/4 * 16p) - (-1/4 * 20) = -4p + 5',
    difficulty: 'medium',
    isManual: true
  },

  // SECTION 3: Expand (Variable multiplication)
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Expand the expression: d(d - 9)',
    answer: 'd² - 9d',
    solution: 'd * d - d * 9 = d² - 9d',
    difficulty: 'medium',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Expand the expression: e(3e + 1)',
    answer: '3e² + e',
    solution: 'e * 3e + e * 1 = 3e² + e',
    difficulty: 'medium',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Expand the expression: f(5f + 6)',
    answer: '5f² + 6f',
    solution: 'f * 5f + f * 6 = 5f² + 6f',
    difficulty: 'medium',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Expand the expression: -2m(5m - 4)',
    answer: '-10m² + 8m',
    solution: '-2m * 5m - (-2m) * 4 = -10m² + 8m',
    difficulty: 'hard',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Expand the expression: -3n(5n + 7)',
    answer: '-15n² - 21n',
    solution: '-3n * 5n + (-3n) * 7 = -15n² - 21n',
    difficulty: 'hard',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Expand the expression: 2p(3q - 5r)',
    answer: '6pq - 10pr',
    solution: '2p * 3q - 2p * 5r = 6pq - 10pr',
    difficulty: 'hard',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Expand the expression: -3x(2x + 5y)',
    answer: '-6x² - 15xy',
    solution: '-3x * 2x + (-3x) * 5y = -6x² - 15xy',
    difficulty: 'hard',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Expand the expression: -2z(3z - 4y)',
    answer: '-6z² + 8zy',
    solution: '-2z * 3z - (-2z) * 4y = -6z² + 8zy',
    difficulty: 'hard',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Expand the expression: 2a(3 + 4ab)',
    answer: '6a + 8a²b',
    solution: '2a * 3 + 2a * 4ab = 6a + 8a²b',
    difficulty: 'hard',
    isManual: true
  },

  // SECTION 4: Expand and collect like terms
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Expand and collect like terms: 2(c + 7) - 9',
    answer: '2c + 5',
    solution: '(2c + 14) - 9 = 2c + 5',
    difficulty: 'medium',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Expand and collect like terms: 4(h + 1) + 3h',
    answer: '7h + 4',
    solution: '(4h + 4) + 3h = 7h + 4',
    difficulty: 'medium',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Expand and collect like terms: 4(1 - 3q) + 15q',
    answer: '3q + 4',
    solution: '(4 - 12q) + 15q = 3q + 4',
    difficulty: 'medium',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Expand and collect like terms: 2a(3a + 2b) - 6a²',
    answer: '4ab',
    solution: '(6a² + 4ab) - 6a² = 4ab',
    difficulty: 'medium',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'multiple_choice',
    question: 'Expand and collect like terms: 5/6(x - 4) + 3x/4',
    options: ['19x/12 - 10/3', '15x/12 - 4', '19x/12 - 20/6', 'x/2 - 3'],
    answer: '0',
    solution: '5x/6 - 20/6 + 3x/4 = (10x/12 + 9x/12) - 10/3 = 19x/12 - 10/3',
    difficulty: 'hard',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Expand and collect like terms: 5(b - 2) - 4(b + 3)',
    answer: 'b - 22',
    solution: '(5b - 10) - (4b + 12) = 5b - 10 - 4b - 12 = b - 22',
    difficulty: 'medium',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Expand and collect like terms: 4y(3y - 5) + 3(3y - 5)',
    answer: '12y² - 11y - 15',
    solution: '12y² - 20y + 9y - 15 = 12y² - 11y - 15',
    difficulty: 'medium',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Expand and collect like terms: 2p(3p + 1) - 4(2p + 1)',
    answer: '6p² - 6p - 4',
    solution: '6p² + 2p - 8p - 4 = 6p² - 6p - 4',
    difficulty: 'medium',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'multiple_choice',
    question: 'Expand: (m + 4)(m - 5)',
    options: ['m² - m - 20', 'm² + m - 20', 'm² - 20', 'm² - 9m - 20'],
    answer: '0',
    solution: 'm² - 5m + 4m - 20 = m² - m - 20',
    difficulty: 'medium',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'multiple_choice',
    question: 'Expand: (6x - 5)(x + 2)',
    options: ['6x² + 7x - 10', '6x² - 7x - 10', '6x² + 12x - 10', '6x² + 17x - 10'],
    answer: '0',
    solution: '6x² + 12x - 5x - 10 = 6x² + 7x - 10',
    difficulty: 'hard',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'multiple_choice',
    question: 'Expand: (7x - 1)(x - 5)',
    options: ['7x² - 36x + 5', '7x² - 34x + 5', '7x² - 36x - 5', '7x² + 36x + 5'],
    answer: '0',
    solution: '7x² - 35x - x + 5 = 7x² - 36x + 5',
    difficulty: 'hard',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3b',
    topicCode: '3B',
    topicTitle: 'Expansion',
    year: 'Year 10',
    type: 'multiple_choice',
    question: 'Expand: (m + 3n)(2m + n)',
    options: ['2m² + 7mn + 3n²', '2m² + 6mn + 3n²', '2m² + 3n²', '2m² + mn + 3n²'],
    answer: '0',
    solution: 'm(2m) + m(n) + 3n(2m) + 3n(n) = 2m² + mn + 6mn + 3n² = 2m² + 7mn + 3n²',
    difficulty: 'hard',
    isManual: true
  },

  // SECTION 5: Solve each equation
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3c',
    topicCode: '3C',
    topicTitle: 'Solving equations',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Solve for x: 7x - 4 = 17',
    answer: '3',
    solution: '7x = 21 => x = 3',
    difficulty: 'easy',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3c',
    topicCode: '3C',
    topicTitle: 'Solving equations',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Solve for x: 3x = 25 - 2x',
    answer: '5',
    solution: '5x = 25 => x = 5',
    difficulty: 'medium',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3c',
    topicCode: '3C',
    topicTitle: 'Solving equations',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Solve for x: 7x = 18 - 2x',
    answer: '2',
    solution: '9x = 18 => x = 2',
    difficulty: 'medium',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3c',
    topicCode: '3C',
    topicTitle: 'Solving equations',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Solve for x: x/3 + 2 = 7',
    answer: '15',
    solution: 'x/3 = 5 => x = 15',
    difficulty: 'medium',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3c',
    topicCode: '3C',
    topicTitle: 'Solving equations',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Solve for x: 3x/2 + 2 = 8',
    answer: '4',
    solution: '3x/2 = 6 => 3x = 12 => x = 4',
    difficulty: 'medium',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3c',
    topicCode: '3C',
    topicTitle: 'Solving equations',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Solve for x: 3x - 7 = x + 1',
    answer: '4',
    solution: '2x = 8 => x = 4',
    difficulty: 'medium',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3c',
    topicCode: '3C',
    topicTitle: 'Solving equations',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Solve for x: 7x/2 + 2x = 12 - x',
    answer: '24/13',
    solution: '3.5x + 2x + x = 12 => 6.5x = 12 => 13x/2 = 12 => 13x = 24 => x = 24/13',
    difficulty: 'hard',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3c',
    topicCode: '3C',
    topicTitle: 'Solving equations',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Solve for x: x/2 + x/5 = 14',
    answer: '20',
    solution: '5x/10 + 2x/10 = 14 => 7x/10 = 14 => 7x = 140 => x = 20',
    difficulty: 'hard',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3c',
    topicCode: '3C',
    topicTitle: 'Solving equations',
    year: 'Year 10',
    type: 'short_answer',
    question: 'Solve for x: 3(2x - 1) + 3x = 15',
    answer: '2',
    solution: '6x - 3 + 3x = 15 => 9x = 18 => x = 2',
    difficulty: 'hard',
    isManual: true
  },

  // SECTION 6: Inequalities (Sketching/Drawing)
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3d',
    topicCode: '3D',
    topicTitle: 'Inequalities',
    year: 'Year 10',
    type: 'graph_sketch',
    question: 'Solve and graph on a number line: x + 1 > 5',
    answer: 'x > 4',
    solution: 'x > 5 - 1 => x > 4. Draw an open circle at 4 and an arrow pointing to the right.',
    difficulty: 'medium',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3d',
    topicCode: '3D',
    topicTitle: 'Inequalities',
    year: 'Year 10',
    type: 'graph_sketch',
    question: 'Solve and graph on a number line: 2x - 1 < 6',
    answer: 'x < 3.5',
    solution: '2x < 7 => x < 3.5. Draw an open circle at 3.5 and arrow left.',
    difficulty: 'medium',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3d',
    topicCode: '3D',
    topicTitle: 'Inequalities',
    year: 'Year 10',
    type: 'graph_sketch',
    question: 'Solve and graph on a number line: (x + 1)/2 ≥ -4',
    answer: 'x ≥ -9',
    solution: 'x + 1 ≥ -8 => x ≥ -9. Draw solid circle at -9 and arrow right.',
    difficulty: 'medium',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3d',
    topicCode: '3D',
    topicTitle: 'Inequalities',
    year: 'Year 10',
    type: 'graph_sketch',
    question: 'Solve and graph on a number line: -2x + 1 ≤ 6',
    answer: 'x ≥ -2.5',
    solution: '-2x ≤ 5 => x ≥ -5/2 => x ≥ -2.5. Draw a solid circle at -2.5 and an arrow pointing to the right.',
    difficulty: 'hard',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3d',
    topicCode: '3D',
    topicTitle: 'Inequalities',
    year: 'Year 10',
    type: 'graph_sketch',
    question: 'Solve and graph on a number line: 4 - 7x ≥ 6',
    answer: 'x ≤ -2/7',
    solution: '-7x ≥ 2 => x ≤ -2/7. Draw solid circle at -2/7 and arrow left.',
    difficulty: 'hard',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3d',
    topicCode: '3D',
    topicTitle: 'Inequalities',
    year: 'Year 10',
    type: 'graph_sketch',
    question: 'Solve and graph on a number line: (-3x + 2)/6 ≤ 1',
    answer: 'x ≥ -4/3',
    solution: '-3x + 2 ≤ 6 => -3x ≤ 4 => x ≥ -4/3. Draw solid circle and arrow right.',
    difficulty: 'hard',
    isManual: true
  },
  {
    chapterId: 'y10-3',
    chapterTitle: 'Chapter 3: Algebraic Expressions and Equations',
    topicId: 'y10-3d',
    topicCode: '3D',
    topicTitle: 'Inequalities',
    year: 'Year 10',
    type: 'graph_sketch',
    question: 'Solve and graph on a number line: (2x - 1)/3 ≤ (x + 1)/4',
    answer: 'x ≤ 1.4',
    solution: '4(2x - 1) ≤ 3(x + 1) => 8x - 4 ≤ 3x + 3 => 5x ≤ 7 => x ≤ 1.4. Draw a solid circle at 1.4 and arrow left.',
    difficulty: 'hard',
    isManual: true
  }
];

export const importYear10Ch3 = async () => {
  console.log('Starting Year 10 Chapter 3 FULL question import...');
  let importedCount = 0;
  
  for (const q of allQuestions) {
    try {
      const qRef = collection(db, 'questions');
      const dupQuery = query(qRef, where('question', '==', q.question));
      const dupSnap = await getDocs(dupQuery);
      
      if (dupSnap.empty) {
        await addDoc(collection(db, 'questions'), q);
        importedCount++;
      }
    } catch (error) {
      console.error('Error importing question:', error);
    }
  }
  
  console.log(`Successfully imported ${importedCount} Year 10 Ch 3 questions.`);
  return importedCount;
};
