// NSW HSC 2025 School Rankings (Overall Band 6 success rate)
// Source: Matrix Education 2025 HSC results (https://www.matrix.edu.au/2025-high-school-rankings/)
// change: positive = moved up, negative = moved down, null = new entry
export const NSW_SCHOOL_RANKINGS = [
  { rank: 1,   school: "North Sydney Boys High School",                                    change: 0 },
  { rank: 2,   school: "James Ruse Agricultural High School",                              change: 0 },
  { rank: 3,   school: "Sydney Grammar School",                                            change: 0 },
  { rank: 4,   school: "North Sydney Girls High School",                                   change: 4 },
  { rank: 5,   school: "Normanhurst Boys High School",                                     change: -1 },
  { rank: 6,   school: "Sydney Boys High School",                                          change: 3 },
  { rank: 7,   school: "Baulkham Hills High School",                                       change: -1 },
  { rank: 8,   school: "Hornsby Girls High School",                                        change: -1 },
  { rank: 9,   school: "St Aloysius' College",                                             change: 5 },
  { rank: 10,  school: "Reddam House",                                                     change: -5 },
  { rank: 11,  school: "Abbotsleigh",                                                      change: -1 },
  { rank: 12,  school: "Ascham School",                                                    change: 11 },
  { rank: 13,  school: "Sydney Girls High School",                                         change: 4 },
  { rank: 14,  school: "Ravenswood School for Girls",                                      change: 26 },
  { rank: 15,  school: "Conservatorium High School",                                       change: null },
  { rank: 16,  school: "Presbyterian Ladies' College – Sydney",                            change: 19 },
  { rank: 17,  school: "Penrith Selective High School",                                    change: 13 },
  { rank: 18,  school: "Pymble Ladies' College",                                           change: 3 },
  { rank: 19,  school: "Roseville College",                                                change: 6 },
  { rank: 20,  school: "Fort Street High School",                                          change: 8 },
  { rank: 21,  school: "SCEGGS Darlinghurst",                                              change: -5 },
  { rank: 22,  school: "Merewether High School",                                           change: 7 },
  { rank: 23,  school: "Al-Faisal College",                                                change: -1 },
  { rank: 24,  school: "Meriden School",                                                   change: -13 },
  { rank: 25,  school: "Northern Beaches Secondary College Manly Campus",                  change: -10 },
  { rank: 26,  school: "Girraween High School",                                            change: 6 },
  { rank: 27,  school: "SHORE – Sydney Church of England Grammar School",                  change: -1 },
  { rank: 28,  school: "Alpha Omega Senior College",                                       change: -9 },
  { rank: 29,  school: "Knox Grammar School",                                              change: -11 },
  { rank: 30,  school: "Loreto Kirribilli",                                                change: -10 },
  { rank: 31,  school: "Caringbah High School",                                            change: 49 },
  { rank: 32,  school: "Queenwood",                                                        change: 4 },
  { rank: 33,  school: "Gosford High School",                                              change: 20 },
  { rank: 34,  school: "Kincoppal – Rose Bay School of the Sacred Heart",                  change: 34 },
  { rank: 35,  school: "Wenona School",                                                    change: -8 },
  { rank: 36,  school: "Kambala",                                                          change: -24 },
  { rank: 37,  school: "Northholm Grammar School",                                         change: -6 },
  { rank: 38,  school: "St Catherine's School – Waverley",                                 change: -14 },
  { rank: 39,  school: "Tara Anglican School for Girls",                                   change: 27 },
  { rank: 40,  school: "Loreto Normanhurst",                                               change: 23 },
  { rank: 41,  school: "Al Noori Muslim School",                                           change: -2 },
  { rank: 42,  school: "The King's School",                                                change: -8 },
  { rank: 43,  school: "Hurlstone Agricultural High School",                               change: 1 },
  { rank: 44,  school: "Parramatta Marist High School",                                    change: 15 },
  { rank: 45,  school: "St George Girls High School",                                      change: -7 },
  { rank: 46,  school: "Sydney Tech High School",                                          change: 5 },
  { rank: 47,  school: "Cranbrook School",                                                 change: -4 },
  { rank: 48,  school: "Brigidine College St Ives",                                        change: 47 },
  { rank: 49,  school: "Monte Sant' Angelo Mercy College",                                 change: 16 },
  { rank: 50,  school: "Barker College",                                                   change: -3 },
  { rank: 51,  school: "Emanuel School",                                                   change: -9 },
  { rank: 52,  school: "Newington College",                                                change: 75 },
  { rank: 53,  school: "Brigidine College Randwick",                                       change: 14 },
  { rank: 54,  school: "Tangara School for Girls",                                         change: 33 },
  { rank: 55,  school: "The Illawarra Grammar School",                                     change: null },
  { rank: 56,  school: "Frensham School",                                                  change: -6 },
  { rank: 57,  school: "Willoughby Girls High School",                                     change: -2 },
  { rank: 58,  school: "MLC School",                                                       change: 81 },
  { rank: 59,  school: "Saint Ignatius' College",                                          change: 12 },
  { rank: 60,  school: "Moriah College",                                                   change: -27 },
  { rank: 61,  school: "Newcastle Grammar School",                                         change: 23 },
  { rank: 62,  school: "Smiths Hill High School",                                          change: -8 },
  { rank: 63,  school: "Northern Beaches Secondary College Balgowlah Boys Campus",         change: 1 },
  { rank: 64,  school: "Chatswood High School",                                            change: -6 },
  { rank: 65,  school: "St Luke's Grammar School",                                         change: -20 },
  { rank: 66,  school: "St Vincent's College",                                             change: 19 },
  { rank: 67,  school: "St Patrick's College, Strathfield",                                change: 22 },
  { rank: 68,  school: "Masada College",                                                   change: -31 },
  { rank: 69,  school: "Marist Catholic College North Shore",                              change: 7 },
  { rank: 70,  school: "Danebank – An Anglican School for Girls",                          change: -18 },
  { rank: 71,  school: "St Augustine's College Sydney",                                    change: -9 },
  { rank: 72,  school: "St Joseph's College (Hunters Hill)",                               change: 16 },
  { rank: 73,  school: "Cherrybrook Technology High School",                               change: 21 },
  { rank: 74,  school: "St Andrew's Cathedral School",                                     change: 62 },
  { rank: 75,  school: "Cheltenham Girls High School",                                     change: -18 },
  { rank: 76,  school: "Mount St Benedict College",                                        change: 1 },
  { rank: 77,  school: "St Clare's College",                                               change: -29 },
  { rank: 78,  school: "Sefton High School",                                               change: 51 },
  { rank: 79,  school: "Santa Sabina College",                                             change: 7 },
  { rank: 80,  school: "Bethany College",                                                  change: 2 },
  { rank: 81,  school: "The Scots College",                                                change: -40 },
  { rank: 82,  school: "Pittwater House Schools",                                          change: -33 },
  { rank: 83,  school: "Waverley College",                                                 change: 32 },
  { rank: 84,  school: "International Grammar School",                                     change: -5 },
  { rank: 85,  school: "Georges River Grammar",                                            change: 114 },
  { rank: 86,  school: "Lindfield Learning Village",                                       change: null },
  { rank: 87,  school: "Oxley College",                                                    change: null },
  { rank: 88,  school: "St Mark's Coptic Orthodox College",                                change: null },
  { rank: 89,  school: "Killarney Heights High School",                                    change: 21 },
  { rank: 90,  school: "St Spyridon College",                                              change: -9 },
  { rank: 91,  school: "Central Coast Grammar School",                                     change: -45 },
  { rank: 92,  school: "Rose Bay Secondary College",                                       change: 17 },
  { rank: 93,  school: "Stella Maris College",                                             change: 3 },
  { rank: 94,  school: "Parramatta High School",                                           change: 5 },
  { rank: 95,  school: "Our Lady of Mercy College Parramatta",                             change: -25 },
  { rank: 96,  school: "Cammeraygal High School",                                          change: 25 },
  { rank: 97,  school: "Newtown High School of Performing Arts",                           change: -41 },
  { rank: 98,  school: "Covenant Christian School",                                        change: 35 },
  { rank: 99,  school: "Marist Catholic College Penshurst",                                change: -2 },
  { rank: 100, school: "Epping Boys High School",                                          change: -40 },
  { rank: 101, school: "Mercy Catholic College",                                           change: 56 },
  { rank: 102, school: "SCECGS Redlands",                                                  change: 29 },
  { rank: 103, school: "St Ursula's College",                                              change: -11 },
  { rank: 104, school: "Redeemer Baptist School",                                          change: null },
  { rank: 105, school: "St George Christian School",                                       change: 2 },
  { rank: 106, school: "St Mary and St Mina's Coptic Orthodox College",                    change: null },
  { rank: 107, school: "Aquinas Catholic College",                                         change: 68 },
  { rank: 108, school: "Arden Anglican School",                                            change: -35 },
  { rank: 109, school: "St Mary's Cathedral College",                                      change: 17 },
  { rank: 110, school: "Christian Brothers' High School Lewisham",                         change: 32 },
  { rank: 111, school: "Macarthur Anglican School",                                        change: -33 },
  { rank: 112, school: "Amity College, Prestons",                                          change: -1 },
  { rank: 113, school: "Northern Beaches Secondary College Mackellar Girls Campus",        change: 5 },
  { rank: 114, school: "Strathfield Girls High School",                                    change: -12 },
  { rank: 115, school: "Oxford Falls Grammar School",                                      change: 36 },
  { rank: 116, school: "St John Bosco College",                                            change: 21 },
  { rank: 117, school: "Trinity Grammar School",                                           change: null },
  { rank: 118, school: "Carlingford High School",                                          change: -46 },
  { rank: 119, school: "Castle Hill High School",                                          change: -13 },
  { rank: 120, school: "Freeman Catholic College",                                         change: 43 },
  { rank: 121, school: "Al-Faisal College – Liverpool",                                    change: null },
  { rank: 122, school: "St Philip's Christian College – Waratah",                          change: -2 },
  { rank: 123, school: "St Columba Anglican School",                                       change: -18 },
  { rank: 124, school: "Rosebank College",                                                 change: 25 },
  { rank: 125, school: "Marist College Eastwood",                                          change: -11 },
  { rank: 126, school: "Sydney Secondary College Blackwattle Bay Campus",                  change: null },
  { rank: 127, school: "St Scholastica's College Glebe Point",                             change: -3 },
  { rank: 128, school: "Marcellin College",                                                change: -15 },
  { rank: 129, school: "The Hills Grammar School",                                         change: -60 },
  { rank: 130, school: "Marist College Kogarah",                                           change: 30 },
  { rank: 131, school: "Emmanuel Anglican College",                                        change: null },
  { rank: 132, school: "St Charbel's College",                                             change: null },
  { rank: 133, school: "St Pius X College",                                                change: null },
  { rank: 134, school: "Domremy Catholic College",                                         change: -22 },
  { rank: 135, school: "St Patrick's College Sutherland",                                  change: null },
  { rank: 136, school: "Xavier Catholic College Ballina",                                  change: 5 },
  { rank: 137, school: "Oakhill College",                                                  change: null },
  { rank: 138, school: "Northern Beaches Secondary College Freshwater Senior Campus",      change: -22 },
  { rank: 139, school: "Wollemi College",                                                  change: null },
  { rank: 140, school: "William Clarke College",                                           change: -18 },
  { rank: 141, school: "Killara High School",                                              change: -51 },
  { rank: 142, school: "Ryde Secondary College",                                           change: -44 },
  { rank: 143, school: "Burwood Girls High School",                                        change: -39 },
  { rank: 144, school: "Dulwich High School of Visual Arts and Design",                    change: null },
  { rank: 147, school: "St Patrick's Marist College",                                      change: null },
  { rank: 148, school: "Asquith Girls High School",                                        change: null },
  { rank: 149, school: "Cerdon College",                                                   change: 30 },
];

// Fuzzy match: find a school's rank from its name (case-insensitive partial match)
export const findSchoolRank = (schoolName) => {
  if (!schoolName) return null;
  const q = schoolName.toLowerCase().trim();
  const exact = NSW_SCHOOL_RANKINGS.find((s) => s.school.toLowerCase() === q);
  if (exact) return exact.rank;
  const partial = NSW_SCHOOL_RANKINGS.find((s) => s.school.toLowerCase().includes(q) || q.includes(s.school.toLowerCase().split(' ').slice(0, 2).join(' ')));
  return partial ? partial.rank : null;
};
