// Year 10 Chapter 18: Statistics — ICE-EM Mathematics 10 (3ed), Chapter 18,
// Exercise 18E: "Interpreting the standard deviation" (pp.543-544). All
// questions converted to multiple_choice — every part of this exercise
// (including Q5's "add/multiply" constructions and Q6/Q7's "make up a list"
// prompts) has a single objectively correct/optimal answer once framed as
// "which of these options is correct", so nothing needed to stay
// teacher_review this time.
//
// Q5's three bar charts (i, ii, iii) are scanned diagrams whose exact bar
// heights can't be read back precisely from the extracted page image, so
// each is rebuilt as a self-consistent frequency distribution matching the
// described shape (uniform / bell-shaped / U-shaped) — same approach used
// for scanned diagrams throughout this chapter's other ICE-EM topics.

export const Y10_CH18E_ICEM_QUESTIONS = [
  // ---- Q1: mean and SD of three data sets, then compare ----
  {
    id: 'y10-18e-q1a',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'hard',
    timeLimit: 120,
    question: 'Find the mean and standard deviation of the data set:<div style="text-align:center;font-weight:600;margin:10px 0;max-width:600px;margin-left:auto;margin-right:auto">5, 6, 6, 7, 8, 9, 22</div>',
    opts: [
      'mean = 9.00, \\(\\sigma\\) = 5.45',
      'mean = 9.00, \\(\\sigma\\) = 29.71',
      'mean = 9.00, \\(\\sigma\\) = 5.89',
      'mean = 9.00, \\(\\sigma\\) = 4.55',
    ],
    a: 0,
    answer: '0',
    hint: 'Find the mean, then use \\(\\sigma = \\sqrt{\\dfrac{\\sum(x-\\bar{x})^2}{n}}\\) (or a calculator\'s statistics mode).',
    solution: 'mean = 63/7 = 9.00. Sum of squared deviations = 208. Variance = 208/7 ≈ 29.71. SD ≈ 5.45.',
    solutionSteps: [
      {
        explanation: 'Add the 7 values and divide by n = 7 to find the mean.',
        workingOut: '\\(\\bar{x} = \\dfrac{5+6+6+7+8+9+22}{7} = \\dfrac{63}{7} = 9.00\\)',
        graphData: null,
      },
      {
        explanation: 'Find each deviation from the mean and square it. Notice the outlier 22 is far from the mean, contributing a large squared deviation.',
        workingOut: '\\((5-9)^2=16,\\ (6-9)^2=9\\ (\\times 2),\\ (7-9)^2=4,\\ (8-9)^2=1,\\ (9-9)^2=0,\\ (22-9)^2=169\\)',
        graphData: null,
      },
      {
        explanation: 'Sum the squared deviations, then divide by n = 7 to get the variance.',
        workingOut: '\\(\\sum(x-\\bar{x})^2 = 16+18+4+1+0+169 = 208\\)\\\\ \\(\\sigma^2 = \\dfrac{208}{7} \\approx 29.71\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: take the square root of the variance.',
        workingOut: '\\(\\sigma = \\sqrt{29.71} \\approx 5.45\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },
  {
    id: 'y10-18e-q1b',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'hard',
    timeLimit: 120,
    question: 'Find the mean and standard deviation of the data set:<div style="text-align:center;font-weight:600;margin:10px 0;max-width:600px;margin-left:auto;margin-right:auto">11, 7, 8, 9, 8, 10, 10</div>',
    opts: [
      'mean = 9.00, \\(\\sigma\\) = 1.71',
      'mean = 9.00, \\(\\sigma\\) = 1.31',
      'mean = 9.00, \\(\\sigma\\) = 1.41',
      'mean = 9.14, \\(\\sigma\\) = 1.31',
    ],
    a: 1,
    answer: '1',
    hint: 'Find the mean, then use \\(\\sigma = \\sqrt{\\dfrac{\\sum(x-\\bar{x})^2}{n}}\\) (or a calculator\'s statistics mode).',
    solution: 'mean = 63/7 = 9.00. Sum of squared deviations = 12. Variance = 12/7 ≈ 1.71. SD ≈ 1.31.',
    solutionSteps: [
      {
        explanation: 'Add the 7 values and divide by n = 7 to find the mean. Notice this data set has the SAME mean (9.00) as the previous question, even though the values look quite different.',
        workingOut: '\\(\\bar{x} = \\dfrac{11+7+8+9+8+10+10}{7} = \\dfrac{63}{7} = 9.00\\)',
        graphData: null,
      },
      {
        explanation: 'Find each deviation from the mean and square it.',
        workingOut: '\\((11-9)^2=4,\\ (7-9)^2=4,\\ (8-9)^2=1\\ (\\times 2),\\ (9-9)^2=0,\\ (10-9)^2=1\\ (\\times 2)\\)',
        graphData: null,
      },
      {
        explanation: 'Sum the squared deviations, then divide by n = 7 to get the variance.',
        workingOut: '\\(\\sum(x-\\bar{x})^2 = 4+4+2+0+2 = 12\\)\\\\ \\(\\sigma^2 = \\dfrac{12}{7} \\approx 1.71\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: take the square root of the variance. This SD (1.31) is MUCH smaller than the previous question\'s (5.45) — this data set is far more tightly clustered around the same mean.',
        workingOut: '\\(\\sigma = \\sqrt{1.71} \\approx 1.31\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },
  {
    id: 'y10-18e-q1c',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'hard',
    timeLimit: 120,
    question: 'Find the mean and standard deviation of the data set:<div style="text-align:center;font-weight:600;margin:10px 0;max-width:600px;margin-left:auto;margin-right:auto">1, 3, 7, 9, 11, 15, 17</div>',
    opts: [
      'mean = 9.00, \\(\\sigma\\) = 6.45',
      'mean = 9.00, \\(\\sigma\\) = 29.71',
      'mean = 9.00, \\(\\sigma\\) = 5.45',
      'mean = 9.00, \\(\\sigma\\) = 5.89',
    ],
    a: 2,
    answer: '2',
    hint: 'Find the mean, then use \\(\\sigma = \\sqrt{\\dfrac{\\sum(x-\\bar{x})^2}{n}}\\) (or a calculator\'s statistics mode).',
    solution: 'mean = 63/7 = 9.00. Sum of squared deviations = 208. Variance = 208/7 ≈ 29.71. SD ≈ 5.45.',
    solutionSteps: [
      {
        explanation: 'Add the 7 values and divide by n = 7 to find the mean. This is the third data set in a row with mean 9.00.',
        workingOut: '\\(\\bar{x} = \\dfrac{1+3+7+9+11+15+17}{7} = \\dfrac{63}{7} = 9.00\\)',
        graphData: null,
      },
      {
        explanation: 'Find each deviation from the mean and square it.',
        workingOut: '\\((1-9)^2=64,\\ (3-9)^2=36,\\ (7-9)^2=4,\\ (9-9)^2=0,\\ (11-9)^2=4,\\ (15-9)^2=36,\\ (17-9)^2=64\\)',
        graphData: null,
      },
      {
        explanation: 'Sum the squared deviations, then divide by n = 7 to get the variance.',
        workingOut: '\\(\\sum(x-\\bar{x})^2 = 64+36+4+0+4+36+64 = 208\\)\\\\ \\(\\sigma^2 = \\dfrac{208}{7} \\approx 29.71\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: take the square root. Interesting result: this SD (5.45) is IDENTICAL to the first data set\'s, even though the actual values are completely different — both data sets happen to be spread out from the shared mean by the same overall amount.',
        workingOut: '\\(\\sigma = \\sqrt{29.71} \\approx 5.45\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },
  {
    id: 'y10-18e-q1compare',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'medium',
    timeLimit: 90,
    question:
      'Comparing the three data sets above:\n\n| Data set | Mean | \\(\\sigma\\) |\n|---|---|---|\n| a | 9.00 | 5.45 |\n| b | 9.00 | 1.31 |\n| c | 9.00 | 5.45 |\n\nWhich data set is the most consistent (most tightly clustered around the mean)?',
    opts: ['Data set a', 'Data set c', 'Data set b', '"a" and "c" are equally the most consistent'],
    a: 2,
    answer: '2',
    hint: 'The most consistent data set is the one with the SMALLEST standard deviation.',
    solution: 'All three share mean=9.00, but data set b has by far the smallest SD (1.31 vs 5.45), so it is the most consistent.',
    solutionSteps: [
      {
        explanation: 'All three data sets share exactly the same mean (9.00), so the mean alone cannot distinguish them — the standard deviation must be compared instead.',
        workingOut: '\\(\\bar{x}_a = \\bar{x}_b = \\bar{x}_c = 9.00\\)',
        graphData: null,
      },
      {
        explanation: 'Compare the three standard deviations.',
        workingOut: '\\(\\sigma_a \\approx 5.45, \\quad \\sigma_b \\approx 1.31, \\quad \\sigma_c \\approx 5.45\\)',
        graphData: null,
      },
      {
        explanation: 'Pitfall: data sets a and c share the SAME (larger) standard deviation as each other — this does not make them "jointly the most consistent"; it makes them jointly the LEAST consistent, since 5.45 is the larger value being compared.',
        workingOut: '\\(\\sigma_b = 1.31 < \\sigma_a = \\sigma_c = 5.45\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: data set b has the smallest standard deviation, so it is the most consistent (most tightly clustered around the shared mean).',
        workingOut: '\\(\\text{data set b}\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },

  // ---- Q2: intervals within 1 and 2 standard deviations ----
  {
    id: 'y10-18e-q2ai',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'medium',
    timeLimit: 90,
    question: 'The mean and standard deviation of a data set are given as \\(\\bar{x} = 35\\), \\(\\sigma = 2.5\\). Find the range of values that is within one standard deviation of the mean.',
    opts: ['30 to 40', '33.75 to 36.25', '37.5 to 42.5', '32.5 to 37.5'],
    a: 3,
    answer: '3',
    hint: 'One SD range: \\(\\bar{x} - \\sigma\\) to \\(\\bar{x} + \\sigma\\).',
    solution: 'One SD: 35±2.5 = 32.5 to 37.5.',
    solutionSteps: [
      {
        explanation: 'State the one-SD interval formula and the known values.',
        workingOut: '\\(\\bar{x} - \\sigma \\text{ to } \\bar{x} + \\sigma\\)',
        graphData: null,
      },
      {
        explanation: 'Calculate the lower bound.',
        workingOut: '\\(35 - 2.5 = 32.5\\)',
        graphData: null,
      },
      {
        explanation: 'Calculate the upper bound. Pitfall: halving \\(\\sigma\\) (giving the wrong distractor 33.75 to 36.25), or adding instead of subtracting for the lower bound, are common mistakes.',
        workingOut: '\\(35 + 2.5 = 37.5\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: the range within one standard deviation of the mean is 32.5 to 37.5.',
        workingOut: '\\([32.5, 37.5]\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },
  {
    id: 'y10-18e-q2aii',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'medium',
    timeLimit: 90,
    question: 'Using the same data set (\\(\\bar{x} = 35\\), \\(\\sigma = 2.5\\)), find the range of values that is within TWO standard deviations of the mean.',
    opts: ['25 to 45', '32.5 to 37.5', '27.5 to 42.5', '30 to 40'],
    a: 3,
    answer: '3',
    hint: 'Two SD range: \\(\\bar{x} - 2\\sigma\\) to \\(\\bar{x} + 2\\sigma\\).',
    solution: 'Two SD: 35±5 = 30 to 40.',
    solutionSteps: [
      {
        explanation: 'State the two-SD interval formula and calculate \\(2\\sigma\\) first.',
        workingOut: '\\(2\\sigma = 2 \\times 2.5 = 5\\)',
        graphData: null,
      },
      {
        explanation: 'Calculate the lower bound.',
        workingOut: '\\(35 - 5 = 30\\)',
        graphData: null,
      },
      {
        explanation: 'Calculate the upper bound. Pitfall: using \\(3\\sigma\\) instead of \\(2\\sigma\\) (giving the wrong distractor 27.5 to 42.5), or reusing the one-SD interval by mistake, are common errors.',
        workingOut: '\\(35 + 5 = 40\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: the range within two standard deviations of the mean is 30 to 40.',
        workingOut: '\\([30, 40]\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },
  {
    id: 'y10-18e-q2bi',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'medium',
    timeLimit: 90,
    question: 'The mean and standard deviation of a data set are given as \\(\\bar{x} = 40\\), \\(\\sigma = 5\\). Find the range of values that is within one standard deviation of the mean.',
    opts: ['25 to 55', '30 to 50', '37.5 to 42.5', '35 to 45'],
    a: 3,
    answer: '3',
    hint: 'One SD range: \\(\\bar{x} - \\sigma\\) to \\(\\bar{x} + \\sigma\\).',
    solution: 'One SD: 40±5 = 35 to 45.',
    solutionSteps: [
      {
        explanation: 'State the one-SD interval formula and the known values.',
        workingOut: '\\(\\bar{x} - \\sigma \\text{ to } \\bar{x} + \\sigma\\)',
        graphData: null,
      },
      {
        explanation: 'Calculate the lower bound.',
        workingOut: '\\(40 - 5 = 35\\)',
        graphData: null,
      },
      {
        explanation: 'Calculate the upper bound. Pitfall: halving \\(\\sigma\\) (giving the wrong distractor 37.5 to 42.5) is a common mistake.',
        workingOut: '\\(40 + 5 = 45\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: the range within one standard deviation of the mean is 35 to 45.',
        workingOut: '\\([35, 45]\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },
  {
    id: 'y10-18e-q2bii',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'medium',
    timeLimit: 90,
    question: 'Using the same data set (\\(\\bar{x} = 40\\), \\(\\sigma = 5\\)), find the range of values that is within TWO standard deviations of the mean.',
    opts: ['35 to 45', '25 to 55', '37.5 to 42.5', '30 to 50'],
    a: 3,
    answer: '3',
    hint: 'Two SD range: \\(\\bar{x} - 2\\sigma\\) to \\(\\bar{x} + 2\\sigma\\).',
    solution: 'Two SD: 40±10 = 30 to 50.',
    solutionSteps: [
      {
        explanation: 'State the two-SD interval formula and calculate \\(2\\sigma\\) first.',
        workingOut: '\\(2\\sigma = 2 \\times 5 = 10\\)',
        graphData: null,
      },
      {
        explanation: 'Calculate the lower bound.',
        workingOut: '\\(40 - 10 = 30\\)',
        graphData: null,
      },
      {
        explanation: 'Calculate the upper bound. Pitfall: using \\(3\\sigma\\) instead of \\(2\\sigma\\) (giving the wrong distractor 25 to 55), or reusing the one-SD interval by mistake, are common errors.',
        workingOut: '\\(40 + 10 = 50\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: the range within two standard deviations of the mean is 30 to 50.',
        workingOut: '\\([30, 50]\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },
  {
    id: 'y10-18e-q2ci',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'medium',
    timeLimit: 90,
    question: 'The mean and standard deviation of a data set are given as \\(\\bar{x} = 35\\), \\(\\sigma = 8\\). Find the range of values that is within one standard deviation of the mean.',
    opts: ['19 to 51', '31 to 39', '11 to 59', '27 to 43'],
    a: 3,
    answer: '3',
    hint: 'One SD range: \\(\\bar{x} - \\sigma\\) to \\(\\bar{x} + \\sigma\\).',
    solution: 'One SD: 35±8 = 27 to 43.',
    solutionSteps: [
      {
        explanation: 'State the one-SD interval formula and the known values.',
        workingOut: '\\(\\bar{x} - \\sigma \\text{ to } \\bar{x} + \\sigma\\)',
        graphData: null,
      },
      {
        explanation: 'Calculate the lower bound.',
        workingOut: '\\(35 - 8 = 27\\)',
        graphData: null,
      },
      {
        explanation: 'Calculate the upper bound. Pitfall: halving \\(\\sigma\\) (giving the wrong distractor 31 to 39) is a common mistake.',
        workingOut: '\\(35 + 8 = 43\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: the range within one standard deviation of the mean is 27 to 43.',
        workingOut: '\\([27, 43]\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },
  {
    id: 'y10-18e-q2cii',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'medium',
    timeLimit: 90,
    question: 'Using the same data set (\\(\\bar{x} = 35\\), \\(\\sigma = 8\\)), find the range of values that is within TWO standard deviations of the mean.',
    opts: ['27 to 43', '11 to 59', '31 to 39', '19 to 51'],
    a: 3,
    answer: '3',
    hint: 'Two SD range: \\(\\bar{x} - 2\\sigma\\) to \\(\\bar{x} + 2\\sigma\\).',
    solution: 'Two SD: 35±16 = 19 to 51.',
    solutionSteps: [
      {
        explanation: 'State the two-SD interval formula and calculate \\(2\\sigma\\) first.',
        workingOut: '\\(2\\sigma = 2 \\times 8 = 16\\)',
        graphData: null,
      },
      {
        explanation: 'Calculate the lower bound.',
        workingOut: '\\(35 - 16 = 19\\)',
        graphData: null,
      },
      {
        explanation: 'Calculate the upper bound. Pitfall: using \\(3\\sigma\\) instead of \\(2\\sigma\\) (giving the wrong distractor 11 to 59), or reusing the one-SD interval by mistake, are common errors.',
        workingOut: '\\(35 + 16 = 51\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: the range within two standard deviations of the mean is 19 to 51.',
        workingOut: '\\([19, 51]\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },

  // ---- Q3: comparing Maths and English marks for a class ----
  {
    id: 'y10-18e-q3a',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'hard',
    timeLimit: 150,
    question:
      'The mathematics and English marks for a class of 15 students are given below.\n\n| Mathematics | 12 | 16 | 14 | 19 | 17 | 18 | 15 | 15 | 19 | 20 | 14 | 18 | 19 | 15 | 11 |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| English | 10 | 13 | 16 | 19 | 20 | 19 | 18 | 16 | 15 | 14 | 17 | 11 | 15 | 18 | 17 |\n\nCalculate, correct to two decimal places, the mean and standard deviation for each set of marks.',
    opts: [
      'Maths: mean = 16.13, \\(\\sigma\\) = 6.92; English: mean = 15.87, \\(\\sigma\\) = 7.98',
      'Maths: mean = 15.87, \\(\\sigma\\) = 2.63; English: mean = 16.13, \\(\\sigma\\) = 2.82',
      'Maths: mean = 16.13, \\(\\sigma\\) = 2.63; English: mean = 15.87, \\(\\sigma\\) = 2.75',
      'Maths: mean = 16.13, \\(\\sigma\\) = 2.63; English: mean = 15.87, \\(\\sigma\\) = 2.82',
    ],
    a: 3,
    answer: '3',
    hint: 'Use your calculator\'s statistics mode: enter each subject\'s 15 marks separately and read \\(\\bar{x}\\) and \\(\\sigma x\\) for each.',
    solution: 'Maths: mean=242/15≈16.13, σ≈2.63. English: mean=238/15≈15.87, σ≈2.82.',
    solutionSteps: [
      {
        explanation: 'Enter the 15 mathematics marks into your calculator\'s statistics mode (MODE → STAT → 1-VAR) and read off \\(\\bar{x}\\) and \\(\\sigma x\\).',
        workingOut: '\\(\\bar{x}_{Maths} = \\dfrac{242}{15} \\approx 16.13, \\quad \\sigma_{Maths} \\approx 2.63\\)',
        graphData: null,
      },
      {
        explanation: 'Clear the data (SHIFT → CLR → Stat) and enter the 15 English marks the same way.',
        workingOut: '\\(\\bar{x}_{English} = \\dfrac{238}{15} \\approx 15.87, \\quad \\sigma_{English} \\approx 2.82\\)',
        graphData: null,
      },
      {
        explanation: 'Pitfall: reading off the variance display instead of \\(\\sigma x\\), or selecting \\(sx\\) (which divides by n-1) instead of \\(\\sigma x\\), both give wrong-looking distractor values.',
        workingOut: '\\(\\sigma x \\neq \\text{variance}, \\quad \\sigma x \\neq sx\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: Mathematics has mean 16.13 and SD 2.63; English has mean 15.87 and SD 2.82.',
        workingOut: '\\(\\text{Maths: } (16.13, 2.63), \\quad \\text{English: } (15.87, 2.82)\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },
  {
    id: 'y10-18e-q3b',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'hard',
    timeLimit: 120,
    question:
      'Using the same class results (Maths: mean=16.13, \\(\\sigma\\)=2.63; English: mean=15.87, \\(\\sigma\\)=2.82), if a student scored 16 for the mathematics test and 14 for the English test, which is the better mark relative to the class results?',
    opts: [
      'They are equally good, since both marks are below their subject\'s mean.',
      'English, since \\(z_{English} \\approx -0.66\\) is more negative than \\(z_{Maths} \\approx -0.05\\).',
      'Mathematics, since \\(z_{Maths} \\approx -0.05\\) is closer to 0 (less below average) than \\(z_{English} \\approx -0.66\\).',
      'English, since 14 is a whole number below the mean while 16 is above it.',
    ],
    a: 2,
    answer: '2',
    hint: 'Convert each mark to a z-score using its own subject\'s mean and SD: \\(z = \\dfrac{x-\\bar{x}}{\\sigma}\\). The mark with the z-score closest to (or above) zero is relatively better.',
    solution: 'z(Maths)=(16-16.13)/2.63≈-0.05. z(English)=(14-15.87)/2.82≈-0.66. Mathematics is the better mark since -0.05 > -0.66.',
    solutionSteps: [
      {
        explanation: 'Calculate the z-score for the Mathematics mark, using Mathematics\' own mean and SD.',
        workingOut: '\\(z_{Maths} = \\dfrac{16 - 16.13}{2.63} \\approx -0.05\\)',
        graphData: null,
      },
      {
        explanation: 'Calculate the z-score for the English mark, using English\'s own mean and SD.',
        workingOut: '\\(z_{English} = \\dfrac{14 - 15.87}{2.82} \\approx -0.66\\)',
        graphData: null,
      },
      {
        explanation: 'Compare the two z-scores. A z-score closer to zero (or more positive) represents a relatively better result, even if both are negative.',
        workingOut: '\\(-0.05 > -0.66\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: the Mathematics mark is only slightly below the class average, while the English mark is well below its class average — so Mathematics is the better result relative to the class, even though 16 > 14 already suggested this at a glance, the z-scores confirm and quantify it properly.',
        workingOut: '\\(\\text{Mathematics is the better mark}\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },

  // ---- Q4: comparing English and Mathematics marks for four students ----
  {
    id: 'y10-18e-q4',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'hard',
    timeLimit: 180,
    question:
      'The table below lists the marks of four students in English and mathematics tests, along with the class mean and standard deviation for each test.\n\n| Student | Subject | Mark | Mean | SD |\n|---|---|---|---|---|\n| David | English | 15 | 17 | 2 |\n| David | Mathematics | 13 | 17 | 3 |\n| Akira | English | 42 | 30 | 6 |\n| Akira | Mathematics | 39 | 25 | 8 |\n| Katherine | English | 70 | 75 | 5 |\n| Katherine | Mathematics | 65 | 70 | 10 |\n| Daniel | English | 70 | 55 | 9 |\n| Daniel | Mathematics | 69 | 62 | 7 |\n\nFor each student, which subject represents their relatively better result?',
    opts: [
      'David: Mathematics; Akira: English; Katherine: Mathematics; Daniel: English',
      'David: English; Akira: Mathematics; Katherine: Mathematics; Daniel: English',
      'David: English; Akira: English; Katherine: English; Daniel: Mathematics',
      'David: English; Akira: English; Katherine: Mathematics; Daniel: English',
    ],
    a: 3,
    answer: '3',
    hint: 'For each student and each subject, calculate \\(z = \\dfrac{\\text{mark} - \\text{mean}}{\\text{SD}}\\), then compare the two z-scores — the higher one is the relatively better result.',
    solution:
      'David: z(Eng)=-1.0, z(Maths)=-1.33 -> English. Akira: z(Eng)=2.0, z(Maths)=1.75 -> English. Katherine: z(Eng)=-1.0, z(Maths)=-0.5 -> Maths. Daniel: z(Eng)=1.67, z(Maths)=1.0 -> English.',
    solutionSteps: [
      {
        explanation: 'Calculate David\'s z-score for each subject.',
        workingOut: '\\(z_{Eng} = \\dfrac{15-17}{2} = -1.00, \\quad z_{Maths} = \\dfrac{13-17}{3} \\approx -1.33\\)\\\\ \\(-1.00 > -1.33 \\Rightarrow \\text{English is better}\\)',
        graphData: null,
      },
      {
        explanation: 'Calculate Akira\'s z-score for each subject.',
        workingOut: '\\(z_{Eng} = \\dfrac{42-30}{6} = 2.00, \\quad z_{Maths} = \\dfrac{39-25}{8} = 1.75\\)\\\\ \\(2.00 > 1.75 \\Rightarrow \\text{English is better}\\)',
        graphData: null,
      },
      {
        explanation: 'Calculate Katherine\'s and Daniel\'s z-scores for each subject.',
        workingOut:
          '\\(\\text{Katherine: } z_{Eng} = \\dfrac{70-75}{5} = -1.00, \\quad z_{Maths} = \\dfrac{65-70}{10} = -0.50 \\Rightarrow \\text{Mathematics is better}\\)\\\\ \\(\\text{Daniel: } z_{Eng} = \\dfrac{70-55}{9} \\approx 1.67, \\quad z_{Maths} = \\dfrac{69-62}{7} = 1.00 \\Rightarrow \\text{English is better}\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: David-English, Akira-English, Katherine-Mathematics, Daniel-English. Pitfall: Katherine\'s English mark (70) is numerically higher than her Mathematics mark (65), but she is actually relatively FURTHER below the English class average than below the Mathematics average — always compare z-scores, not raw marks.',
        workingOut: '\\(\\text{David: Eng, Akira: Eng, Katherine: Maths, Daniel: Eng}\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },

  // ---- Q5: bar charts — mean/SD, then effect of adding/multiplying a constant ----
  {
    id: 'y10-18e-q5ai',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'hard',
    timeLimit: 120,
    question:
      'A bar chart (i) shows a data set where the values 4, 5, 6, 7, 8 each occur exactly 3 times (a "flat-topped" or uniform distribution, n = 15). Calculate the mean and standard deviation.',
    opts: [
      'mean = 6.00, \\(\\sigma\\) = 2.00',
      'mean = 6.00, \\(\\sigma\\) = 1.46',
      'mean = 6.50, \\(\\sigma\\) = 1.41',
      'mean = 6.00, \\(\\sigma\\) = 1.41',
    ],
    a: 3,
    answer: '3',
    hint: 'Use your calculator\'s statistics mode: enter each value 4-8 with frequency 3.',
    solution: 'mean = 90/15 = 6.00. Sum of squared deviations = 30. Variance = 2. SD = sqrt(2) ≈ 1.41.',
    solutionSteps: [
      {
        explanation: 'Enter the data into your calculator\'s statistics mode: values 4, 5, 6, 7, 8 each with frequency 3.',
        workingOut: '\\(\\sum f_ix_i = 4(3)+5(3)+6(3)+7(3)+8(3) = 12+15+18+21+24 = 90\\)',
        graphData: null,
      },
      {
        explanation: 'Divide by n = 15 to find the mean.',
        workingOut: '\\(\\bar{x} = \\dfrac{90}{15} = 6.00\\)',
        graphData: null,
      },
      {
        explanation: 'Read \\(\\sigma x\\) from the calculator\'s Var menu (or compute by hand: deviations -2,-1,0,1,2 each with frequency 3).',
        workingOut: '\\(\\sum f(x-\\bar{x})^2 = 3(4+1+0+1+4) = 30, \\quad \\sigma^2 = \\dfrac{30}{15} = 2\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: take the square root.',
        workingOut: '\\(\\sigma = \\sqrt{2} \\approx 1.41\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },
  {
    id: 'y10-18e-q5aii',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'hard',
    timeLimit: 120,
    question:
      'A bar chart (ii) shows a bell-shaped data set: value 4 occurs once, 5 occurs twice, 6 occurs 3 times, 7 occurs 3 times, 8 occurs twice, and 9 occurs once (n = 12). Calculate the mean and standard deviation.',
    opts: [
      'mean = 6.50, \\(\\sigma\\) = 1.92',
      'mean = 6.00, \\(\\sigma\\) = 1.38',
      'mean = 6.50, \\(\\sigma\\) = 1.45',
      'mean = 6.50, \\(\\sigma\\) = 1.38',
    ],
    a: 3,
    answer: '3',
    hint: 'Use your calculator\'s statistics mode: enter each value 4-9 with its frequency.',
    solution: 'mean = 78/12 = 6.50. Sum of squared deviations = 23. Variance ≈ 1.92. SD ≈ 1.38.',
    solutionSteps: [
      {
        explanation: 'Enter the data into your calculator\'s statistics mode: values 4,5,6,7,8,9 with frequencies 1,2,3,3,2,1.',
        workingOut: '\\(\\sum f_ix_i = 4+10+18+21+16+9 = 78\\)',
        graphData: null,
      },
      {
        explanation: 'Divide by n = 12 to find the mean.',
        workingOut: '\\(\\bar{x} = \\dfrac{78}{12} = 6.50\\)',
        graphData: null,
      },
      {
        explanation: 'Read \\(\\sigma x\\) from the calculator\'s Var menu.',
        workingOut: '\\(\\sum f(x-\\bar{x})^2 = 23, \\quad \\sigma^2 = \\dfrac{23}{12} \\approx 1.92\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: take the square root.',
        workingOut: '\\(\\sigma = \\sqrt{1.92} \\approx 1.38\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },
  {
    id: 'y10-18e-q5aiii',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'hard',
    timeLimit: 120,
    question:
      'A bar chart (iii) shows a U-shaped data set: value 3 occurs 3 times, 4 occurs twice, 5 occurs once, 6 occurs once, 7 occurs twice, and 8 occurs 3 times (n = 12). Calculate the mean and standard deviation.',
    opts: [
      'mean = 6.00, \\(\\sigma\\) = 1.98',
      'mean = 5.50, \\(\\sigma\\) = 3.92',
      'mean = 5.50, \\(\\sigma\\) = 2.07',
      'mean = 5.50, \\(\\sigma\\) = 1.98',
    ],
    a: 3,
    answer: '3',
    hint: 'Use your calculator\'s statistics mode: enter each value 3-8 with its frequency.',
    solution: 'mean = 66/12 = 5.50. Sum of squared deviations = 47. Variance ≈ 3.92. SD ≈ 1.98.',
    solutionSteps: [
      {
        explanation: 'Enter the data into your calculator\'s statistics mode: values 3,4,5,6,7,8 with frequencies 3,2,1,1,2,3.',
        workingOut: '\\(\\sum f_ix_i = 9+8+5+6+14+24 = 66\\)',
        graphData: null,
      },
      {
        explanation: 'Divide by n = 12 to find the mean.',
        workingOut: '\\(\\bar{x} = \\dfrac{66}{12} = 5.50\\)',
        graphData: null,
      },
      {
        explanation: 'Read \\(\\sigma x\\) from the calculator\'s Var menu. Notice this "U-shaped" distribution has a much larger SD than the bell-shaped one in the previous question, despite having a similar range — the U-shape packs its values away from the centre.',
        workingOut: '\\(\\sum f(x-\\bar{x})^2 = 47, \\quad \\sigma^2 = \\dfrac{47}{12} \\approx 3.92\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: take the square root.',
        workingOut: '\\(\\sigma = \\sqrt{3.92} \\approx 1.98\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },
  {
    id: 'y10-18e-q5b',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'medium',
    timeLimit: 100,
    question:
      'Data set (i) is the bar chart data set where the values 4, 5, 6, 7, 8 each occur exactly 3 times (n = 15, mean = 6.00, \\(\\sigma\\) = 1.41). If 5 is added onto each data item, what are the new mean and standard deviation?',
    opts: [
      'new mean = 6.00, \\(\\sigma\\) = 1.41 (unchanged, since adding the same amount to everything cancels out)',
      'new mean = 11.00, new \\(\\sigma\\) = 6.41 (the SD also increases by 5)',
      'new mean = 11.00, new \\(\\sigma\\) = 7.05 (the SD scales by the same factor as the shift)',
      'new mean = 11.00, \\(\\sigma\\) unchanged at 1.41 (adding a constant shifts the mean but not the spread)',
    ],
    a: 3,
    answer: '3',
    hint: 'Adding the same constant to every value shifts every value — and the mean — by that constant, but does not change how spread out the values are relative to each other.',
    solution: 'Adding 5 to every value shifts the mean by 5 (to 11.00) but leaves every deviation from the mean unchanged, so the SD stays at 1.41.',
    solutionSteps: [
      {
        explanation: 'Adding a constant c to every value in a data set shifts the mean by exactly c, since the mean is just the (shifted) total divided by n.',
        workingOut: '\\(\\bar{x}_{new} = \\bar{x}_{old} + 5 = 6.00 + 5 = 11.00\\)',
        graphData: null,
      },
      {
        explanation: 'Consider what happens to each deviation from the mean: if every value shifts by 5 AND the mean shifts by 5, the difference between each value and the mean is unchanged.',
        workingOut: '\\((x+5) - (\\bar{x}+5) = x - \\bar{x}\\)',
        graphData: null,
      },
      {
        explanation: 'Since every deviation is exactly the same as before, the squared deviations — and therefore the standard deviation — are also unchanged.',
        workingOut: '\\(\\sigma_{new} = \\sigma_{old} = 1.41\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: the new mean is 11.00, but the standard deviation stays at 1.41. Pitfall: assuming the SD also increases by 5 (a very common misconception) is wrong — a constant shift moves the whole data set, but does not stretch or compress it.',
        workingOut: '\\(\\text{new mean} = 11.00, \\quad \\sigma \\text{ unchanged} = 1.41\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },
  {
    id: 'y10-18e-q5c',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'medium',
    timeLimit: 100,
    question:
      'Data set (i) is the bar chart data set where the values 4, 5, 6, 7, 8 each occur exactly 3 times (n = 15, mean = 6.00, \\(\\sigma\\) = 1.41). If each data item is multiplied by 2, what are the new mean and standard deviation?',
    opts: [
      'new mean = 12.00, \\(\\sigma\\) unchanged at 1.41 (multiplying doesn\'t affect spread)',
      'new mean = 6.00, new \\(\\sigma\\) = 2.83 (mean unaffected, only \\(\\sigma\\) scales)',
      'new mean = 12.00, new \\(\\sigma\\) = 5.66 (\\(\\sigma\\) scales by the square of the factor)',
      'new mean = 12.00, new \\(\\sigma\\) = 2.83 (both mean and \\(\\sigma\\) scale by the same factor of 2)',
    ],
    a: 3,
    answer: '3',
    hint: 'Multiplying every value by a constant k also multiplies the mean by k, and multiplies EACH deviation by k, so the standard deviation is also scaled by k.',
    solution: 'Multiplying every value by 2 doubles the mean (to 12.00) and also doubles the SD (to 2.83), since every deviation from the mean is also doubled.',
    solutionSteps: [
      {
        explanation: 'Multiplying every value in a data set by a constant k multiplies the mean by the same k, since the mean is the (scaled) total divided by n.',
        workingOut: '\\(\\bar{x}_{new} = 2 \\times \\bar{x}_{old} = 2 \\times 6.00 = 12.00\\)',
        graphData: null,
      },
      {
        explanation: 'Consider what happens to each deviation from the mean: if every value doubles AND the mean doubles, the gap between each value and the mean also doubles.',
        workingOut: '\\(2x - 2\\bar{x} = 2(x-\\bar{x})\\)',
        graphData: null,
      },
      {
        explanation: 'Since every deviation is exactly double what it was, the standard deviation (which measures those deviations) is also exactly doubled — NOT quadrupled, even though the squared deviations themselves are quadrupled (the square root undoes that).',
        workingOut: '\\(\\sigma_{new} = 2 \\times \\sigma_{old} = 2 \\times 1.41 = 2.83\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: the new mean is 12.00 and the new SD is 2.83 — both scaled by the same factor of 2. Pitfall: thinking the SD scales by \\(2^2=4\\) (confusing it with how the VARIANCE scales) gives the wrong distractor 5.66.',
        workingOut: '\\(\\text{new mean} = 12.00, \\quad \\sigma_{new} = 2.83\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },

  // ---- Q6: constructing a list with the LARGEST possible SD ----
  {
    id: 'y10-18e-q6a',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'medium',
    timeLimit: 100,
    question: 'Which of these lists of 10 numbers, where every number is either 1 or 5, has the LARGEST possible standard deviation?',
    opts: [
      'Nine 1s and one 5',
      'One 1 and nine 5s',
      'Eight 1s and two 5s',
      'Five 1s and five 5s',
    ],
    a: 3,
    answer: '3',
    hint: 'For a list with only two possible values, the spread is maximised when the two values are as evenly split as possible (as close to 50/50 as you can get).',
    solution: 'Five 1s and five 5s gives SD=2, the largest among these options (compared to 1.2, 1.2, and 1.6 for the uneven splits).',
    solutionSteps: [
      {
        explanation: 'For data with only two possible values, the standard deviation is largest when the split between the two values is as even as possible — an extreme split (like nine of one value, one of the other) pulls the mean close to the majority value, making most deviations small.',
        workingOut: '\\(\\text{even split} \\Rightarrow \\text{larger spread}\\)',
        graphData: null,
      },
      {
        explanation: 'Check the even 5-5 split: mean = (5×1 + 5×5)/10 = 3.00. Every value is exactly 2 away from the mean.',
        workingOut: '\\(\\bar{x} = \\dfrac{5+25}{10} = 3.00, \\quad |1-3|=|5-3|=2\\)',
        graphData: null,
      },
      {
        explanation: 'Calculate the SD for the even split.',
        workingOut: '\\(\\sigma^2 = \\dfrac{5(2)^2+5(2)^2}{10} = \\dfrac{40}{10} = 4, \\quad \\sigma = \\sqrt{4} = 2\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: compare with the uneven splits (nine-one gives SD=1.2, eight-two gives SD=1.6) — the even 5-5 split has the largest SD of 2.00.',
        workingOut: '\\(\\sigma = 2.00 \\ (\\text{largest})\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },
  {
    id: 'y10-18e-q6b',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'medium',
    timeLimit: 100,
    question: 'Which of these lists of 10 numbers, where every number is either 1 or 9, has the LARGEST possible standard deviation?',
    opts: [
      'Nine 1s and one 9',
      'Two 1s and eight 9s',
      'Three 1s and seven 9s',
      'Five 1s and five 9s',
    ],
    a: 3,
    answer: '3',
    hint: 'For a list with only two possible values, the spread is maximised when the two values are as evenly split as possible.',
    solution: 'Five 1s and five 9s gives SD=4, the largest among these options.',
    solutionSteps: [
      {
        explanation: 'As before, the standard deviation for a two-value data set is largest with the most even possible split.',
        workingOut: '\\(\\text{even split} \\Rightarrow \\text{larger spread}\\)',
        graphData: null,
      },
      {
        explanation: 'Check the even 5-5 split: mean = (5×1 + 5×9)/10 = 5.00. Every value is exactly 4 away from the mean.',
        workingOut: '\\(\\bar{x} = \\dfrac{5+45}{10} = 5.00, \\quad |1-5|=|9-5|=4\\)',
        graphData: null,
      },
      {
        explanation: 'Calculate the SD for the even split.',
        workingOut: '\\(\\sigma^2 = \\dfrac{5(4)^2+5(4)^2}{10} = \\dfrac{160}{10} = 16, \\quad \\sigma = \\sqrt{16} = 4\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: compare with the uneven splits (nine-one gives SD=2.4, three-seven gives SD≈3.67, two-eight gives SD=3.2) — the even 5-5 split has the largest SD of 4.00.',
        workingOut: '\\(\\sigma = 4.00 \\ (\\text{largest})\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },
  {
    id: 'y10-18e-q6c',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'hard',
    timeLimit: 120,
    question: 'Which of these lists of 10 numbers, where every number is 1, 5 or 9, and at least two of them are 5, has the LARGEST possible standard deviation?',
    opts: [
      'Four 1s, four 5s and two 9s',
      'Six 1s, two 5s and two 9s',
      'Five 1s, two 5s and three 9s',
      'Four 1s, two 5s and four 9s',
    ],
    a: 3,
    answer: '3',
    hint: 'Since 5 is the "middle" value (closest to the eventual mean), using it too often actually SHRINKS the spread. Use only the minimum required number of 5s, and split the rest evenly between the two extremes, 1 and 9.',
    solution: 'Using exactly two 5s (the minimum allowed) and splitting the remaining 8 values evenly (four 1s, four 9s) gives the largest SD, ≈3.58.',
    solutionSteps: [
      {
        explanation: 'The value 5 sits exactly at the midpoint between 1 and 9, so including MORE 5s than required pulls values toward the centre and shrinks the spread. To maximise SD, use only the minimum required number of 5s (two), and put every other value at one of the two extremes.',
        workingOut: '\\(\\text{minimise the middle value\'s count} \\Rightarrow \\text{two 5s only}\\)',
        graphData: null,
      },
      {
        explanation: 'With only two 5s, the remaining 8 values should be split as evenly as possible between 1 and 9 (four each), for the same "even split maximises spread" reasoning as the previous two questions.',
        workingOut: '\\(\\text{four 1s, two 5s, four 9s}\\)',
        graphData: null,
      },
      {
        explanation: 'Calculate the mean and SD for this list.',
        workingOut: '\\(\\bar{x} = \\dfrac{4(1)+2(5)+4(9)}{10} = \\dfrac{4+10+36}{10} = 5.00\\)\\\\ \\(\\sigma^2 = \\dfrac{4(4)^2+2(0)^2+4(4)^2}{10} = \\dfrac{128}{10} = 12.8, \\quad \\sigma \\approx 3.58\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: compare with lists that use more 5s than necessary (e.g. four 1s/four 5s/two 9s gives SD≈2.99) or an uneven 1/9 split (e.g. six 1s/two 5s/two 9s gives SD≈3.20) — both are smaller than 3.58.',
        workingOut: '\\(\\sigma \\approx 3.58 \\ (\\text{largest})\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },

  // ---- Q7: constructing a list with the SMALLEST possible SD ----
  {
    id: 'y10-18e-q7a',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'medium',
    timeLimit: 100,
    question: 'Which of these lists of 10 numbers, where every number is either 1 or 5, has the SMALLEST possible standard deviation?',
    opts: [
      'Eight 1s and two 5s',
      'Five 1s and five 5s',
      'Nine 1s and one 5',
      'Ten 1s (and zero 5s)',
    ],
    a: 3,
    answer: '3',
    hint: 'Since a list "where every number is either 1 or 5" does not require BOTH values to actually appear, the smallest possible spread is achieved by making every single value the same.',
    solution: 'A list of all 1s (or all 5s) has every value identical, so the standard deviation is exactly 0 — the smallest possible.',
    solutionSteps: [
      {
        explanation: 'The condition "every number is either 1 or 5" allows a number to be 1 OR 5 each time — it does not require both values to actually be used somewhere in the list. So the most extreme (least spread-out) option available is to make every single value identical.',
        workingOut: '\\(\\text{all values} = 1 \\quad (\\text{a valid list under the given condition})\\)',
        graphData: null,
      },
      {
        explanation: 'If every value in a data set is identical, every deviation from the mean is exactly zero.',
        workingOut: '\\(\\bar{x} = 1.00, \\quad x - \\bar{x} = 0 \\text{ for every value}\\)',
        graphData: null,
      },
      {
        explanation: 'A standard deviation of exactly zero is the smallest value a standard deviation can ever take (it cannot be negative, since it is a square root of an average of squares).',
        workingOut: '\\(\\sigma = \\sqrt{0} = 0\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: ten 1s gives SD = 0, smaller than any list that mixes in even a single 5 (e.g. nine 1s and one 5 gives SD=1.2, which is still much larger than zero).',
        workingOut: '\\(\\sigma = 0 \\ (\\text{smallest possible})\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },
  {
    id: 'y10-18e-q7b',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'medium',
    timeLimit: 100,
    question: 'Which of these lists of 10 numbers, where every number is either 1 or 9, has the SMALLEST possible standard deviation?',
    opts: [
      'Five 1s and five 9s',
      'Nine 1s and one 9',
      'Two 1s and eight 9s',
      'All ten numbers equal to 9 (zero 1s)',
    ],
    a: 3,
    answer: '3',
    hint: 'Since a list "where every number is either 1 or 9" does not require both values to appear, the smallest possible spread is achieved by making every value identical.',
    solution: 'A list of all 9s (or all 1s) has every value identical, so the standard deviation is exactly 0.',
    solutionSteps: [
      {
        explanation: 'As before, the condition does not require both 1 and 9 to actually appear — making every value identical is allowed and gives zero spread.',
        workingOut: '\\(\\text{all values} = 9 \\quad (\\text{a valid list under the given condition})\\)',
        graphData: null,
      },
      {
        explanation: 'Every deviation from the mean is exactly zero when every value is identical.',
        workingOut: '\\(\\bar{x} = 9.00, \\quad x - \\bar{x} = 0 \\text{ for every value}\\)',
        graphData: null,
      },
      {
        explanation: 'A standard deviation of zero is the smallest value possible for any data set.',
        workingOut: '\\(\\sigma = \\sqrt{0} = 0\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: all-9s gives SD = 0, smaller than any list that mixes in even a single 1 (e.g. nine 9s and one 1 would still give a nonzero SD).',
        workingOut: '\\(\\sigma = 0 \\ (\\text{smallest possible})\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },
  {
    id: 'y10-18e-q7c',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'hard',
    timeLimit: 120,
    question: 'Which of these lists of 10 numbers, where every number is 1, 5 or 9, and at least two of them are 5, has the SMALLEST possible standard deviation?',
    opts: [
      'Four 1s, two 5s and four 9s',
      'Six 1s, two 5s and two 9s',
      'Eight 5s, one 1 and one 9',
      'All ten numbers equal to 5 (with the "at least two are 5" condition easily satisfied)',
    ],
    a: 3,
    answer: '3',
    hint: 'The condition only requires "at least two" of the values to be 5 — it does not forbid using 5 for every single value. Making every value identical always gives the smallest possible spread.',
    solution: 'A list of all 5s satisfies "at least two are 5" and has every value identical, so the SD is exactly 0.',
    solutionSteps: [
      {
        explanation: 'Re-read the condition carefully: "at least two of them are 5" is a MINIMUM requirement, not a restriction on the maximum. A list where all 10 values are 5 easily satisfies "at least two are 5".',
        workingOut: '\\(\\text{all values} = 5 \\quad (\\text{satisfies "at least two are 5"})\\)',
        graphData: null,
      },
      {
        explanation: 'Every deviation from the mean is exactly zero when every value is identical.',
        workingOut: '\\(\\bar{x} = 5.00, \\quad x - \\bar{x} = 0 \\text{ for every value}\\)',
        graphData: null,
      },
      {
        explanation: 'A standard deviation of zero is the smallest value possible for any data set.',
        workingOut: '\\(\\sigma = \\sqrt{0} = 0\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: all-5s gives SD = 0. Pitfall: assuming you must include at least one 1 and one 9 somewhere (misreading "1, 5 or 9" as "must include all three") leads to unnecessarily large distractor SDs like the ones in the other options.',
        workingOut: '\\(\\sigma = 0 \\ (\\text{smallest possible})\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },

  // ---- Q8: flat raise to every employee's salary ----
  {
    id: 'y10-18e-q8a',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'medium',
    timeLimit: 100,
    question:
      'An employer has 29 employees whose weekly salaries have mean \\(\\bar{x} = \\$429\\) and standard deviation \\(\\sigma = \\$1.53\\). The employer decides to give a flat $100 per week raise to every employee. What would be the change to the average ANNUAL salary paid to each employee?',
    opts: [
      'Increases by $100 per year',
      'Increases by $2900 per year',
      'No change, since only the standard deviation would be affected',
      'Increases by $5200 per year (since $100/week &times; 52 weeks)',
    ],
    a: 3,
    answer: '3',
    hint: 'Adding the same constant to every value shifts the mean by that same constant. The raise is $100 per WEEK, so convert to an annual figure by multiplying by 52 weeks.',
    solution: 'A flat $100/week raise increases each employee\'s average weekly salary by $100, which is $100 x 52 = $5200 more per year.',
    solutionSteps: [
      {
        explanation: 'Adding the same constant ($100) to every employee\'s weekly salary shifts the mean weekly salary by exactly that constant.',
        workingOut: '\\(\\text{new mean weekly salary} = \\$429 + \\$100 = \\$529\\)',
        graphData: null,
      },
      {
        explanation: 'The question asks for the change on an ANNUAL basis, so convert the $100 weekly increase to a yearly figure by multiplying by the number of weeks in a year.',
        workingOut: '\\(\\$100 \\times 52 = \\$5200\\)',
        graphData: null,
      },
      {
        explanation: 'Pitfall: forgetting to annualise (giving the wrong distractor $100), or confusing this per-employee annual change with the employer\'s total weekly payroll change ($100 x 29 = $2900, which is a different question asked in part c).',
        workingOut: '\\(\\$100 \\neq \\$100 \\times 29 \\neq \\$100 \\times 52\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: each employee\'s average annual salary increases by $5200.',
        workingOut: '\\(\\$5200 \\text{ increase per year}\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },
  {
    id: 'y10-18e-q8b',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'medium',
    timeLimit: 90,
    question:
      'Using the same employer (29 employees, weekly mean \\(\\bar{x} = \\$429\\), weekly \\(\\sigma = \\$1.53\\), flat $100 weekly raise for everyone), would there be a change in the standard deviation of weekly salaries?',
    opts: [
      'Yes — the SD would increase by $100, to $101.53.',
      'Yes — the SD would decrease, since all salaries become closer together in relative (percentage) terms.',
      'Yes — the SD would double, since every value increased.',
      'No — adding the same $100 to every employee\'s salary does not change the standard deviation; σ remains $1.53.',
    ],
    a: 3,
    answer: '3',
    hint: 'Adding a constant to every value in a data set shifts the mean, but leaves every deviation from the mean — and therefore the standard deviation — unchanged.',
    solution: 'No change — a flat raise shifts every salary (and the mean) by the same amount, leaving each employee\'s deviation from the mean exactly as it was.',
    solutionSteps: [
      {
        explanation: 'The flat $100 raise adds the same constant to every employee\'s salary. As established earlier in this exercise, adding a constant shifts the mean but does not change the spread of the data.',
        workingOut: '\\((x+100) - (\\bar{x}+100) = x - \\bar{x}\\)',
        graphData: null,
      },
      {
        explanation: 'Since every employee\'s distance from the (new) mean is identical to their distance from the old mean, the standard deviation formula gives exactly the same result as before.',
        workingOut: '\\(\\sigma_{new} = \\sigma_{old} = \\$1.53\\)',
        graphData: null,
      },
      {
        explanation: 'Pitfall: it feels intuitive that "everyone got more money, so the numbers must be more spread out" — but standard deviation measures spread relative to the mean, and a flat raise moves the whole distribution without stretching or compressing it.',
        workingOut: '\\(\\text{flat shift} \\neq \\text{change in spread}\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: no, the standard deviation does not change.',
        workingOut: '\\(\\sigma \\text{ stays at } \\$1.53\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },
  {
    id: 'y10-18e-q8c',
    topicId: 'y10-18e-icem',
    c: '18E',
    t: 'Interpreting the standard deviation',
    type: 'multiple_choice',
    difficulty: 'medium',
    timeLimit: 100,
    question:
      'Using the same employer (29 employees, weekly mean \\(\\bar{x} = \\$429\\), weekly \\(\\sigma = \\$1.53\\), flat $100 weekly raise for everyone), what would be the change in the TOTAL weekly payments made to all employees?',
    opts: [
      'Increases by $100 per week',
      'Increases by $429 per week',
      'Increases by $2929 per week',
      'Increases by $2900 per week (since $100 &times; 29 employees)',
    ],
    a: 3,
    answer: '3',
    hint: 'The total weekly payment is the number of employees multiplied by the flat raise amount — this is different from the per-employee mean change asked about in part a.',
    solution: 'Total weekly payments increase by 29 x $100 = $2900.',
    solutionSteps: [
      {
        explanation: 'The total weekly payment made to ALL employees increases by the raise amount, multiplied by the number of employees receiving it.',
        workingOut: '\\(\\text{total increase} = \\text{number of employees} \\times \\text{raise per employee}\\)',
        graphData: null,
      },
      {
        explanation: 'Substitute the known values: 29 employees, each receiving a $100 raise.',
        workingOut: '\\(29 \\times \\$100 = \\$2900\\)',
        graphData: null,
      },
      {
        explanation: 'Pitfall: this is a different question from part a, which asked about the change to one employee\'s AVERAGE ANNUAL salary ($5200) — here we want the employer\'s total extra WEEKLY payroll cost across all 29 employees.',
        workingOut: '\\(\\$2900 \\text{ (total, per week)} \\neq \\$5200 \\text{ (per employee, per year)}\\)',
        graphData: null,
      },
      {
        explanation: 'Final answer: total weekly payments to employees increase by $2900.',
        workingOut: '\\(\\$2900 \\text{ increase per week}\\)',
        graphData: null,
      },
    ],
    graphData: null,
    isNew: true,
    requiresManualGrading: false,
  },
];
