// Generated candidates for HSC Standard "Measurement: Applications" (y11s-2)
// — Area, Surface Area and Volume. Written from scratch (no existing corpus
// reference was available for this topic — see QUESTION_BANK_EXPANSION.md).
// Pending review: ingest with --source=generated, then approve in the local
// corpus viewer's New Questions tab before ever deploying.
export const Y11S_CH2_QUESTIONS = [
  // ── Area of composite shapes (y11s-2a) ──────────────────────────────────
  {
    id: 'y11s-2a-gen-1',
    chapterId: 'y11s-2',
    topicId: 'y11s-2a',
    topicCode: '2A',
    t: 'Area of composite shapes',
    type: 'multiple_choice',
    difficulty: 'easy',
    timeLimit: 120,
    question: 'A garden bed is a rectangle 8 m long and 5 m wide, with a semicircular section of diameter 5 m attached to one end. Find the total area, correct to two decimal places.',
    options: ['\\( 49.82 \\text{ m}^2 \\)', '\\( 59.63 \\text{ m}^2 \\)', '\\( 40.00 \\text{ m}^2 \\)', '\\( 45.00 \\text{ m}^2 \\)'],
    answer: '0',
    solutionSteps: [
      { explanation: 'Find the area of the rectangle.', workingOut: '\\( A_{rect} = 8 \\times 5 = 40 \\text{ m}^2 \\)' },
      { explanation: 'Find the area of the semicircle (radius = 2.5 m, half of the diameter).', workingOut: '\\( A_{semi} = \\dfrac{1}{2}\\pi (2.5)^2 = 9.82 \\text{ m}^2 \\)' },
      { explanation: 'Add the two areas together.', workingOut: '\\( A = 40 + 9.82 = 49.82 \\text{ m}^2 \\)' },
    ],
  },
  {
    id: 'y11s-2a-gen-2',
    chapterId: 'y11s-2',
    topicId: 'y11s-2a',
    topicCode: '2A',
    t: 'Area of composite shapes',
    type: 'short_answer',
    difficulty: 'medium',
    timeLimit: 150,
    question: 'A block of land is a trapezium with parallel sides 12 m and 18 m, and the perpendicular distance between them is 9 m. A triangular section with base 6 m and height 9 m is removed from one corner for a driveway. Find the remaining area in \\( \\text{m}^2 \\).',
    answer: '108',
    solutionSteps: [
      { explanation: 'Find the area of the trapezium.', workingOut: '\\( A_{trap} = \\dfrac{1}{2}(12+18)(9) = 135 \\text{ m}^2 \\)' },
      { explanation: 'Find the area of the triangular section removed.', workingOut: '\\( A_{tri} = \\dfrac{1}{2}(6)(9) = 27 \\text{ m}^2 \\)' },
      { explanation: 'Subtract the triangle from the trapezium.', workingOut: '\\( A = 135 - 27 = 108 \\text{ m}^2 \\)' },
    ],
  },
  {
    id: 'y11s-2a-gen-3',
    chapterId: 'y11s-2',
    topicId: 'y11s-2a',
    topicCode: '2A',
    t: 'Area of composite shapes',
    type: 'multiple_choice',
    difficulty: 'medium',
    timeLimit: 150,
    question: 'A rectangle measuring 10 m by 6 m has a quarter-circle of radius 6 m cut from one corner. Find the remaining area, correct to one decimal place.',
    options: ['\\( 31.7 \\text{ m}^2 \\)', '\\( 28.3 \\text{ m}^2 \\)', '\\( 60.0 \\text{ m}^2 \\)', '\\( 88.3 \\text{ m}^2 \\)'],
    answer: '0',
    solutionSteps: [
      { explanation: 'Find the area of the rectangle.', workingOut: '\\( A_{rect} = 10 \\times 6 = 60 \\text{ m}^2 \\)' },
      { explanation: 'Find the area of the quarter circle removed.', workingOut: '\\( A_{quarter} = \\dfrac{1}{4}\\pi (6)^2 = 28.3 \\text{ m}^2 \\)' },
      { explanation: 'Subtract the quarter circle from the rectangle.', workingOut: '\\( A = 60 - 28.3 = 31.7 \\text{ m}^2 \\)' },
    ],
  },

  // ── Surface area (y11s-2b) ───────────────────────────────────────────────
  {
    id: 'y11s-2b-gen-1',
    chapterId: 'y11s-2',
    topicId: 'y11s-2b',
    topicCode: '2B',
    t: 'Surface area of solids',
    type: 'short_answer',
    difficulty: 'easy',
    timeLimit: 120,
    question: 'Find the surface area of a closed rectangular prism with length 8 cm, width 5 cm and height 4 cm, in \\( \\text{cm}^2 \\).',
    answer: '184',
    solutionSteps: [
      { explanation: 'Use the surface area formula for a rectangular prism.', workingOut: '\\( SA = 2(lw + lh + wh) \\)' },
      { explanation: 'Substitute the dimensions and evaluate.', workingOut: '\\( SA = 2(8\\times5 + 8\\times4 + 5\\times4) = 2(92) = 184 \\text{ cm}^2 \\)' },
    ],
  },
  {
    id: 'y11s-2b-gen-2',
    chapterId: 'y11s-2',
    topicId: 'y11s-2b',
    topicCode: '2B',
    t: 'Surface area of solids',
    type: 'multiple_choice',
    difficulty: 'medium',
    timeLimit: 150,
    question: 'A cylindrical can, closed at both ends, has a radius of 3.5 cm and a height of 12 cm. Find its surface area, correct to the nearest whole number.',
    options: ['\\( 341 \\text{ cm}^2 \\)', '\\( 264 \\text{ cm}^2 \\)', '\\( 302 \\text{ cm}^2 \\)', '\\( 836 \\text{ cm}^2 \\)'],
    answer: '0',
    solutionSteps: [
      { explanation: 'Use the total surface area formula for a closed cylinder.', workingOut: '\\( SA = 2\\pi r^2 + 2\\pi rh \\)' },
      { explanation: 'Substitute \\( r = 3.5 \\) and \\( h = 12 \\), then evaluate.', workingOut: '\\( SA = 2\\pi(3.5)^2 + 2\\pi(3.5)(12) = 76.97 + 263.89 = 340.86 \\approx 341 \\text{ cm}^2 \\)' },
    ],
  },
  {
    id: 'y11s-2b-gen-3',
    chapterId: 'y11s-2',
    topicId: 'y11s-2b',
    topicCode: '2B',
    t: 'Surface area of solids',
    type: 'short_answer',
    difficulty: 'hard',
    timeLimit: 180,
    question: 'A cone with a closed circular base has a base radius of 6 cm and a slant height of 10 cm. Find its total surface area, correct to one decimal place, in \\( \\text{cm}^2 \\).',
    answer: '301.6',
    solutionSteps: [
      { explanation: 'Use the total surface area formula for a closed cone.', workingOut: '\\( SA = \\pi r^2 + \\pi rl \\)' },
      { explanation: 'Substitute \\( r = 6 \\) and \\( l = 10 \\), then evaluate.', workingOut: '\\( SA = \\pi(6)^2 + \\pi(6)(10) = 113.10 + 188.50 = 301.6 \\text{ cm}^2 \\)' },
    ],
  },

  // ── Volume (y11s-2c) ─────────────────────────────────────────────────────
  {
    id: 'y11s-2c-gen-1',
    chapterId: 'y11s-2',
    topicId: 'y11s-2c',
    topicCode: '2C',
    t: 'Volume of solids',
    type: 'multiple_choice',
    difficulty: 'easy',
    timeLimit: 120,
    question: 'Find the volume of a rectangular prism with dimensions 7 cm, 4 cm and 5 cm.',
    options: ['\\( 140 \\text{ cm}^3 \\)', '\\( 16 \\text{ cm}^3 \\)', '\\( 35 \\text{ cm}^3 \\)', '\\( 70 \\text{ cm}^3 \\)'],
    answer: '0',
    solutionSteps: [
      { explanation: 'Multiply the three dimensions together.', workingOut: '\\( V = 7 \\times 4 \\times 5 = 140 \\text{ cm}^3 \\)' },
    ],
  },
  {
    id: 'y11s-2c-gen-2',
    chapterId: 'y11s-2',
    topicId: 'y11s-2c',
    topicCode: '2C',
    t: 'Volume of solids',
    type: 'short_answer',
    difficulty: 'medium',
    timeLimit: 150,
    question: 'A cylindrical water tank has a radius of 1.5 m and a height of 2.8 m. Find its volume, correct to two decimal places, in \\( \\text{m}^3 \\).',
    answer: '19.79',
    solutionSteps: [
      { explanation: 'Use the volume formula for a cylinder.', workingOut: '\\( V = \\pi r^2 h \\)' },
      { explanation: 'Substitute \\( r = 1.5 \\) and \\( h = 2.8 \\), then evaluate.', workingOut: '\\( V = \\pi (1.5)^2 (2.8) = 19.79 \\text{ m}^3 \\)' },
    ],
  },
  {
    id: 'y11s-2c-gen-3',
    chapterId: 'y11s-2',
    topicId: 'y11s-2c',
    topicCode: '2C',
    t: 'Volume of solids',
    type: 'multiple_choice',
    difficulty: 'medium',
    timeLimit: 150,
    question: 'A square pyramid has a base side length of 8 cm and a perpendicular height of 9 cm. Find its volume.',
    options: ['\\( 192 \\text{ cm}^3 \\)', '\\( 576 \\text{ cm}^3 \\)', '\\( 64 \\text{ cm}^3 \\)', '\\( 288 \\text{ cm}^3 \\)'],
    answer: '0',
    solutionSteps: [
      { explanation: 'Use the volume formula for a pyramid.', workingOut: '\\( V = \\dfrac{1}{3} \\times \\text{base area} \\times \\text{height} \\)' },
      { explanation: 'Substitute the base area \\( (8\\times8=64) \\) and height, then evaluate.', workingOut: '\\( V = \\dfrac{1}{3}(64)(9) = 192 \\text{ cm}^3 \\)' },
    ],
  },
  {
    id: 'y11s-2c-gen-4',
    chapterId: 'y11s-2',
    topicId: 'y11s-2c',
    topicCode: '2C',
    t: 'Volume of solids',
    type: 'short_answer',
    difficulty: 'hard',
    timeLimit: 180,
    question: 'A solid consists of a hemisphere of radius 4 cm sitting on top of a cylinder of radius 4 cm and height 10 cm. Find the total volume of the solid, correct to one decimal place, in \\( \\text{cm}^3 \\).',
    answer: '636.7',
    solutionSteps: [
      { explanation: 'Find the volume of the cylinder.', workingOut: '\\( V_{cyl} = \\pi (4)^2 (10) = 502.65 \\text{ cm}^3 \\)' },
      { explanation: 'Find the volume of the hemisphere (half of a sphere).', workingOut: '\\( V_{hemi} = \\dfrac{2}{3}\\pi (4)^3 = 134.04 \\text{ cm}^3 \\)' },
      { explanation: 'Add the two volumes together.', workingOut: '\\( V = 502.65 + 134.04 = 636.7 \\text{ cm}^3 \\)' },
    ],
  },
];
