export const Y12A_CH5F_QUESTIONS = [
  {
    id: "y12a-5f-q1a",
    type: "short_answer",
    question: "Use the calculator's \\(\ln\\) button to approximate, correct to four significant figures:\n\\(\log_e 12\\)",
    a: "2.485",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q1b",
    type: "short_answer",
    question: "Use the calculator's \\(\ln\\) button to approximate, correct to four significant figures:\n\\(\log_e 0.2\\)",
    a: "-1.609",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q1c",
    type: "short_answer",
    question: "Use the calculator's \\(\ln\\) button to approximate, correct to four significant figures:\n\\(\ln 9876\\)",
    a: "9.198",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q1d",
    type: "short_answer",
    question: "Use the calculator's \\(\ln\\) button to approximate, correct to four significant figures:\n\\(\ln 0.000005\\)",
    a: "-12.21",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q1e",
    type: "short_answer",
    question: "Use the calculator's \\(\ln\\) button to approximate, correct to four significant figures:\n\\(\log_e 60\\)",
    a: "4.094",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q1f",
    type: "short_answer",
    question: "Use the calculator's \\(\ln\\) button to approximate, correct to four significant figures:\n\\(\log_e 0.05\\)",
    a: "-2.996",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q2a",
    type: "short_answer",
    question: "Use the identities \\(\log_e e^x = x\\) for all real \\(x\\), and \\(e^{\log_e x} = x\\) for \\(x > 0\\), to simplify:\n\\(\log_e e^4\\)",
    a: "4",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q2b",
    type: "short_answer",
    question: "Use the identities \\(\log_e e^x = x\\) for all real \\(x\\), and \\(e^{\log_e x} = x\\) for \\(x > 0\\), to simplify:\n\\(\log_e e^{-2}\\)",
    a: "-2",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q2c",
    type: "short_answer",
    question: "Use the identities \\(\log_e e^x = x\\) for all real \\(x\\), and \\(e^{\log_e x} = x\\) for \\(x > 0\\), to simplify:\n\\(\log_e \\frac{1}{e^3}\\)",
    a: "-3",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q2d",
    type: "short_answer",
    question: "Use the identities \\(\log_e e^x = x\\) for all real \\(x\\), and \\(e^{\log_e x} = x\\) for \\(x > 0\\), to simplify:\n\\(\log_e \\sqrt[3]{e}\\)",
    a: "\\frac{1}{3}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q2e",
    type: "short_answer",
    question: "Use the identities \\(\log_e e^x = x\\) for all real \\(x\\), and \\(e^{\log_e x} = x\\) for \\(x > 0\\), to simplify:\n\\(e^{\ln 7}\\)",
    a: "7",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q2f",
    type: "short_answer",
    question: "Use the identities \\(\log_e e^x = x\\) for all real \\(x\\), and \\(e^{\log_e x} = x\\) for \\(x > 0\\), to simplify:\n\\(e^{\ln 0.02}\\)",
    a: "0.02",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q2g",
    type: "short_answer",
    question: "Use the identities \\(\log_e e^x = x\\) for all real \\(x\\), and \\(e^{\log_e x} = x\\) for \\(x > 0\\), to simplify:\n\\(e^{\ln 3}\\)",
    a: "3",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q2h",
    type: "short_answer",
    question: "Use the identities \\(\log_e e^x = x\\) for all real \\(x\\), and \\(e^{\log_e x} = x\\) for \\(x > 0\\), to simplify:\n\\(e^{\ln e^2}\\)",
    a: "e^2",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q3a",
    type: "short_answer",
    teacher_review: true,
    question: "Use your calculator to confirm that \\(\log_e 1 = 0\\).",
    a: "Confirmed",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q3b",
    type: "short_answer",
    teacher_review: true,
    question: "Write \\(1\\) as a power of \\(e\\), then use the identities in question 2 to explain why \\(\log_e 1 = 0\\).",
    a: "1 = e^0, so \log_e 1 = \log_e e^0 = 0",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q3c",
    type: "short_answer",
    teacher_review: true,
    question: "Use your calculator to confirm that \\(\log_e e = 1\\).",
    a: "Confirmed",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q3d",
    type: "short_answer",
    teacher_review: true,
    question: "Write \\(e\\) as a power of \\(e\\), then use the identities in question 2 to explain why \\(\log_e e = 1\\).",
    a: "e = e^1, so \log_e e = \log_e e^1 = 1",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q4a",
    type: "short_answer",
    question: "Convert the exponential statement to logarithm form:\n\\(x = e^5\\)",
    a: "\\log_e x = 5",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q4b",
    type: "short_answer",
    question: "Convert the logarithmic statement to exponential form:\n\\(\log_e x = -3\\)",
    a: "x = e^{-3}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q4c",
    type: "short_answer",
    question: "Convert the logarithmic statement to exponential form:\n\\(x = \\ln 15\\)",
    a: "e^x = 15",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q4d",
    type: "short_answer",
    question: "Convert the exponential statement to logarithm form:\n\\(e^x = \\frac{1}{4}\\)",
    a: "x = \\ln \\frac{1}{4}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q5a",
    type: "short_answer",
    teacher_review: true,
    question: "Use the change-of-base formula to express the logarithm in terms of logarithms base \\(e\\). Then approximate it correct to four significant figures:\n\\(\log_3 8\\)",
    a: "\\frac{\ln 8}{\ln 3} \approx 1.893",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q5b",
    type: "short_answer",
    teacher_review: true,
    question: "Use the change-of-base formula to express the logarithm in terms of logarithms base \\(e\\). Then approximate it correct to four significant figures:\n\\(\log_{10} 30\\)",
    a: "\\frac{\ln 30}{\ln 10} \approx 1.477",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q5c",
    type: "short_answer",
    teacher_review: true,
    question: "Use the change-of-base formula to express the logarithm in terms of logarithms base \\(e\\). Then approximate it correct to four significant figures:\n\\(\log_4 0.05\\)",
    a: "\\frac{\ln 0.05}{\ln 4} \approx -2.161",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q6a",
    type: "short_answer",
    teacher_review: true,
    question: "What transformation maps \\(y = e^x\\) to \\(y = \\log_e x\\), and how can this transformation be used to find the gradient of \\(y = \\log_e x\\) at its \\(x\\)-intercept?",
    a: "Reflection in the line y = x. The gradient is the reciprocal of the gradient of y = e^x at its y-intercept, which is 1.",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q6b",
    type: "short_answer",
    teacher_review: true,
    question: "What transformation maps \\(y = \\log_e x\\) to \\(y = \\log_e(-x)\\), and how can this transformation also be interpreted as a dilation?",
    a: "Reflection in the y-axis. It is equivalent to a dilation by a factor of -1 horizontally.",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q6c",
    type: "short_answer",
    teacher_review: true,
    question: "Sketch \\(y = \\log_e x\\) and \\(y = \\log_e(-x)\\) on one set of axes.",
    a: "Sketch required.",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q7a",
    type: "short_answer",
    teacher_review: true,
    question: "Sketch the curve using a single transformation of \\(y = \\log_e x\\), and describe the transformation:\n\\(y = \\log_e x + 2\\)",
    a: "Translation upwards by 2 units.",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q7b",
    type: "short_answer",
    teacher_review: true,
    question: "Sketch the curve using a single transformation of \\(y = \\log_e x\\), and describe the transformation:\n\\(y = \\log_e(x - 3)\\)",
    a: "Translation right by 3 units.",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q7c",
    type: "short_answer",
    teacher_review: true,
    question: "Sketch the curve using a single transformation of \\(y = \\log_e x\\), and describe the transformation:\n\\(y = \\log_e(2x)\\)",
    a: "Horizontal dilation by factor of 1/2.",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q7d",
    type: "short_answer",
    teacher_review: true,
    question: "Sketch the curve using a single transformation of \\(y = \\log_e x\\), and describe the transformation:\n\\(y = 2 \\log_e x\\)",
    a: "Vertical dilation by factor of 2.",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q8a",
    type: "short_answer",
    teacher_review: true,
    question: "Sketch the curve using a single transformation of \\(y = \\log_e(-x)\\), and describe the transformation:\n\\(y = \\log_e(-x) - 2\\)",
    a: "Translation downwards by 2 units.",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q8b",
    type: "short_answer",
    teacher_review: true,
    question: "Sketch the curve using a single transformation of \\(y = \\log_e(-x)\\), and describe the transformation:\n\\(y = -\\log_e(-x)\\)",
    a: "Reflection in the x-axis.",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q8c",
    type: "short_answer",
    teacher_review: true,
    question: "Sketch the curve using a single transformation of \\(y = \\log_e(-x)\\), and describe the transformation:\n\\(y = 4 \\log_e(-x)\\)",
    a: "Vertical dilation by factor of 4.",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5f-q9",
    type: "short_answer",
    teacher_review: true,
    question: "The graph drawn is a dilation of \\(y = \\log_e(-x)\\).\nDescribe the dilation, and write down the equation of the curve.",
    a: "Horizontal dilation by factor of 1/2. Equation: y = \\log_e(-2x)",
    difficulty: "medium",
    timeLimit: 120,
    graphData: {
      "jsxGraph": {
            "width": 350,
            "height": 250,
            "boundingbox": [
                  -2,
                  3,
                  1,
                  -2
            ],
            "script": "board.suspendUpdate();\nboard.create('arrow', [[0,-2], [0, 3]], {strokeColor: 'black', strokeWidth: 1});\nboard.create('arrow', [[-2,0], [1, 0]], {strokeColor: 'black', strokeWidth: 1});\nboard.create('text', [0.8, -0.2], 'x', {anchorX: 'right', anchorY: 'top', fontSize: 14});\nboard.create('text', [-0.1, 2.8], 'y', {anchorX: 'right', anchorY: 'top', fontSize: 14});\nboard.create('functiongraph', [function(x){ return Math.log(-2*x); }, -2, -0.01], {strokeColor: 'black', strokeWidth: 1});\nboard.create('point', [-0.5, 0], {name: '-1/2', size: 2, label: {offset: [5, 10]}});\nboard.unsuspendUpdate();"
      }
},
  },
  {
    id: "y12a-5f-q10a",
    type: "short_answer",
    question: "Use the substitution \\(u = 2^x\\) to solve \\(4^x - 10 \\times 2^x + 16 = 0\\).",
    a: "x = 1, x = 3",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5f-q10b",
    type: "short_answer",
    question: "Use the substitution \\(u = 3^x\\) to solve \\(3^{2x} - 12 \\times 3^x + 27 = 0\\).",
    a: "x = 1, x = 2",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5f-q10ci",
    type: "short_answer",
    question: "Use similar substitutions, or none, to solve:\n\\(25^x - 30 \\times 5^x + 125 = 0\\)",
    a: "x = 1, x = 2",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5f-q10cii",
    type: "short_answer",
    question: "Use similar substitutions, or none, to solve:\n\\(9^x - 12 \\times 3^x + 27 = 0\\)",
    a: "x = 1, x = 2",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5f-q10ciii",
    type: "short_answer",
    question: "Use similar substitutions, or none, to solve:\n\\(3^{2x} - 2 \\times 3^x - 15 = 0\\)",
    a: "x = \\log_3 5",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5f-q10civ",
    type: "short_answer",
    question: "Use similar substitutions, or none, to solve:\n\\(7^{2x} - 6 \\times 7^x - 7 = 0\\)",
    a: "x = 1",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5f-q10cv",
    type: "short_answer",
    question: "Use similar substitutions, or none, to solve:\n\\(2^{5x} = 4^{x+3}\\)",
    a: "x = 2",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5f-q10cvi",
    type: "short_answer",
    question: "Use similar substitutions, or none, to solve:\n\\(4^x - 5 \\times 2^{x+1} + 16 = 0\\)",
    a: "x = 1, x = 3",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5f-q11a",
    type: "short_answer",
    question: "Use the substitution \\(u = e^x\\) or \\(u = e^{2x}\\) to reduce these equations to quadratics and solve them. Write your answers as logarithms base \\(e\\), unless they can be further simplified.\n\\(e^{2x} - 3e^x + 2 = 0\\)",
    a: "x = 0, x = \\ln 2",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5f-q11b",
    type: "short_answer",
    question: "Use the substitution \\(u = e^x\\) or \\(u = e^{2x}\\) to reduce these equations to quadratics and solve them. Write your answers as logarithms base \\(e\\), unless they can be further simplified.\n\\(e^{2x} + 2e^x - 8 = 0\\)",
    a: "x = \\ln 2",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5f-q11c",
    type: "short_answer",
    question: "Use the substitution \\(u = e^x\\) or \\(u = e^{2x}\\) to reduce these equations to quadratics and solve them. Write your answers as logarithms base \\(e\\), unless they can be further simplified.\n\\(e^{4x} - 5e^{2x} + 4 = 0\\)",
    a: "x = 0, x = \\ln 2",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5f-q11d",
    type: "short_answer",
    question: "Use the substitution \\(u = e^x\\) or \\(u = e^{2x}\\) to reduce these equations to quadratics and solve them. Write your answers as logarithms base \\(e\\), unless they can be further simplified.\n\\(e^{4x} - 9e^{2x} = 0\\)",
    a: "x = \\ln 3",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5f-q12a",
    type: "short_answer",
    question: "Use a substitution, or none, to solve:\n\\((\log_e x)^2 - 4\log_e x + 3 = 0\\)",
    a: "x = e, x = e^3",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5f-q12b",
    type: "short_answer",
    question: "Use a substitution, or none, to solve:\n\\((\log_e x)^2 = 4\log_e x\\)",
    a: "x = 1, x = e^4",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5f-q13ai",
    type: "short_answer",
    question: "Use the laws for logarithms to simplify:\n\\(\log_e e^3\\)",
    a: "3",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5f-q13aii",
    type: "short_answer",
    question: "Use the laws for logarithms to simplify:\n\\(\log_e(\log_e e^e)\\)",
    a: "1",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5f-q13aiii",
    type: "short_answer",
    question: "Use the laws for logarithms to simplify:\n\\(\log_e(\log_e(\log_e e^{e^e}))\\)",
    a: "1",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5f-q13bi",
    type: "short_answer",
    question: "Use the laws for logarithms to express as a single logarithm:\n\\(\ln 6 + \ln 3\\)",
    a: "\\ln 18",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5f-q13bii",
    type: "short_answer",
    question: "Use the laws for logarithms to express as a single logarithm:\n\\(\ln 40 - \log_e 8\\)",
    a: "\\ln 5",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5f-q13biii",
    type: "short_answer",
    question: "Use the laws for logarithms to express as a single logarithm:\n\\(\ln 15 - \ln 5 + \ln 2\\)",
    a: "\\ln 6",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5f-q14a",
    type: "short_answer",
    question: "Use a substitution such as \\(u = 4^x\\) to solve the equation. Give the solution as a rational number, or approximate correct to three decimal places.\n\\(2^{4x} - 5 \\times 2^{2x} + 4 = 0\\)",
    a: "x = 0, x = 1",
    difficulty: "hard",
    timeLimit: 180,
  },
  {
    id: "y12a-5f-q14b",
    type: "short_answer",
    question: "Use a substitution such as \\(u = 4^x\\) to solve the equation. Give the solution as a rational number, or approximate correct to three decimal places.\n\\(100^x - 11 \\times 10^x + 10 = 0\\)",
    a: "x = 0, x = 1",
    difficulty: "hard",
    timeLimit: 180,
  },
  {
    id: "y12a-5f-q14c",
    type: "short_answer",
    question: "Use a substitution such as \\(u = 4^x\\) to solve the equation. Give the solution as a rational number, or approximate correct to three decimal places.\n\\(\\left(\\frac{1}{2}\\right)^{2x} - 5 \\times \\left(\\frac{1}{2}\\right)^x + 4 = 0\\)",
    a: "x = 0, x = -2",
    difficulty: "hard",
    timeLimit: 180,
  },
  {
    id: "y12a-5f-q15a",
    type: "short_answer",
    teacher_review: true,
    question: "Use, and describe, a dilation of \\(y = \\log_e x\\) to sketch \\(y = \\log_e(3x)\\).",
    a: "Horizontal dilation by factor 1/3.",
    difficulty: "hard",
    timeLimit: 180,
  },
  {
    id: "y12a-5f-q15b",
    type: "short_answer",
    teacher_review: true,
    question: "Use, and describe, a subsequent translation to sketch \\(y = \\log_e 3(x - 2)\\).",
    a: "Translation right by 2 units.",
    difficulty: "hard",
    timeLimit: 180,
  },
  {
    id: "y12a-5f-q15c",
    type: "short_answer",
    teacher_review: true,
    question: "Use, and describe, a subsequent dilation to sketch \\(y = \\frac{1}{3} \\log_e 3(x - 2)\\).",
    a: "Vertical dilation by factor 1/3.",
    difficulty: "hard",
    timeLimit: 180,
  },
  {
    id: "y12a-5f-q15d",
    type: "short_answer",
    teacher_review: true,
    question: "Use, and describe, a subsequent translation to sketch \\(y = \\frac{1}{3} \\log_e 3(x - 2) - 1\\).",
    a: "Translation downwards by 1 unit.",
    difficulty: "hard",
    timeLimit: 180,
  },
  {
    id: "y12a-5f-q16a",
    type: "short_answer",
    teacher_review: true,
    question: "Interpret the transformation from \\(y = \\log_e x\\) to \\(y = \\log_e(4x)\\) as a dilation. Then interpret it as a translation.",
    a: "Horizontal dilation by factor 1/4. Translation upwards by \\ln 4.",
    difficulty: "hard",
    timeLimit: 180,
  },
  {
    id: "y12a-5f-q16b",
    type: "short_answer",
    teacher_review: true,
    question: "Interpret the transformation from \\(y = \\log_e x\\) to \\(y = \\log_e x + 3\\) as a translation. Then interpret it as a dilation by writing 3 as \\(\log_e e^3\\).",
    a: "Translation upwards by 3 units. Horizontal dilation by factor e^{-3}.",
    difficulty: "hard",
    timeLimit: 180,
  },
];
