export const Y12A_CH5G_QUESTIONS = [
  {
    id: "y12a-5g-q1a",
    type: "short_answer",
    question: "Use the standard form \\(\\frac{d}{dx} \\log_e(ax + b) = \\frac{a}{ax + b}\\) to differentiate:\n\\(y = \\log_e(x + 5)\\)",
    a: "\\frac{1}{x + 5}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q1b",
    type: "short_answer",
    question: "Use the standard form \\(\\frac{d}{dx} \\log_e(ax + b) = \\frac{a}{ax + b}\\) to differentiate:\n\\(y = \\log_e(x - 4)\\)",
    a: "\\frac{1}{x - 4}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q1c",
    type: "short_answer",
    question: "Use the standard form \\(\\frac{d}{dx} \\log_e(ax + b) = \\frac{a}{ax + b}\\) to differentiate:\n\\(y = \\log_e(4x + 3)\\)",
    a: "\\frac{4}{4x + 3}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q1d",
    type: "short_answer",
    question: "Use the standard form \\(\\frac{d}{dx} \\log_e(ax + b) = \\frac{a}{ax + b}\\) to differentiate:\n\\(y = \\log_e(3x - 2)\\)",
    a: "\\frac{3}{3x - 2}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q1e",
    type: "short_answer",
    question: "Use the standard form \\(\\frac{d}{dx} \\log_e(ax + b) = \\frac{a}{ax + b}\\) to differentiate:\n\\(y = \\log_e(-5x + 2)\\)",
    a: "\\frac{-5}{-5x + 2}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q1f",
    type: "short_answer",
    question: "Use the standard form \\(\\frac{d}{dx} \\log_e(ax + b) = \\frac{a}{ax + b}\\) to differentiate:\n\\(y = \\log_e(-2x + 5)\\)",
    a: "\\frac{-2}{-2x + 5}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q1g",
    type: "short_answer",
    question: "Use the standard form \\(\\frac{d}{dx} \\log_e(ax + b) = \\frac{a}{ax + b}\\) to differentiate:\n\\(y = \\ln(-3x - 8)\\)",
    a: "\\frac{-3}{-3x - 8}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q1h",
    type: "short_answer",
    question: "Use the standard form \\(\\frac{d}{dx} \\log_e(ax + b) = \\frac{a}{ax + b}\\) to differentiate:\n\\(y = 4 \\ln(3x + 5)\\)",
    a: "\\frac{12}{3x + 5}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q1i",
    type: "short_answer",
    question: "Use the standard form \\(\\frac{d}{dx} \\log_e(ax + b) = \\frac{a}{ax + b}\\) to differentiate:\n\\(y = 2 \\ln(5x - 3)\\)",
    a: "\\frac{10}{5x - 3}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q2a",
    type: "short_answer",
    question: "Differentiate the function:\n\\(y = \\log_e 3x\\)",
    a: "\\frac{1}{x}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q2b",
    type: "short_answer",
    question: "Differentiate the function:\n\\(y = \\log_e 4x\\)",
    a: "\\frac{1}{x}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q2c",
    type: "short_answer",
    question: "Differentiate the function:\n\\(y = \\log_e 6x\\)",
    a: "\\frac{1}{x}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q2d",
    type: "short_answer",
    question: "Differentiate the function:\n\\(y = \\log_e 8x\\)",
    a: "\\frac{1}{x}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q2e",
    type: "short_answer",
    question: "Differentiate the function:\n\\(y = 5 \\ln 2x\\)",
    a: "\\frac{5}{x}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q2f",
    type: "short_answer",
    question: "Differentiate the function:\n\\(y = 2 \\ln 3x\\)",
    a: "\\frac{2}{x}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q2g",
    type: "short_answer",
    question: "Differentiate the function:\n\\(y = 6 \\ln 5x\\)",
    a: "\\frac{6}{x}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q2h",
    type: "short_answer",
    question: "Differentiate the function:\n\\(y = 7 \\ln 8x\\)",
    a: "\\frac{7}{x}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q3a",
    type: "short_answer",
    question: "Find \\(\\frac{dy}{dx}\\) for the function. Then evaluate \\(\\frac{dy}{dx}\\) at \\(x = 2\\).\n\\(y = \\log_e(x + 2)\\)",
    a: "\\frac{1}{4}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q3b",
    type: "short_answer",
    question: "Find \\(\\frac{dy}{dx}\\) for the function. Then evaluate \\(\\frac{dy}{dx}\\) at \\(x = 2\\).\n\\(y = \\log_e(3x - 1)\\)",
    a: "\\frac{3}{5}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q3c",
    type: "short_answer",
    question: "Find \\(\\frac{dy}{dx}\\) for the function. Then evaluate \\(\\frac{dy}{dx}\\) at \\(x = 2\\).\n\\(y = \\log_e(4x - 5)\\)",
    a: "\\frac{4}{3}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q3d",
    type: "short_answer",
    question: "Find \\(\\frac{dy}{dx}\\) for the function. Then evaluate \\(\\frac{dy}{dx}\\) at \\(x = 2\\).\n\\(y = \\log_e(2x + 3)\\)",
    a: "\\frac{2}{7}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q3e",
    type: "short_answer",
    question: "Find \\(\\frac{dy}{dx}\\) for the function. Then evaluate \\(\\frac{dy}{dx}\\) at \\(x = 2\\).\n\\(y = 3 \\ln(x + 1)\\)",
    a: "1",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q3f",
    type: "short_answer",
    question: "Find \\(\\frac{dy}{dx}\\) for the function. Then evaluate \\(\\frac{dy}{dx}\\) at \\(x = 2\\).\n\\(y = 4 \\ln(3x + 1)\\)",
    a: "\\frac{12}{7}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q4a",
    type: "short_answer",
    question: "Differentiate the function:\n\\(y = 3 + \\log_e x\\)",
    a: "\\frac{1}{x}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q4b",
    type: "short_answer",
    question: "Differentiate the function:\n\\(y = 4 - \\log_e(x + 2)\\)",
    a: "-\\frac{1}{x + 2}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q4c",
    type: "short_answer",
    question: "Differentiate the function:\n\\(y = 2x + 3 \\log_e x\\)",
    a: "2 + \\frac{3}{x}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q4d",
    type: "short_answer",
    question: "Differentiate the function:\n\\(y = 3x^4 + 2 + 5 \\log_e x\\)",
    a: "12x^3 + \\frac{5}{x}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q4e",
    type: "short_answer",
    question: "Differentiate the function:\n\\(y = \\ln(3x - 1) + 4x^2\\)",
    a: "\\frac{3}{3x - 1} + 8x",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q4f",
    type: "short_answer",
    question: "Differentiate the function:\n\\(y = 2x^3 - 4x + 5 + \\ln(2x - 3)\\)",
    a: "6x^2 - 4 + \\frac{2}{2x - 3}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5g-q5a",
    type: "short_answer",
    question: "Use the log laws to simplify the function, then differentiate it:\n\\(y = \\ln x^4\\)",
    a: "\\frac{4}{x}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q5b",
    type: "short_answer",
    question: "Use the log laws to simplify the function, then differentiate it:\n\\(y = \\ln x^5\\)",
    a: "\\frac{5}{x}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q5c",
    type: "short_answer",
    question: "Use the log laws to simplify the function, then differentiate it:\n\\(y = \\ln x^{-4}\\)",
    a: "-\\frac{4}{x}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q5d",
    type: "short_answer",
    question: "Use the log laws to simplify the function, then differentiate it:\n\\(y = \\ln x^{-5}\\)",
    a: "-\\frac{5}{x}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q5e",
    type: "short_answer",
    question: "Use the log laws to simplify the function, then differentiate it:\n\\(y = \\ln x^{\\frac{1}{3}}\\)",
    a: "\\frac{1}{3x}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q5f",
    type: "short_answer",
    question: "Use the log laws to simplify the function, then differentiate it:\n\\(y = \\ln \\sqrt{x + 2}\\)",
    a: "\\frac{1}{2(x + 2)}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q6a",
    type: "short_answer",
    question: "Differentiate the function:\n\\(y = \\log_e \\frac{1}{4}x\\)",
    a: "\\frac{1}{x}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q6b",
    type: "short_answer",
    question: "Differentiate the function:\n\\(y = \\log_e \\frac{1}{5}x\\)",
    a: "\\frac{1}{x}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q6c",
    type: "short_answer",
    question: "Differentiate the function:\n\\(y = 4 \\log_e \\frac{1}{2}x\\)",
    a: "\\frac{4}{x}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q6d",
    type: "short_answer",
    question: "Differentiate the function:\n\\(y = -5 \\log_e \\frac{1}{3}x\\)",
    a: "-\\frac{5}{x}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q6e",
    type: "short_answer",
    question: "Differentiate the function:\n\\(y = 2x + \\log_e \\frac{1}{4}x\\)",
    a: "2 + \\frac{1}{x}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q6f",
    type: "short_answer",
    question: "Differentiate the function:\n\\(y = 5x^3 - \\log_e \\frac{1}{2}x\\)",
    a: "15x^2 - \\frac{1}{x}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q7a",
    type: "short_answer",
    question: "Use the full setting-out of the chain rule to differentiate:\n\\(\\ln(x^2 + 2)\\)",
    a: "\\frac{2x}{x^2 + 2}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q7b",
    type: "short_answer",
    question: "Use the full setting-out of the chain rule to differentiate:\n\\(\\ln(3 - x^2)\\)",
    a: "-\\frac{2x}{3 - x^2}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q7c",
    type: "short_answer",
    question: "Use the full setting-out of the chain rule to differentiate:\n\\(\\ln(2 + e^x)\\)",
    a: "\\frac{e^x}{2 + e^x}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q8a",
    type: "short_answer",
    question: "Use the standard form \\(\\frac{d}{dx} \\log_e u = \\frac{u'}{u}\\) to differentiate:\n\\(\\log_e(x^2 + 4x + 3)\\)",
    a: "\\frac{2x + 4}{x^2 + 4x + 3}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q8b",
    type: "short_answer",
    question: "Use the standard form \\(\\frac{d}{dx} \\log_e u = \\frac{u'}{u}\\) to differentiate:\n\\(\\log_e(2 + 3x^3)\\)",
    a: "\\frac{9x^2}{2 + 3x^3}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q8c",
    type: "short_answer",
    question: "Use the standard form \\(\\frac{d}{dx} \\log_e u = \\frac{u'}{u}\\) to differentiate:\n\\(\\ln(e^x - 3)\\)",
    a: "\\frac{e^x}{e^x - 3}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q8d",
    type: "short_answer",
    question: "Use the standard form \\(\\frac{d}{dx} \\log_e u = \\frac{u'}{u}\\) to differentiate:\n\\(2x + 1 - \\ln(x^2 + 2x)\\)",
    a: "2 - \\frac{2x + 2}{x^2 + 2x}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q8e",
    type: "short_answer",
    question: "Use the standard form \\(\\frac{d}{dx} \\log_e u = \\frac{u'}{u}\\) to differentiate:\n\\(2x^2 + \\ln(x^3 - 2x)\\)",
    a: "4x + \\frac{3x^2 - 2}{x^3 - 2x}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q8f",
    type: "short_answer",
    question: "Use the standard form \\(\\frac{d}{dx} \\log_e u = \\frac{u'}{u}\\) to differentiate:\n\\(3x^3 - 4x^2 + \\ln(3x^2 - 2x + 1)\\)",
    a: "9x^2 - 8x + \\frac{6x - 2}{3x^2 - 2x + 1}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q9a",
    type: "short_answer",
    question: "Find the gradient, and the angle of inclination correct to the nearest minute, of the tangent to \\(y = \\ln x\\) at the point where \\(x = 2\\). (Format: 'gradient, angle')",
    a: "1/2, 26^{\\circ}34'",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q9b",
    type: "short_answer",
    question: "Find the gradient, and the angle of inclination correct to the nearest minute, of the tangent to \\(y = \\ln x\\) at the point where \\(x = 5\\). (Format: 'gradient, angle')",
    a: "1/5, 11^{\\circ}19'",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q10a",
    type: "short_answer",
    question: "Differentiate using the product rule:\n\\(2x \\log_e x\\)",
    a: "2 \\log_e x + 2",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q10b",
    type: "short_answer",
    question: "Differentiate using the product rule:\n\\(x \\log_e(3x + 1)\\)",
    a: "\\log_e(3x + 1) + \\frac{3x}{3x + 1}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q10c",
    type: "short_answer",
    question: "Differentiate using the product rule:\n\\((3x + 2) \\log_e x\\)",
    a: "3 \\log_e x + \\frac{3x + 2}{x}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q10d",
    type: "short_answer",
    question: "Differentiate using the product rule:\n\\(x^5 \\log_e x\\)",
    a: "x^4(5 \\log_e x + 1)",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q10e",
    type: "short_answer",
    question: "Differentiate using the product rule:\n\\((x + 4) \\log_e(x + 4)\\)",
    a: "\\log_e(x + 4) + 1",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q10f",
    type: "short_answer",
    question: "Differentiate using the product rule:\n\\((x - 2) \\log_e(3x + 5)\\)",
    a: "\\log_e(3x + 5) + \\frac{3(x - 2)}{3x + 5}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q10g",
    type: "short_answer",
    question: "Differentiate using the product rule:\n\\(e^{2x} \\log_e x\\)",
    a: "e^{2x} \\left(2 \\log_e x + \\frac{1}{x}\\right)",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q10h",
    type: "short_answer",
    question: "Differentiate using the product rule:\n\\(e^{-2x} \\log_e x\\)",
    a: "e^{-2x} \\left(\\frac{1}{x} - 2 \\log_e x\\right)",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q11a",
    type: "short_answer",
    question: "Differentiate using the quotient rule:\n\\(y = \\frac{\\log_e 2x}{x}\\)",
    a: "\\frac{1 - \\log_e 2x}{x^2}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q11b",
    type: "short_answer",
    question: "Differentiate using the quotient rule:\n\\(y = \\frac{\\log_e x}{x^3}\\)",
    a: "\\frac{1 - 3 \\log_e x}{x^4}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q11c",
    type: "short_answer",
    question: "Differentiate using the quotient rule:\n\\(y = \\frac{2x}{\\log_e x}\\)",
    a: "\\frac{2(\\log_e x - 1)}{(\\log_e x)^2}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q11d",
    type: "short_answer",
    question: "Differentiate using the quotient rule:\n\\(y = \\frac{x^3}{\\log_e x}\\)",
    a: "\\frac{x^2(3 \\log_e x - 1)}{(\\log_e x)^2}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q11e",
    type: "short_answer",
    question: "Differentiate using the quotient rule:\n\\(y = \\frac{\\log_e x}{e^{2x}}\\)",
    a: "\\frac{\\frac{1}{x} - 2 \\log_e x}{e^{2x}}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q11f",
    type: "short_answer",
    question: "Differentiate using the quotient rule:\n\\(y = \\frac{e^{2x}}{\\log_e x}\\)",
    a: "\\frac{e^{2x}(2 \\log_e x - \\frac{1}{x})}{(\\log_e x)^2}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q12a",
    type: "short_answer",
    question: "Use the log laws to simplify each function, then differentiate it:\n\\(y = \\log_e 4x^5\\)",
    a: "\\frac{5}{x}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q12b",
    type: "short_answer",
    question: "Use the log laws to simplify each function, then differentiate it:\n\\(y = \\log_e 2x^3\\)",
    a: "\\frac{3}{x}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q12c",
    type: "short_answer",
    question: "Use the log laws to simplify each function, then differentiate it:\n\\(y = \\log_e \\sqrt[4]{x}\\)",
    a: "\\frac{1}{4x}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q12d",
    type: "short_answer",
    question: "Use the log laws to simplify each function, then differentiate it:\n\\(y = \\log_e \\sqrt[5]{x}\\)",
    a: "\\frac{1}{5x}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q12e",
    type: "short_answer",
    question: "Use the log laws to simplify each function, then differentiate it:\n\\(y = \\log_e \\frac{4}{x}\\)",
    a: "-\\frac{1}{x}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q12f",
    type: "short_answer",
    question: "Use the log laws to simplify each function, then differentiate it:\n\\(y = \\log_e \\frac{3}{4x}\\)",
    a: "-\\frac{1}{x}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q12g",
    type: "short_answer",
    question: "Use the log laws to simplify each function, then differentiate it:\n\\(y = \\ln \\sqrt{3 - x}\\)",
    a: "-\\frac{1}{2(3 - x)}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q12h",
    type: "short_answer",
    question: "Use the log laws to simplify each function, then differentiate it:\n\\(y = \\ln \\sqrt{4x + 3}\\)",
    a: "\\frac{2}{4x + 3}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q13a",
    type: "short_answer",
    question: "Find the first and second derivatives of the function, then evaluate both derivatives at the value given.\n\\(f(x) = \\log_e(x - 2)\\) at \\(x = 4\\). (Format: 'f\'(x), f\'\'(x)')",
    a: "1/2, -1/4",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q13b",
    type: "short_answer",
    question: "Find the first and second derivatives of the function, then evaluate both derivatives at the value given.\n\\(f(x) = \\log_e(3x + 1)\\) at \\(x = 0\\). (Format: 'f\'(x), f\'\'(x)')",
    a: "3, -9",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q13c",
    type: "short_answer",
    question: "Find the first and second derivatives of the function, then evaluate both derivatives at the value given.\n\\(f(x) = \\log_e x^3\\) at \\(x = 3\\). (Format: 'f\'(x), f\'\'(x)')",
    a: "1, -1/3",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q13d",
    type: "short_answer",
    question: "Find the first and second derivatives of the function, then evaluate both derivatives at the value given.\n\\(f(x) = x^2 \\log_e x\\) at \\(x = e\\). (Format: 'f\'(x), f\'\'(x)')",
    a: "3e, 5",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q14a",
    type: "short_answer",
    question: "Differentiate the function, then find any values of \\(x\\) for which the derivative is zero.\n\\(y = x \\log_e x - 2x\\)",
    a: "x = e^2",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q14b",
    type: "short_answer",
    question: "Differentiate the function, then find any values of \\(x\\) for which the derivative is zero.\n\\(y = x^3 \\log_e x\\)",
    a: "x = e^{-1/3}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q14c",
    type: "short_answer",
    question: "Differentiate the function, then find any values of \\(x\\) for which the derivative is zero.\n\\(y = \\frac{\\log_e x}{x^2}\\)",
    a: "x = e^{1/2}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q14d",
    type: "short_answer",
    question: "Differentiate the function, then find any values of \\(x\\) for which the derivative is zero.\n\\(y = (\\log_e x)^3\\)",
    a: "x = 1",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q14e",
    type: "short_answer",
    question: "Differentiate the function, then find any values of \\(x\\) for which the derivative is zero.\n\\(y = (\\log_e x)^5\\)",
    a: "x = 1",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q14f",
    type: "short_answer",
    question: "Differentiate the function, then find any values of \\(x\\) for which the derivative is zero.\n\\(y = \\frac{1}{2 + \\log_e x}\\)",
    a: "No values",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q14g",
    type: "short_answer",
    question: "Differentiate the function, then find any values of \\(x\\) for which the derivative is zero.\n\\(y = (3 \\log_e x - 2)^4\\)",
    a: "x = e^{2/3}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q14h",
    type: "short_answer",
    question: "Differentiate the function, then find any values of \\(x\\) for which the derivative is zero.\n\\(y = \\frac{1}{(\\log_e x)^2}\\)",
    a: "No values",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q14i",
    type: "short_answer",
    question: "Differentiate the function, then find any values of \\(x\\) for which the derivative is zero.\n\\(y = \\log_e(2 \\log_e x)\\)",
    a: "No values",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q15a",
    type: "short_answer",
    question: "Find the point(s) where the tangent to the curve is horizontal.\n\\(y = 2x \\ln x\\) (Format: '(x, y)')",
    a: "(e^{-1}, -2e^{-1})",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q15b",
    type: "short_answer",
    question: "Find the point(s) where the tangent to the curve is horizontal.\n\\(y = \\frac{2}{x} + \\ln x\\) (Format: '(x, y)')",
    a: "(2, 1 + \\ln 2)",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5g-q16",
    type: "multi_part",
    question: "Consider the function \\(y = \\frac{x}{2\\ln x}\\).",
    difficulty: "hard",
    timeLimit: 180,
    subQuestions: [
      {
        id: "y12a-5g-q16a",
        type: "short_answer",
        question: "Find the derivative of \\(y = \\frac{x}{2\\ln x}\\).",
        a: "\\frac{\\ln x - 1}{2(\\ln x)^2}"
      },
      {
        id: "y12a-5g-q16b",
        type: "teacher_review",
        question: "Hence show that \\(y = \\frac{x}{2\\ln x}\\) is a solution of the equation \\(\frac{dy}{dx} = \\frac{1}{2} \\left( \\frac{y}{x} - 2\\left(\\frac{y}{x}\\right)^2 \\right)\\).",
        a: "Show by substituting."
      },
    ]
  },
  {
    id: "y12a-5g-q17a",
    type: "short_answer",
    question: "Use the log laws to simplify the function, then differentiate it.\n\\(y = \\log_e((x + 3)(x + 2))\\)",
    a: "\\frac{1}{x + 3} + \\frac{1}{x + 2}",
    difficulty: "hard",
    timeLimit: 180,
  },
  {
    id: "y12a-5g-q17b",
    type: "short_answer",
    question: "Use the log laws to simplify the function, then differentiate it.\n\\(y = \\log_e((x + 4)(2x - 3))\\)",
    a: "\\frac{1}{x + 4} + \\frac{2}{2x - 3}",
    difficulty: "hard",
    timeLimit: 180,
  },
  {
    id: "y12a-5g-q17c",
    type: "short_answer",
    question: "Use the log laws to simplify the function, then differentiate it.\n\\(y = \\ln \\frac{2 + x}{2 - x}\\)",
    a: "\\frac{4}{4 - x^2}",
    difficulty: "hard",
    timeLimit: 180,
  },
  {
    id: "y12a-5g-q17d",
    type: "short_answer",
    question: "Use the log laws to simplify the function, then differentiate it.\n\\(y = \\ln \\frac{4x - 1}{x + 3}\\)",
    a: "\\frac{13}{(4x - 1)(x + 3)}",
    difficulty: "hard",
    timeLimit: 180,
  },
  {
    id: "y12a-5g-q17e",
    type: "short_answer",
    question: "Use the log laws to simplify the function, then differentiate it.\n\\(y = \\log_e \\frac{(x - 5)^2}{2x + 1}\\)",
    a: "\\frac{2}{x - 5} - \\frac{2}{2x + 1}",
    difficulty: "hard",
    timeLimit: 180,
  },
  {
    id: "y12a-5g-q17f",
    type: "short_answer",
    question: "Use the log laws to simplify the function, then differentiate it.\n\\(y = \\log_e (x \\sqrt{x + 2})\\)",
    a: "\\frac{1}{x} + \\frac{1}{2(x + 2)}",
    difficulty: "hard",
    timeLimit: 180,
  },
  {
    id: "y12a-5g-q18a",
    type: "short_answer",
    question: "Use the log laws to simplify the function, then differentiate it.\n\\(y = \\log_e 3^x\\)",
    a: "\\ln 3",
    difficulty: "hard",
    timeLimit: 180,
  },
  {
    id: "y12a-5g-q18b",
    type: "short_answer",
    question: "Use the log laws to simplify the function, then differentiate it.\n\\(y = \\log_e e^{2x}\\)",
    a: "2",
    difficulty: "hard",
    timeLimit: 180,
  },
  {
    id: "y12a-5g-q18c",
    type: "short_answer",
    question: "Use the log laws to simplify the function, then differentiate it.\n\\(y = \\log_e x^{2x}\\)",
    a: "2 \\ln x + 2",
    difficulty: "hard",
    timeLimit: 180,
  },
  {
    id: "y12a-5g-q19",
    type: "multi_part",
    question: "This result will be used in Section 5I.",
    difficulty: "hard",
    timeLimit: 180,
    subQuestions: [
      {
        id: "y12a-5g-q19a",
        type: "short_answer",
        question: "Copy and complete the statement:\n\\(\log_e |x| = \\begin{cases} \dots & \text{for } x > 0, \\ \dots & \text{for } x < 0. \end{cases}\\)",
        a: "\\ln x, \\ln(-x)"
      },
      {
        id: "y12a-5g-q19b",
        type: "teacher_review",
        question: "Use part a to sketch the curve \\(y = \\log_e |x|\\).",
        a: "Sketch showing reflection in y-axis."
      },
      {
        id: "y12a-5g-q19c",
        type: "teacher_review",
        question: "By differentiating separately the two branches in part a, show that \\(\\frac{d}{dx} \\log_e |x| = \\frac{1}{x}\\) for all \\(x \\neq 0\\).",
        a: "Show steps."
      },
      {
        id: "y12a-5g-q19d",
        type: "short_answer",
        question: "Why was \\(x = 0\\) excluded in this discussion?",
        a: "\\ln 0 is undefined."
      },
    ]
  },
];
