export const Y12A_CH5E_QUESTIONS = [
  {
    id: "y12a-5e-q1ai",
    type: "short_answer",
    question: "Use the standard form \\(\int e^x dx = e^x + C\\) to evaluate the definite integral. Then approximate it correct to two decimal places.\n\\(\int_0^1 e^x dx\\)",
    a: "e - 1",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q1aii",
    type: "short_answer",
    question: "Use the standard form \\(\int e^x dx = e^x + C\\) to evaluate the definite integral. Then approximate it correct to two decimal places.\n\\(\int_{-1}^0 e^x dx\\)",
    a: "1 - e^{-1}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q1aiii",
    type: "short_answer",
    question: "Use the standard form \\(\int e^x dx = e^x + C\\) to evaluate the definite integral. Then approximate it correct to two decimal places.\n\\(\int_{-2}^0 e^x dx\\)",
    a: "1 - e^{-2}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q1aiv",
    type: "short_answer",
    question: "Use the standard form \\(\int e^x dx = e^x + C\\) to evaluate the definite integral. Then approximate it correct to two decimal places.\n\\(\int_{-3}^0 e^x dx\\)",
    a: "1 - e^{-3}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q1b",
    type: "short_answer",
    teacher_review: true,
    question: "The graph shows \\(y = e^x\\) from \\(x = -5\\) to \\(x = 1\\), with a scale of 10 divisions to 1 unit, so that 100 little squares equal 1 square unit.\nBy counting squares under the curve from \\(x = 0\\) to \\(x = 1\\), find an approximation to \\(\int_0^1 e^x dx\\), and compare it with the approximation obtained in part a.",
    a: "Approximation by counting squares",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q1ci",
    type: "short_answer",
    teacher_review: true,
    question: "Count squares to the left of the \\(y\\)-axis to obtain approximations to \\(\int_{-1}^0 e^x dx\\)",
    a: "Approximation by counting squares",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q1cii",
    type: "short_answer",
    teacher_review: true,
    question: "Count squares to the left of the \\(y\\)-axis to obtain approximations to \\(\int_{-2}^0 e^x dx\\)",
    a: "Approximation by counting squares",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q1ciii",
    type: "short_answer",
    teacher_review: true,
    question: "Count squares to the left of the \\(y\\)-axis to obtain approximations to \\(\int_{-3}^0 e^x dx\\)",
    a: "Approximation by counting squares",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q1d",
    type: "short_answer",
    teacher_review: true,
    question: "Continue counting squares to the left of \\(x = -3\\), and estimate the total area under the curve to the left of the \\(y\\)-axis.",
    a: "Approximation by counting squares",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q2a",
    type: "short_answer",
    question: "Find the area between \\(y = e^x\\) and the \\(x\\)-axis for \\(-1 \\le x \\le 0\\).",
    a: "1 - e^{-1}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q2b",
    type: "short_answer",
    question: "Find the area between \\(y = e^x\\) and the \\(x\\)-axis for \\(1 \\le x \\le 3\\).",
    a: "e^3 - e",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q2c",
    type: "short_answer",
    question: "Find the area between \\(y = e^x\\) and the \\(x\\)-axis for \\(-1 \\le x \\le 1\\).",
    a: "e - e^{-1}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q2d",
    type: "short_answer",
    question: "Find the area between \\(y = e^x\\) and the \\(x\\)-axis for \\(-2 \\le x \\le 1\\).",
    a: "e - e^{-2}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q3ai",
    type: "short_answer",
    question: "Find the area between the curve \\(y = e^{2x}\\) and the \\(x\\)-axis from \\(x = 0\\) to \\(x = 3\\). Answer in exact form.",
    a: "\\frac{1}{2}(e^6 - 1)",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q3aii",
    type: "short_answer",
    question: "Find the area between the curve \\(y = e^{2x}\\) and the \\(x\\)-axis from \\(x = -3\\) to \\(x = 0\\). Answer in exact form.",
    a: "\\frac{1}{2}(1 - e^{-6})",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q3bi",
    type: "short_answer",
    question: "Find the area between the curve \\(y = e^{-x}\\) and the \\(x\\)-axis from \\(x = 0\\) to \\(x = 1\\). Answer in exact form.",
    a: "1 - e^{-1}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q3bii",
    type: "short_answer",
    question: "Find the area between the curve \\(y = e^{-x}\\) and the \\(x\\)-axis from \\(x = -1\\) to \\(x = 0\\). Answer in exact form.",
    a: "e - 1",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q3ci",
    type: "short_answer",
    question: "Find the area between the curve \\(y = e^{\\frac{1}{3}x}\\) and the \\(x\\)-axis from \\(x = 0\\) to \\(x = 3\\). Answer in exact form.",
    a: "3(e - 1)",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q3cii",
    type: "short_answer",
    question: "Find the area between the curve \\(y = e^{\\frac{1}{3}x}\\) and the \\(x\\)-axis from \\(x = -3\\) to \\(x = 0\\). Answer in exact form.",
    a: "3(1 - e^{-1})",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q4a",
    type: "short_answer",
    question: "Find the area between the \\(x\\)-axis and the given curve between the given \\(x\\)-values:\n\\(y = e^{x+1}\\), for \\(0 \\le x \\le 2\\).",
    a: "e^3 - e",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q4b",
    type: "short_answer",
    question: "Find the area between the \\(x\\)-axis and the given curve between the given \\(x\\)-values:\n\\(y = e^{x+3}\\), for \\(-2 \\le x \\le 0\\).",
    a: "e^3 - e",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q4c",
    type: "short_answer",
    question: "Find the area between the \\(x\\)-axis and the given curve between the given \\(x\\)-values:\n\\(y = e^{2x-1}\\), for \\(0 \\le x \\le 1\\).",
    a: "\\frac{1}{2}(e - e^{-1})",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q4d",
    type: "short_answer",
    question: "Find the area between the \\(x\\)-axis and the given curve between the given \\(x\\)-values:\n\\(y = e^{3x-5}\\), for \\(1 \\le x \\le 2\\).",
    a: "\\frac{1}{3}(e - e^{-2})",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q4e",
    type: "short_answer",
    question: "Find the area between the \\(x\\)-axis and the given curve between the given \\(x\\)-values:\n\\(y = e^{-x+1}\\), for \\(-1 \\le x \\le 1\\).",
    a: "e^2 - 1",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q4f",
    type: "short_answer",
    question: "Find the area between the \\(x\\)-axis and the given curve between the given \\(x\\)-values:\n\\(y = e^{-2x-1}\\), for \\(-2 \\le x \\le -1\\).",
    a: "\\frac{1}{2}(e^3 - e)",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q4g",
    type: "short_answer",
    question: "Find the area between the \\(x\\)-axis and the given curve between the given \\(x\\)-values:\n\\(y = e^{\\frac{1}{2}x+2}\\), for \\(0 \\le x \\le 3\\).",
    a: "2(e^{\\frac{7}{2}} - e^2)",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q4h",
    type: "short_answer",
    question: "Find the area between the \\(x\\)-axis and the given curve between the given \\(x\\)-values:\n\\(y = e^{\\frac{1}{2}x-1}\\), for \\(-2 \\le x \\le 2\\).",
    a: "2(1 - e^{-2})",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q5a",
    type: "short_answer",
    question: "Find the area of the region bounded by the curve \\(y = e^x\\), the \\(x\\)-axis, the \\(y\\)-axis and the line \\(x = 2\\).",
    a: "e^2 - 1",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q5b",
    type: "short_answer",
    question: "Find the area of the region bounded by the curve \\(y = e^{\\frac{1}{2}x}\\), the \\(x\\)-axis, and the lines \\(x = -1\\) and \\(x = 2\\).",
    a: "2(e - e^{-\\frac{1}{2}})",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q5c",
    type: "short_answer",
    question: "Find the area of the region bounded by the curve \\(y = e^{-x}\\), the \\(x\\)-axis, the \\(y\\)-axis and the line \\(x = 1\\).",
    a: "1 - e^{-1}",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q5d",
    type: "short_answer",
    question: "Find the area of the region bounded by the curve \\(y = e^{-\\frac{1}{2}x}\\), the \\(x\\)-axis, and the lines \\(x = -1\\) and \\(x = 2\\).",
    a: "2(e^{\\frac{1}{2}} - e^{-1})",
    difficulty: "easy",
    timeLimit: 90,
  },
  {
    id: "y12a-5e-q6a",
    type: "short_answer",
    question: "Find the area between the curve \\(y = e^{-x} + 1\\) and the \\(x\\)-axis, from \\(x = 0\\) to \\(x = 2\\).",
    a: "3 - e^{-2}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5e-q6b",
    type: "short_answer",
    question: "Find the area between the curve \\(y = 1 - e^x\\) and the \\(x\\)-axis, from \\(x = -1\\) to \\(x = 0\\).",
    a: "e^{-1}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5e-q6c",
    type: "short_answer",
    question: "Find the area between the curve \\(y = e^x + e^{-x}\\) and the \\(x\\)-axis, from \\(x = -2\\) to \\(x = 2\\).",
    a: "2(e^2 - e^{-2})",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5e-q6d",
    type: "short_answer",
    question: "Find the area between the curve \\(y = x^2 + e^x\\) and the \\(x\\)-axis, from \\(x = -3\\) to \\(x = 3\\).",
    a: "18 + e^3 - e^{-3}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5e-q7a",
    type: "short_answer",
    question: "Find the area of the region bounded by the curve \\(y = e^{-x}\\) and the lines \\(x = 2\\) and \\(y = 1\\).",
    a: "1 + e^{-2}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5e-q7b",
    type: "short_answer",
    question: "Find the area of the region in the first quadrant bounded by the coordinate axes and the curve \\(y = e - e^x\\).",
    a: "1",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5e-q7c",
    type: "short_answer",
    question: "Find the area between the \\(x\\)-axis, the curve \\(y = e^x - 1\\) and the line \\(x = -1\\).",
    a: "e^{-1}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5e-q7d",
    type: "short_answer",
    question: "What is the area bounded by \\(x = 2\\), \\(y = e^{-x} - 2\\), the \\(x\\)-axis and the \\(y\\)-axis?",
    a: "3 + e^{-2}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5e-q7e",
    type: "short_answer",
    question: "Find the area of the region bounded by the curve \\(y = e^{-x} - e\\) and the coordinate axes.",
    a: "1",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5e-q7f",
    type: "short_answer",
    question: "Find the area of the region bounded by the curve \\(y = 3 - e^{-x}\\), the \\(x\\)-axis, and the lines \\(x = -1\\) and \\(x = 2\\).",
    a: "9 - e + e^{-2}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5e-q8a",
    type: "short_answer",
    teacher_review: true,
    question: "Sketch the curves \\(y = e^x\\) and \\(y = x + 1\\), and shade the region between them, from \\(x = 0\\) to \\(x = 1\\). Then write down the area of this region as an integral and evaluate it.",
    a: "e - \\frac{5}{2}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5e-q8b",
    type: "short_answer",
    teacher_review: true,
    question: "Sketch the curves \\(y = e^x\\) and \\(y = 1 - x\\), and shade the region between them, from \\(x = 0\\) to \\(x = 1\\). Then write down the area of this region as an integral and evaluate it.",
    a: "e - \\frac{3}{2}",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5e-q9",
    type: "multi_part",
    question: "The diagram shows the region above the \\(x\\)-axis, below both \\(y = e^x\\) and \\(y = e^{-x}\\), between \\(x = -1\\) and \\(x = 1\\).",
    difficulty: "medium",
    timeLimit: 120,
    subQuestions: [
      {
        id: "y12a-5e-q9a",
        type: "short_answer",
        teacher_review: true,
        question: "Explain why the area of this region may be written as area = \\(2 \\int_0^1 e^{-x} dx\\).",
        a: "By symmetry of the region about the y-axis."
      },
      {
        id: "y12a-5e-q9b",
        type: "short_answer",
        question: "Hence find the area of this region.",
        a: "2(1 - e^{-1})"
      },
    ]
  },
  {
    id: "y12a-5e-q10",
    type: "multi_part",
    question: "The diagram shows the region above the \\(x\\)-axis, below both \\(y = e - e^{-x}\\) and \\(y = e - e^x\\).",
    difficulty: "medium",
    timeLimit: 120,
    subQuestions: [
      {
        id: "y12a-5e-q10a",
        type: "short_answer",
        teacher_review: true,
        question: "Explain why the area of this region may be written as area = \\(2 \\int_0^1 (e - e^x) dx\\).",
        a: "By symmetry of the region about the y-axis."
      },
      {
        id: "y12a-5e-q10b",
        type: "short_answer",
        question: "Hence find the area of this region.",
        a: "2"
      },
    ]
  },
  {
    id: "y12a-5e-q11",
    type: "multi_part",
    question: "The diagram shows the region between the curve \\(y = e^x - e^{-x}\\), the \\(x\\)-axis and the lines \\(x = -3\\) and \\(x = 3\\).",
    difficulty: "medium",
    timeLimit: 120,
    subQuestions: [
      {
        id: "y12a-5e-q11a",
        type: "short_answer",
        teacher_review: true,
        question: "Show that \\(y = e^x - e^{-x}\\) is an odd function.",
        a: "f(-x) = e^{-x} - e^x = -(e^x - e^{-x}) = -f(x)"
      },
      {
        id: "y12a-5e-q11b",
        type: "short_answer",
        question: "Hence write down the value of \\(\int_{-3}^3 (e^x - e^{-x}) dx\\) without finding a primitive.",
        a: "0"
      },
      {
        id: "y12a-5e-q11c",
        type: "short_answer",
        teacher_review: true,
        question: "Explain why the area of this region may be written as area = \\(2 \\int_0^3 (e^x - e^{-x}) dx\\).",
        a: "By symmetry of the odd function over a symmetric interval."
      },
      {
        id: "y12a-5e-q11d",
        type: "short_answer",
        question: "Hence find the area of this region.",
        a: "2(e^3 + e^{-3} - 2)"
      },
    ]
  },
  {
    id: "y12a-5e-q12",
    type: "multi_part",
    question: "Consider the curves \\(y = x^2\\) and \\(y = e^{x+1}\\).",
    difficulty: "medium",
    timeLimit: 120,
    subQuestions: [
      {
        id: "y12a-5e-q12a",
        type: "short_answer",
        teacher_review: true,
        question: "Show that the curves intersect at \\(x = -1\\).",
        a: "At x=-1, y=(-1)^2=1. And y=e^{-1+1}=e^0=1."
      },
      {
        id: "y12a-5e-q12b",
        type: "short_answer",
        teacher_review: true,
        question: "Sketch the region in the second quadrant between these two curves and the \\(y\\)-axis.",
        a: "Sketch required."
      },
      {
        id: "y12a-5e-q12c",
        type: "short_answer",
        question: "Find its area.",
        a: "e - \\frac{4}{3}"
      },
    ]
  },
  {
    id: "y12a-5e-q13",
    type: "multi_part",
    question: "Consider the curve \\(y = e^x\\) and the line \\(y = (e - 1)x + 1\\).",
    difficulty: "medium",
    timeLimit: 120,
    subQuestions: [
      {
        id: "y12a-5e-q13a",
        type: "short_answer",
        teacher_review: true,
        question: "Show that they meet at \\(A(0, 1)\\) and \\(B(1, e)\\).",
        a: "Substitution of x=0 and x=1 into both equations yields matching y-values."
      },
      {
        id: "y12a-5e-q13b",
        type: "short_answer",
        teacher_review: true,
        question: "Sketch the graphs, and find the area contained between the line and the curve.",
        a: "\\frac{3}{2} - \\frac{e}{2}"
      },
    ]
  },
  {
    id: "y12a-5e-q14",
    type: "short_answer",
    teacher_review: true,
    question: "Sketch the region between the graphs of \\(y = e^x\\) and \\(y = x\\), between the \\(y\\)-axis and \\(x = 2\\), then find its area.",
    a: "e^2 - 3",
    difficulty: "medium",
    timeLimit: 120,
  },
  {
    id: "y12a-5e-q15",
    type: "multi_part",
    question: "In this question, give all approximations correct to four decimal places.",
    difficulty: "medium",
    timeLimit: 120,
    subQuestions: [
      {
        id: "y12a-5e-q15a",
        type: "short_answer",
        question: "Find the area between the curve \\(y = e^x\\) and the \\(x\\)-axis, for \\(0 \\le x \\le 1\\), by evaluating an appropriate integral. Then approximate the result.",
        a: "1.7183"
      },
      {
        id: "y12a-5e-q15b",
        type: "short_answer",
        question: "Estimate the area using the trapezoidal rule with two subintervals (that is, with three function values).",
        a: "1.7539"
      },
      {
        id: "y12a-5e-q15c",
        type: "short_answer",
        teacher_review: true,
        question: "Is the trapezoidal-rule approximation greater than or less than the exact value? Give a geometric explanation.",
        a: "Greater than. The curve y=e^x is concave up, so the trapezoids lie above the curve."
      },
    ]
  },
];
